#!/usr/bin/env python3
"""Author Grade 7 unique-bank batch 01: 100 Religion and Ethics questions."""
from __future__ import annotations

from collections import Counter
import json
from pathlib import Path
from typing import Any

from build_unique_question_banks import ROOT
from author_grade6_mixed_batch03 import make_question, read_notes_only


OUTPUT = ROOT / "authoring/question-bank-blueprints/grade-7.jsonl"
LABELS_OUTPUT = ROOT / "authoring/question-bank-blueprints/grade-7-labels.json"
SOURCE = ROOT / "turkiye/7-sinif/din-kulturu-ve-ahlak-bilgisi/din-kulturu-ve-ahlak-bilgisi-tum.jsonl"


# note, scenario, evidence, concept, action, inference, misconceptions, rationale
CASES = [
    ("tr-g07-dkab-note-dkab-7-1-1", "Bir öğrenci melekleri görevlerine göre eşleştiren bir kart hazırlıyor.", "Cebrâil için vahyi iletme, İsrâfil için sûra üfleme, Kirâmen Kâtibîn için davranışları kaydetme görevleri yazılıyor.", "Melekler ortak özelliklerinin yanında kaynaklarda bildirilen görevlerine göre sınıflandırılabilir.", "Her meleği güvenilir kaynakta belirtilen göreviyle eşleştirip kaynağı belirsiz özellik eklememek gerekir.", "Farklı görevlerin ayrı kartlarda yer alması, sınıflandırmanın ad benzerliğine değil görev ölçütüne dayandığını gösterir.", ["Bütün meleklerin görevi yalnız vahiy getirmektir.", "Melekler insanlar gibi yiyip içer ve istedikleri zaman görevlerini bırakır.", "Bir meleğe kaynakta bildirilmeyen görev eklemek sınıflandırmayı güçlendirir."], "Melek inancı görünmeyen alanla ilgilidir; sınıflandırma Kur’an ve güvenilir dinî bilgilerde bildirilen ortak özellik ve görevlere dayanır."),
    ("tr-g07-dkab-note-dkab-7-1-2", "Bir zaman şeridinde ölümden sonraki hayatın aşamaları karışık yerleştiriliyor.", "Ölüm ve kabir hayatından sonra kıyamet, yeniden diriliş, mahşer ve hesap aşamalarının geldiği belirtiliyor.", "Ahiret hayatı ölüm, kabir hayatı, kıyamet, yeniden diriliş, mahşer ve hesap gibi ilişkili aşamalarla açıklanır.", "Aşamaları güvenilir kaynakta verilen anlam ve zaman ilişkisine göre sıralamak, kesin tarihi bilinmeyen olaylara tarih uydurmamak gerekir.", "Yeniden dirilişin kıyametten sonra gösterilmesi, şeridin rastgele değil olayların anlam ilişkisine göre kurulması gerektiğini gösterir.", ["Mahşer dünya hayatındaki doğumdan önce gerçekleşir.", "Ahiret aşamalarının sırası ve anlamı birbirinden bağımsızdır.", "Kıyametin kesin tarihini insanlar hesaplayıp değişmez biçimde bilebilir."], "Ahiret aşamaları birbirine karıştırılmadan açıklanır; zamanına ilişkin bilinmeyen ayrıntılar hakkında kesin iddia kurulmaz."),
    ("tr-g07-dkab-note-dkab-7-1-3", "Bir öğrenci ahiret inancının günlük davranışa etkisini tartışıyor.", "Emaneti koruyan, haksızlıktan kaçınan ve yaptığı davranışın sorumluluğunu üstlenen örnekler öne çıkıyor.", "Melek ve ahiret inancı, insanın davranışlarının anlam ve sorumluluk taşıdığı bilincini destekler.", "Bir karar verirken hakkaniyet, sorumluluk ve sonuçları gözetmek; inancı başkasını yargılama aracına dönüştürmemek gerekir.", "Sorumlu davranışların ortaklaşması, inanç bilgisinin yalnız ezber değil ahlaki seçimlerle ilişkili olduğunu gösterir.", ["Ahiret inancı insanın dünyadaki davranışlarından sorumlu olmadığı anlamına gelir.", "Melek inancı yalnız başkalarının hatalarını araştırmayı gerektirir.", "İnanç ile adalet, umut ve öz denetim arasında hiçbir ilişki kurulamaz."], "İnancın kazanımı kişisel sorumluluk, umut ve iyi davranışla açıklanır; insanların niyetleri hakkında hüküm vermeye dönüştürülmez."),
    ("tr-g07-dkab-note-dkab-7-1-4", "Bir öğrenci Nâs suresini yalnız görünür tehlikelerden korunma metni sayıyor.", "Surede insanların Rabbi, Meliki ve İlahı olan Allah’a; cinlerden ve insanlardan gelebilen vesvesenin şerrinden sığınma anlatılıyor.", "Nâs suresi, insanın kalbine kuşku ve kötülük fısıldayan vesveseye karşı Allah’a sığınmasını öğretir.", "Sureyi anlamıyla okuyup vesveseyi fark ederken doğru bilgiye, duaya ve sorumlu davranışa birlikte yönelmek gerekir.", "Vesvesenin hem cinlerden hem insanlardan gelebileceğinin anılması, mesajın yalnız fiziksel bir tehlikeyle sınırlandırılamayacağını gösterir.", ["Nâs suresinde Allah’a sığınma ifadesi bulunmaz.", "Sure yalnız belirli bir yerde okunursa anlam taşır.", "Allah’a sığınmak insanın bilgi edinme ve tedbir alma sorumluluğunu kaldırır."], "Sure, ana kavramları ve bütünü içindeki anlam ilişkisiyle yorumlanır; dua, bilinçli seçim ve tedbir birbirine karşıt gösterilmez."),
    ("tr-g07-dkab-note-dkab-7-2-1", "İki ibadet kartında hac ile umrenin ortak ve farklı yönleri karşılaştırılıyor.", "İhram, tavaf ve sa’y iki ibadette de bulunurken Arafat vakfesi haccın temel uygulamalarından biri olarak gösteriliyor.", "Hac ve umre bazı ortak uygulamalar taşır; hac belirli zamanda Arafat vakfesi gibi kendine özgü menasiki de içerir.", "Karşılaştırmayı ortak ibadetler, zaman ve kendine özgü uygulamalar ölçütleriyle yapmak gerekir.", "Arafat vakfesinin yalnız hac kartında bulunması, iki ibadetin tamamen aynı sayılamayacağını gösterir.", ["Hac ile umrenin bütün uygulamaları ve zamanı eksiksiz aynıdır.", "Tavaf yalnız umrede bulunur, hacda yapılmaz.", "Arafat vakfesi umrenin zorunlu uygulamasıdır."], "Hac ve umre karşılaştırılırken ortak uygulamalar ile hacca özgü menasik birbirinden ayrılır; fıkhi ayrıntılar güvenilir kaynaktan doğrulanır."),
    ("tr-g07-dkab-note-dkab-7-2-2", "Bir aile kurban ibadetini yalnız et elde etme faaliyeti olarak açıklıyor.", "Niyet, Allah’a yakınlaşma bilinci, ibadet şartları ve ihtiyaç sahipleriyle paylaşma birlikte ele alınıyor.", "Kurban, belirli şartlarla yerine getirilen; kulluk, teslimiyet ve paylaşma anlamı taşıyan bir ibadettir.", "İbadetin şartlarını güvenilir kaynaktan öğrenip hayvan refahına, çevre temizliğine ve adil paylaşıma özen göstermek gerekir.", "Niyet ve paylaşmanın birlikte vurgulanması, kurbanın yalnız ekonomik bir et işlemi olmadığını gösterir.", ["Kurban ibadetinde niyet ve paylaşmanın hiçbir önemi yoktur.", "Hayvana eziyet etmek ibadetin şartlarından biridir.", "Kurban yalnız gösteriş ve tüketim amacıyla yerine getirilir."], "Kurban ibadeti biçimsel şart, niyet, canlıya merhamet ve toplumsal dayanışma boyutlarıyla birlikte değerlendirilir."),
    ("tr-g07-dkab-note-dkab-7-2-3", "Bir araştırma grubu hac ve kurbanın kültürel yansımalarını derliyor.", "Hacı uğurlama ve karşılama gelenekleri, bayramlaşma, kurban etini paylaşma ve ihtiyaç sahibini gözetme örnekleri kaydediliyor.", "Hac ve kurban ibadetleri toplumda dayanışma, ziyaret, paylaşma ve ortak hatıra oluşturan kültürel yansımalar doğurmuştur.", "Bir geleneği ibadetin kendisiyle karıştırmadan kökenini, anlamını ve günümüzdeki uygulamasını kaynaklarla incelemek gerekir.", "Farklı yerel uygulamaların ortak paylaşma ve birlik temasında buluşması, kültürel biçim ile temel değerin ayırt edilmesini gerektirir.", ["Yerel bir gelenek dinî ibadetin değişmez ve tek biçimidir.", "Hac ve kurbanın toplumdaki dayanışmayla hiçbir ilişkisi yoktur.", "Kültürel uygulamaları incelerken kaynak ve bağlama bakmak gereksizdir."], "Kültürel yansımalar saygılı gözlemle ele alınır; yerel gelenek, ibadetin temel hükmü ve ortak değer birbirine karıştırılmaz."),
    ("tr-g07-dkab-note-dkab-7-2-4", "Bir öğrenci Kâfirûn suresini farklı inançtaki insanlara hakaret gerekçesi sayıyor.", "Surede ibadet konusunda açık bir ayrım yapılırken herkesin kendi inanç tercihinden sorumlu olduğu anlamı öne çıkıyor.", "Kâfirûn suresi tevhid inancında kararlılığı bildirir; mesajı hakaret veya baskı olarak yorumlanmaz.", "Sureyi bütünüyle okuyup inançta açıklık ile insanlara saygılı davranma sorumluluğunu birlikte korumak gerekir.", "İbadet ayrımının açık fakat saldırısız dille kurulması, kararlılığın saygısızlık anlamına gelmediğini gösterir.", ["Sure insanlara zorla inanç değiştirmeyi emreder.", "Tevhid inancında kararlı olmak başkalarına hakaret etmeyi gerektirir.", "Surenin ibadet ve inanç tercihiyle hiçbir ilişkisi yoktur."], "Sure bağlamından koparılmaz; inanç ilkelerinde açıklık, din ve vicdan alanında saygılı tutumla birlikte değerlendirilir."),
    ("tr-g07-dkab-note-dkab-7-3-1", "İki toplum aynı temel dinî kaynağı bazı uygulama ayrıntılarında farklı yorumluyor.", "Dil, yaşanılan çevre, tarihsel şartlar, yöntem ve insan anlayışındaki farklılıkların yorumları etkileyebildiği görülüyor.", "Din ilahi kaynağa, din anlayışı ise insanların o kaynağı anlama ve yorumlama biçimlerine işaret eder.", "Yorum farkını incelerken ortak temel ilkeleri, kullanılan yöntemi ve tarihsel-kültürel bağlamı ayrı ayrı belirlemek gerekir.", "Farklı çevre ve yöntemlerle oluşan yorumlar, bütün ayrılıkların dinin özünden kaynaklandığı iddiasını desteklemez.", ["İnsanların yorumları hiçbir tarihsel veya kültürel etkiden etkilenmez.", "Her yorum farkı dinin temel ilkelerinin bütünüyle değiştiğini gösterir.", "Din ile din anlayışı tamamen aynı kavramdır ve ayrılamaz."], "Yorum farklılıkları insan unsuruyla açıklanır; ortak inanç esasları ile değişebilen yorum ve uygulamalar birbirine karıştırılmaz."),
    ("tr-g07-dkab-note-dkab-7-3-2", "Öğrenciler İslam düşüncesindeki yorumları bir sınıflandırma tablosuna yerleştiriyor.", "İnanç konularına odaklanan itikadi, ibadet ve uygulamaya odaklanan fıkhi, manevi eğitime odaklanan tasavvufi yorumlar ayrılıyor.", "İslam düşüncesindeki yorum biçimleri ele aldıkları konu ve yöntem bakımından itikadi, fıkhi ve tasavvufi başlıklarda incelenebilir.", "Bir yorumu yalnız adına bakarak değil odaklandığı sorun, kullandığı yöntem ve amaç bakımından sınıflandırmak gerekir.", "Aynı din içinde farklı konu alanlarının bulunması, yorum biçimlerinin birbirini geçersiz kılan ayrı dinler sayılamayacağını gösterir.", ["Fıkhi yorumlar yalnız doğa olaylarını açıklamak için oluşmuştur.", "Tasavvufi yorumun ahlak ve manevi eğitimle hiçbir ilişkisi yoktur.", "Her yorum biçimi birbirinden bağımsız yeni bir din oluşturur."], "Sınıflandırma konu alanına dayanır; mezhep ve yorum farklılıkları ayrıştırıcı veya küçümseyici bir dille sunulmaz."),
    ("tr-g07-dkab-note-dkab-7-3-3", "Bir kültür etkinliğinde tasavvufi düşüncenin temsilcileri ve ortak değerleri araştırılıyor.", "Yunus Emre, Mevlânâ, Hacı Bektaş Veli ve Ahmet Yesevi’nin sevgi, ahlak, gönül eğitimi ve birlik vurguları örnekleniyor.", "Tasavvufi yorumlar insanın manevi ve ahlaki gelişimini; sevgi, samimiyet ve güzel davranışla ilişkilendirir.", "Bir söz veya uygulamayı sahibine ve güvenilir kaynağa dayandırıp tarihsel bağlamıyla yorumlamak gerekir.", "Farklı temsilcilerde benzer ahlaki temaların görülmesi, tasavvufun yalnız tören biçimlerinden ibaret olmadığını gösterir.", ["Tasavvufi yorumlar ahlak ve manevi eğitimle ilgilenmez.", "Her güzel söz kaynağı araştırılmadan istenen kişiye bağlanabilir.", "Tasavvuf yalnız dış görünüş ve gösteri biçimlerinden oluşur."], "Tasavvufi miras güvenilir kaynak, tarihsel bağlam ve ortak ahlaki değerlerle incelenir; kişilere söz isnadında dikkatli olunur."),
    ("tr-g07-dkab-note-dkab-7-3-4", "Bir öğrenci Alevilik-Bektaşilik hakkında sosyal medyadaki tek bir anonim paylaşımı kaynak sayıyor.", "Cem, cemevi, dede, semah, gülbank ve musahiplik kavramları farklı güvenilir kaynaklarda bağlamlarıyla karşılaştırılıyor.", "Alevilik-Bektaşilik hakkında bilgi, kavramları kendi bağlamında açıklayan güvenilir ve çoğul kaynaklardan toplanmalıdır.", "Topluluğun kendi kurumsal kaynakları ile akademik ve resmî bilgileri karşılaştırıp genelleyici yargılardan kaçınmak gerekir.", "Aynı kavramın bağlamlı kaynaklarda tutarlı açıklanması, anonim tek iddianın doğrulanmadan kullanılamayacağını gösterir.", ["Anonim tek paylaşım bütün Alevi-Bektaşi topluluklarını temsil eder.", "Cem ve semah hakkında kaynak karşılaştırmak gereksizdir.", "Bir topluluğu tanıtırken kendi açıklamalarına başvurmak bilimsel araştırmayı bozar."], "İnanç ve kültür grupları saygılı, kaynaklı ve çeşitliliği gözeten dille incelenir; tek örnek bütün topluluğa genellenmez."),
    ("tr-g07-dkab-note-dkab-7-4-1", "Bir tarih şeridinde Hz. Muhammed’in Mekke dönemindeki gelişmeler sıralanıyor.", "Hira’da ilk vahiy, yakın çevreye ve sonra açıktan davet, baskılar, Habeşistan hicretleri, boykot ve Akabe görüşmeleri yer alıyor.", "Mekke dönemi tebliğin başlaması, ilk Müslümanların oluşması ve baskılar karşısında sabırlı mücadelenin geliştiği dönemdir.", "Olayları tarihsel sıra, neden ve sonuç ilişkisiyle düzenleyip güvenilir siyer kaynaklarıyla doğrulamak gerekir.", "Baskılara rağmen davetin sürmesi ve Akabe görüşmelerine ulaşılması, dönemin yalnız tek bir olayla özetlenemeyeceğini gösterir.", ["İlk vahiy Medine’de ve hicretten sonra gelmiştir.", "Mekke döneminde Müslümanlar hiçbir baskıyla karşılaşmamıştır.", "Akabe görüşmeleri ilk vahiyden önce gerçekleşmiştir."], "Siyer olayları kronoloji ve bağlam içinde ele alınır; kişi ve topluluklar hakkında kaynak dışı ayrıntı eklenmez."),
    ("tr-g07-dkab-note-dkab-7-4-2", "Bir öğrenci hicreti plansız bir kaçış olarak nitelendiriyor.", "Medine’ye göç için izin, yol arkadaşı, rehber, güzergâh, emanetlerin iadesi ve tedbirlerin planlandığı anlatılıyor.", "Hicret 622 yılında Mekke’den Medine’ye yapılan; inanç özgürlüğü ve yeni toplum düzeni açısından dönüm noktası olan planlı göçtür.", "Hicreti değerlendirirken sebeplerini, alınan tedbirleri ve Medine’de doğurduğu sonuçları birlikte incelemek gerekir.", "Ayrıntılı hazırlık ve emanet sorumluluğu, tevekkülün tedbirsizlik veya plansızlık anlamına gelmediğini gösterir.", ["Hicret Medine’den Mekke’ye yapılan bir ticaret yolculuğudur.", "Hicrette hiçbir hazırlık veya güvenlik tedbiri alınmamıştır.", "Hicretin Müslüman toplumunun oluşumuyla hiçbir ilişkisi yoktur."], "Hicret kronoloji, sebep-sonuç ve ahlaki sorumluluk boyutlarıyla değerlendirilir; güven ile tedbir birbirine karşıt gösterilmez."),
    ("tr-g07-dkab-note-dkab-7-4-3", "Bir sınıf Medine dönemindeki toplumsal düzenlemeleri ilişki haritasına aktarıyor.", "Mescid-i Nebevi, muhacir-ensar kardeşliği, Medine’de birlikte yaşama ilkeleri, savunma ve barış girişimleri birbiriyle ilişkilendiriliyor.", "Medine dönemi ibadet, eğitim, dayanışma, birlikte yaşama ve toplum güvenliğine yönelik kurum ve ilkelerin geliştiği dönemdir.", "Olayları yalnız savaş başlığına indirmeden kurumlaşma, anlaşmalar, dayanışma ve tebliğ boyutlarıyla birlikte yapılandırmak gerekir.", "Mescit ve kardeşlik uygulamalarının güvenlik olaylarıyla aynı dönemde bulunması, dönemin çok boyutlu toplumsal yapılanma içerdiğini gösterir.", ["Medine döneminde eğitim ve toplumsal dayanışmaya yönelik hiçbir çalışma yapılmamıştır.", "Muhacir-ensar kardeşliği toplum birliğini zayıflatmak için kurulmuştur.", "Medine dönemi yalnız savaşlardan oluşur ve barış girişimi içermez."], "Medine dönemi çok yönlü tarihsel bağlamıyla ele alınır; çatışma, barış, kurumlaşma ve ahlaki ilkeler dengeli biçimde ilişkilendirilir."),
    ("tr-g07-dkab-note-dkab-7-4-4", "Bir öğrenci Nasr suresini başarıdan sonra övünmeyi öğreten bir metin sanıyor.", "Surede Allah’ın yardımı ve fetih geldiğinde insanların dine yöneldiği, ardından Allah’ı överek tesbih etme ve bağışlanma dileme buyuruluyor.", "Nasr suresi başarı karşısında kibir yerine Allah’a şükür, tesbih ve istiğfarla yönelmeyi öğretir.", "Sureyi bütün ayet ilişkisiyle okuyup başarıyı sorumluluk, tevazu ve şükür davranışına dönüştürmek gerekir.", "Fetihten sonra istiğfarın emredilmesi, başarının sınırsız övünme gerekçesi olmadığını gösterir.", ["Nasr suresinde şükür ve bağışlanma dileme yer almaz.", "Başarı elde eden kişi başkalarını küçümsemelidir.", "Sure yardım ve fetih ile insan davranışı arasında hiçbir ilişki kurmaz."], "Surede olay ile öğüt arasındaki bağ korunur; başarı, kibir değil şükür ve sorumluluk bilinciyle yorumlanır."),
    ("tr-g07-dkab-note-dkab-7-5-1", "Bir araştırma tablosunda dört din hakkında ibadet yeri, kutsal metin ve temel kavram bilgileri karşılaştırılıyor.", "Yahudilik için sinagog ve Tevrat, Hristiyanlık için kilise ve İncil; Hinduizm ve Budizm için kendi tarihsel-kültürel kavramları kaynaklı biçimde veriliyor.", "Dinler hakkında bilgi toplarken her geleneği kendi kaynak ve kavramları içinde tanıtmak, benzerlik ve farkları ortak ölçütlerle karşılaştırmak gerekir.", "Resmî, akademik ve geleneğin kendi güvenilir kaynaklarını karşılaştırıp küçümseyici genellemelerden kaçınmak gerekir.", "Ortak ölçüt kullanıldığında hem benzerliklerin hem farkların görünmesi, bir dini diğerinin kavramlarıyla açıklamanın yetersiz olduğunu gösterir.", ["Dört din bütün inanç ve ibadetlerinde eksiksiz aynıdır.", "Bir dini tanımak için yalnız karşıt görüşlü anonim paylaşımlar yeterlidir.", "Dinleri karşılaştırırken saygılı dil ve kaynak doğrulaması gereksizdir."], "Dinler nesnel, kaynaklı ve saygılı dille incelenir; iç çeşitlilik yok sayılmaz ve hiçbir topluluk tek kalıp yargıyla tanımlanmaz."),
]


MODES = ["comprehension"] * 25 + ["application"] * 35 + ["analysis"] * 25 + ["error-analysis"] * 15
LEVELS = [1] * 20 + [2] * 25 + [3] * 30 + [4] * 20 + [5] * 5


def replace_grade(value: Any) -> Any:
    if isinstance(value, str):
        return value.replace("tr-g06-bank-dkab-b01", "tr-g07-bank-dkab-b01").replace("tr.g06.bank.dkab.b01", "tr.g07.bank.dkab.b01")
    if isinstance(value, list):
        return [replace_grade(child) for child in value]
    if isinstance(value, dict):
        return {key: replace_grade(child) for key, child in value.items()}
    return value


def main() -> int:
    notes = read_notes_only(SOURCE)
    labels: dict[str, str] = {}
    records = []
    occurrences: Counter[tuple[str, str]] = Counter()
    for local, (mode, level) in enumerate(zip(MODES, LEVELS), 1):
        base_case = CASES[(local - 1) % len(CASES)]
        key = (base_case[0], mode)
        occurrence = occurrences[key]
        occurrences[key] += 1
        case_values = list(base_case)
        if occurrence:
            suffixes = (
                " Bu ikinci değerlendirmede gözlemdeki neden-sonuç sınırı da korunur.",
                " Bu üçüncü değerlendirmede kararın kapsamı ve sorumluluk ölçütü birlikte sınanır.",
            )
            suffix = suffixes[min(occurrence - 1, len(suffixes) - 1)]
            correct_field = {"comprehension": 3, "application": 4, "analysis": 5, "error-analysis": 3}[mode]
            case_values[correct_field] = str(case_values[correct_field]) + suffix
        case = tuple(case_values)
        record = make_question(local, case, mode, level, notes[case[0]], labels,
                               "Din Kültürü ve Ahlak Bilgisi", batch_number=1, number_base=0)
        record = replace_grade(record)
        record["grade"] = 7
        record["title"] = f"{notes[case[0]]['title']} — 1. özgün üretim partisi"
        records.append(record)
    labels = {replace_grade(key): replace_grade(value) for key, value in labels.items()}
    if len(records) != 100 or Counter(row["correct"] for row in records) != Counter({0: 25, 1: 25, 2: 25, 3: 25}):
        raise AssertionError("batch size or answer balance")
    if Counter(row["questionType"] for row in records) != Counter({"comprehension": 25, "application": 35, "analysis": 25, "error-analysis": 15}):
        raise AssertionError("mode balance")
    if Counter(row["level"] for row in records) != Counter({1: 20, 2: 25, 3: 30, 4: 20, 5: 5}):
        raise AssertionError("difficulty balance")
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(json.dumps(row, ensure_ascii=False, separators=(",", ":")) for row in records) + "\n", encoding="utf-8", newline="\n")
    LABELS_OUTPUT.write_text(json.dumps(labels, ensure_ascii=False, sort_keys=True, indent=2) + "\n", encoding="utf-8", newline="\n")
    print(json.dumps({"grade": 7, "batch": 1, "questions": 100, "subject": "Din Kültürü ve Ahlak Bilgisi", "figures": sum(bool(row.get("figure")) for row in records), "sourceQuestionReads": 0}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
