#!/usr/bin/env python3
"""Append Grade 6 DKAB batch 04 from eighteen note-grounded cases."""
from __future__ import annotations

import json
from typing import Any

from author_grade6_bilisim_batch01 import LABELS_OUTPUT, OUTPUT
from author_grade6_mixed_batch03 import (
    DKAB_SOURCE, LEVEL_SEQUENCE, MODE_SEQUENCE, make_question, read_notes_only,
)


# note, independent scenario, evidence, concept, application, inference,
# three misconceptions, grounded explanation
CASES = [
    ("tr-g06-dkab-note-001", "Bir öğrenci, peygamberlerin ilahi mesajı kendi düşüncelerinden oluşturduğunu iddia ediyor.", "Ders metni vahyin Allah tarafından peygamberlere iletildiğini, onların da mesajı insanlara bildirdiğini açıklıyor.", "Peygamber vahyi oluşturan değil, Allah'tan aldığı mesajı insanlara güvenilir biçimde bildiren elçidir.", "İddiayı değerlendirirken vahyin kaynağı ile peygamberin tebliğ görevini birbirinden ayırmak gerekir.", "Metindeki kaynak ve bildirme ayrımı, mesajın peygamberin kişisel sözü sayılamayacağını gösterir.", ["Peygamberler ilahi kitapları yalnız kendi görüşlerinden yazar.", "Vahyin kaynağı ile onu insanlara bildiren elçi arasında hiçbir ayrım yoktur.", "Peygamberlerin güvenilir olması mesajı doğru aktarmalarıyla ilişkili değildir."], "Peygamber ve vahiy ilişkisinde kaynak Allah, vahyi alan ve insanlara açıklayan kişi peygamberdir; bu roller karıştırılmaz."),
    ("tr-g06-dkab-note-002", "Bir genç, kararlarını verirken vahyin yalnız ibadetlerle ilgili olduğunu, ahlaki tercihlere rehberlik etmediğini söylüyor.", "Konu anlatımında doğruluk, adalet ve sorumluluk gibi davranış ölçütlerinin ilahi rehberlikle ilişkilendirildiği görülüyor.", "Vahiy inanç ve ibadetin yanında insanın ahlaki tercihlerine de rehberlik eder.", "Kararda doğruluk, adalet ve sorumluluk ölçütlerini birlikte kullanmak vahyin rehberliğini günlük hayata taşır.", "Ahlaki örneklerin metinde yer alması, vahyin etkisinin yalnız ibadet uygulamalarıyla sınırlı olmadığını gösterir.", ["Vahiy günlük davranış ve ahlak hakkında hiçbir ölçüt sunmaz.", "İlahi rehberlik insanın düşünerek seçim yapmasını tamamen ortadan kaldırır.", "Adalet ve doğruluk yalnız kişisel zevke bağlıdır, sorumlulukla ilişkilendirilemez."], "Vahiy bilinçli seçimi yok etmez; insanın doğru, iyi ve sorumlu davranışı tanımasına rehberlik eder."),
    ("tr-g06-dkab-note-003", "Bir çalışma kâğıdı Zebur'un Hz. Musa'ya, Tevrat'ın Hz. Davud'a verildiğini yazıyor.", "Ders eşleştirmesinde Tevrat-Hz. Musa, Zebur-Hz. Davud, İncil-Hz. İsa ve Kur'an-Hz. Muhammed bilgileri yer alıyor.", "İlahi kitaplarla peygamberleri eşleştirirken Tevrat Hz. Musa'ya, Zebur Hz. Davud'a verilmiştir.", "Çalışma kâğıdındaki iki eşleştirmeyi doğru bilgiye göre yer değiştirmek gerekir.", "Verilen eşleştirme kaydı, çalışma kâğıdında Tevrat ile Zebur'un peygamberlerinin karıştırıldığını gösterir.", ["Tevrat Hz. Davud'a, Zebur Hz. Musa'ya verilmiştir.", "İncil Hz. Musa'ya, Kur'an Hz. İsa'ya verilmiştir.", "İlahi kitapların hangi peygambere verildiğini bilmek kitaplara imanla ilişkili değildir."], "Kitap-peygamber eşleştirmesi ezberden öte, vahyin insanlara peygamberler aracılığıyla ulaştığını anlamaya hizmet eder."),
    ("tr-g06-dkab-note-004", "Bir öğrenci Felak suresindeki sığınma ifadelerinin insanı hiçbir önlem almamaya yönelttiğini düşünüyor.", "Surenin anlamı kötülüklerden Allah'a sığınmayı öğretirken ders örneği tehlikeye karşı sorumlu tedbiri de vurguluyor.", "Felak suresi Allah'a sığınma bilinci kazandırır; bu bilinç insanın gerekli ve meşru tedbirleri bırakması anlamına gelmez.", "Tehlike karşısında güvenli önlemi alıp dua ve tevekkül bilincini birlikte sürdürmek gerekir.", "Dua ile tedbirin birlikte anılması, sığınmanın pasif ve sorumsuz bekleyiş olmadığını gösterir.", ["Allah'a sığınmak bütün güvenlik önlemlerini gereksiz kılar.", "Felak suresinde kötülüklerden korunma ve sığınma mesajı bulunmaz.", "Tedbir almak Allah'a güvenmemek anlamına gelir."], "Surenin mesajı korkuyu büyütmek değil, kötülükler karşısında Allah'a yönelirken sorumlu davranmayı sürdürmektir."),
    ("tr-g06-dkab-note-005", "Ramazan etkinliği yalnız yemek listesinden oluşuyor; Kur'an okuma, paylaşma ve güzel davranışa hiç yer verilmiyor.", "Öğrenciler etkinliğin ayın manevi, bireysel ve toplumsal yönlerini yansıtmadığını belirtiyor.", "Ramazan; oruçla birlikte Kur'an, ibadet, sabır, şükür ve yardımlaşma bilincinin öne çıktığı aydır.", "Etkinliğe anlam çalışması, paylaşma faaliyeti ve güzel davranış hedefi eklemek Ramazan'ın bütünlüğüne uygundur.", "Eksik öğeler, programın Ramazan'ı yalnız yeme düzenine indirgediğini gösterir.", ["Ramazan'ın anlamı yalnız iftar menüsünün çeşitliliğidir.", "Kur'an ve yardımlaşma Ramazan ayıyla ilişkilendirilemez.", "Oruç davranış ve niyet boyutu olmayan yalnızca takvim değişikliğidir."], "Ramazan'ın anlamı bedensel uygulamayla sınırlı tutulmaz; ibadet, Kur'an ve toplumsal dayanışma birlikte ele alınır."),
    ("tr-g06-dkab-note-006", "Sağlık sorunu yaşayan bir öğrenciye arkadaşları dinî hüküm vererek kesin biçimde oruç tutmasını söylüyor.", "Ders notu sağlık ve özel durumlarda aile, hekim ve güvenilir dinî bilgi kaynağına danışılması gerektiğini belirtiyor.", "Oruçla ilgili sağlık ve yükümlülük durumları kişiye göre değişebilir; öğrenci arkadaşları kesin hüküm vermek yerine yetkili desteğe yönlendirmelidir.", "Öğrenciyi ailesi, hekimi ve güvenilir dinî bilgi kaynağıyla görüşmeye teşvik etmek sorumlu davranıştır.", "Kişisel sağlık bilgisinin bilinmemesi, arkadaş yorumuyla kesin sonuç kurulamayacağını gösterir.", ["Her sağlık durumu için aynı hükmü öğrenci arkadaşları belirleyebilir.", "Hekime danışmak oruç ibadetinin manevi yönünü yok eder.", "Kişinin sağlık koşulları dinî sorumluluk değerlendirmesinde hiçbir zaman dikkate alınmaz."], "Yaşa ve sağlık durumuna ilişkin yüksek riskli kararlar akran tahminiyle verilmez; dinî bilgi ile uzman sağlık değerlendirmesi uygun kaynaklardan alınır."),
    ("tr-g06-dkab-note-007", "Bir öğrenci oruç tutarken kantin sırasındaki arkadaşına sabırsız ve kırıcı davranıyor, sonra bunun oruçla ilgisiz olduğunu söylüyor.", "Konu anlatımı orucun sabır, irade, empati ve güzel davranışla ilişkisini kuruyor.", "Oruç yalnız yeme içmeden uzak durma değil, sabır ve öz denetimi davranışlara yansıtma bilinci de kazandırır.", "Kırıcı sözü fark edip özür dilemek ve sırada sabırlı davranmak orucun ahlaki kazanımına uygundur.", "Kırıcı davranış ile sabır hedefi arasındaki çelişki, ibadetin davranış boyutunun ihmal edildiğini gösterir.", ["Oruçluyken kırıcı sözün sabır ve öz denetimle hiçbir ilişkisi yoktur.", "Empati yalnız kişinin kendi açlığını düşünmesi demektir.", "Özür dilemek orucun kazandırdığı güzel davranışlarla bağdaşmaz."], "Orucun kazanımları kişinin söz, tutum ve başkalarının ihtiyaçlarına duyarlılığında görünür hâle gelir."),
    ("tr-g06-dkab-note-008", "Bir öğrenci iftar duası okunmazsa orucun geçersiz olacağını ileri sürüyor.", "Ders notunda duanın rıza, iman, tevekkül ve şükür anlamı taşıdığı; fakat orucun geçerlilik şartı olmadığı açıklanıyor.", "İftar duası anlamlı ve güzel bir duadır; okunması orucun geçerlilik şartı değildir.", "Duayı anlamıyla okumak veya kişinin kendi sözleriyle şükretmesi mümkündür; geçerlilik hakkında yanlış şart kurulmaz.", "Metnin açık hükmü, dua ile orucun geçerlilik şartının birbirine karıştırıldığını gösterir.", ["İftar duası okunmadığında tutulan oruç kesinlikle geçersiz olur.", "İftar duasında Allah'a güven ve rızık için şükür anlamı bulunmaz.", "İftar anında kişi kendi sözleriyle dua edemez."], "Duanın anlam ve değeri korunurken ona ders notunda bulunmayan zorunlu bir geçerlilik şartı yüklenmez."),
    ("tr-g06-dkab-note-009", "Bir öğrenci yanlışlıkla kırdığı sınıf aracını saklıyor ve suçu başka birine yöneltiyor.", "Gerçek ortaya çıktığında hem arkadaşının haksız yere suçlandığı hem sınıftaki güvenin zedelendiği görülüyor.", "Doğru sözlülük gerçeği söylemeyi, sorumluluğu üstlenmeyi ve başkasını yanıltmamayı gerektirir.", "Öğrencinin gerçeği açıklayıp özür dilemesi ve zararı telafi etmek için sorumluluk alması gerekir.", "Yalanın masum kişiye zarar vermesi, doğruluğun yalnız söz değil adalet ve güvenle de ilişkili olduğunu gösterir.", ["Zarardan kaçınmak için suçu başkasına atmak doğru sözlülüktür.", "Gerçek sonradan ortaya çıkarsa ilk yalanın güvene etkisi kalmaz.", "Doğruluk yalnız kişinin çıkarına olduğunda gerekli bir davranıştır."], "Doğru sözlülük, hatasız görünmek değil hata karşısında gerçeği ve sorumluluğu korumaktır."),
    ("tr-g06-dkab-note-010", "Bahçede yaralı bir kuş gören öğrenci onu oyuncak gibi elden ele dolaştırmak istiyor.", "Bir görevli kuşun strese girdiğini, güvenli bir kutuda uzman yardımı beklemesi gerektiğini söylüyor.", "Merhamet yalnız üzülmek değil, canlının ihtiyacını gözeten ve zarar vermeyen yardım davranışıdır.", "Kuşu gereksiz temas olmadan güvenli alana almak ve yetkili hayvan bakım birimine haber vermek gerekir.", "Uzman uyarısı, iyi niyetli görünen her temasın merhametli ve yararlı olmadığını gösterir.", ["Merhamet yaralı canlıyı eğlence için sürekli elden ele dolaştırmaktır.", "Bir canlıya acımak onun gerçek ihtiyacını araştırmayı gereksiz kılar.", "Zarar verme ihtimali olan davranış iyi niyetliyse mutlaka merhametlidir."], "Merhamet, duyguyu bilgi ve sorumlulukla birleştirir; yardım edilen canlının yararı davranışın ölçütüdür."),
    ("tr-g06-dkab-note-011", "Çevrim içi derste bir öğrenci konuşurken diğerleri sözünü kesip alaycı simgeler gönderiyor.", "Söz hakkı düzenlenip uygun dil kullanıldığında herkes düşüncesini tamamlayabiliyor.", "Adap ve nezaket yüz yüze olduğu kadar dijital ortamda da dinleme, saygılı konuşma ve başkasının hakkını gözetmeyi gerektirir.", "Söz sırasına uymak, alaycı tepkileri bırakmak ve eleştiriyi kişiye saldırmadan ifade etmek gerekir.", "Düzenleme sonrası katılımın artması, nezaketin iletişimi ve ortak öğrenmeyi desteklediğini gösterir.", ["Dijital ortamda söz kesmek ve alay etmek nezaket kurallarının dışındadır.", "Nezaket yalnız büyüklerle konuşurken gerekli, akranlar arasında gereksizdir.", "Eleştiri yapabilmek için kişiyi küçük düşürmek gerekir."], "Adap ve nezaket ortam değişince ortadan kalkmaz; insan onuru, söz hakkı ve uygun dil her iletişimde korunur."),
    ("tr-g06-dkab-note-012", "Bir grup vatan sevgisinin yalnız millî bayramlarda söz söylemekten ibaret olduğunu savunuyor.", "Okul çevresini koruma, kamu malına zarar vermeme ve toplumsal sorumluluk alma örnekleri tartışılıyor.", "Vatan sevgisi bir duygu olduğu kadar ortak değerlere, çevreye ve kamu hakkına karşı sorumlu davranışlarla gösterilir.", "Kamu malını korumak ve yaşanılan çevrenin iyiliği için düzenli sorumluluk almak vatan sevgisini davranışa dönüştürür.", "Günlük sorumluluk örnekleri, sevginin yalnız belirli günlerde söylenen sözlerle sınırlı olmadığını gösterir.", ["Vatan sevgisi kamu malına nasıl davranıldığından bağımsızdır.", "Çevreyi korumak ve topluma katkı vermek vatan sevgisiyle ilişkilendirilemez.", "Vatanı sevmek yalnız başkalarını küçümseyen sözler söylemektir."], "Vatan sevgisi, insanlara ve ortak değerlere zarar vermeden sorumluluk üstlenmekle görünür olur; başka toplumlara düşmanlıkla tanımlanmaz."),
    ("tr-g06-dkab-note-013", "Bir öğrenci Kunut dualarını anlamını düşünmeden yalnız sesleri hızlı tekrarlama olarak görüyor.", "Ders çalışmasında Allah'tan yardım isteme, O'na yönelme, şükür ve bağlılık mesajları belirleniyor.", "Kunut dualarını öğrenmek doğru okumanın yanında içerdiği Allah'a yönelme ve yardım dileme anlamını kavramayı gerektirir.", "Okuyuşu çalışırken anlam bölümlerini günlük şükür ve sorumluluk örnekleriyle ilişkilendirmek gerekir.", "Mesajların belirlenebilmesi, duanın anlamsız ses dizisi olmadığını gösterir.", ["Kunut dualarının anlamla ve Allah'a yönelmeyle ilgisi yoktur.", "Duanın hızlı okunması anlamını kavramaktan her zaman daha önemlidir.", "Kunut yalnız başkalarından yardım istemeyi öğretir."], "Dua öğreniminde doğru okuyuş ile anlam birbirini tamamlar; yorum, metindeki mesaj sınırları içinde yapılır."),
    ("tr-g06-dkab-note-014", "Bir sunum Cahiliye Dönemi toplumunun bütün bireylerini aynı kötü davranışla tanımlıyor.", "Kaynaklarda putperestlik, haksızlık ve kan davası gibi sorunların yanında ticaret ve bazı erdemli davranış örnekleri de yer alıyor.", "Cahiliye toplumundaki yaygın sorunlar eleştirilirken bütün insanları tek özellikte ve istisnasız göstermek tarihsel açıdan doğru değildir.", "Sunumda dönemin sorunlarını kanıtlarla açıklayıp bireyler hakkında kapsayıcı ve mutlak yargıdan kaçınmak gerekir.", "Farklı davranış örnekleri, toplumun her üyesine aynı niteliğin yüklenemeyeceğini gösterir.", ["Cahiliye Dönemi'nde yaşayan herkes istisnasız aynı davranışı göstermiştir.", "Dönemin toplumsal sorunlarını anlamak için tarihsel bağlam gereksizdir.", "Bir toplumdaki yaygın hata, her birey hakkında kesin hüküm kurmayı haklı çıkarır."], "Tarihsel bağlam sorunları görünür kılar; ancak sınırlı kanıt bütün insanları tek ve değişmez bir kalıba sokmak için kullanılamaz."),
    ("tr-g06-dkab-note-015", "Bir öğrenci Hz. Muhammed'in çocukluk yıllarındaki farklı aile büyüklerinin himayesini tek bir kişiyle karıştırıyor.", "Ders çizelgesinde annesi Âmine, dedesi Abdülmuttalib ve daha sonra amcası Ebu Talib'in himayesi sıralı biçimde gösteriliyor.", "Hz. Muhammed'in çocukluk hayatı farklı dönemlerde annesi, dedesi ve amcasının himayesinde devam etmiştir.", "Olayları zaman sırasına yerleştirip her dönemi ilgili aile büyüğüyle eşleştirmek gerekir.", "Çizelgedeki ardışıklık, bütün çocukluk döneminin tek kişinin yanında geçmediğini gösterir.", ["Hz. Muhammed'in bütün çocukluğu yalnız aynı kişinin himayesinde geçmiştir.", "Çocukluk olaylarının zaman sırası tarihsel anlamı hiç etkilemez.", "Yetim büyümesi onun toplumda güvenilir olmasına engel olmuştur."], "Siyer bilgisinde kişi, olay ve zaman ilişkisi kaynak sınırında kurulmalı; çocukluk deneyimlerinden kanıtsız psikolojik sonuç çıkarılmamalıdır."),
    ("tr-g06-dkab-note-016", "Mekke'de iki kişi ticarette anlaşmazlığa düşünce Hz. Muhammed'in dürüst ve güvenilir hakemliğine başvuruyor.", "Her iki tarafın da onun verdiği adil açıklamayı kabul ettiği anlatılıyor.", "Hz. Muhammed peygamberlikten önce de dürüstlüğü ve güvenilirliğiyle tanınmıştır.", "Anlaşmazlıkta tarafları dinleyip adalet ve doğruluk ölçütlerini koruyan çözümü örnek almak gerekir.", "Tarafların onun hakemliğine güvenmesi, toplumda güvenilir kişiliğinin tanındığını destekler.", ["Güvenilirlik yalnız peygamberlikten sonra bir anda ortaya çıkmıştır.", "Adil çözüm için taraflardan yalnız güçlü olanı dinlemek gerekir.", "Ticarette doğruluk ve güvenin toplum ilişkilerine etkisi yoktur."], "Peygamberlik öncesi örnekler onun ahlaki kişiliğini gösterir; bu bilgiler gelecekteki her tarihsel rolü kanıtsız biçimde belirlemek için genişletilmez."),
    ("tr-g06-dkab-note-017", "Bir öğrenci Fil suresini yalnız hayvan adlarının anlatıldığı bir metin olarak yorumluyor.", "Surenin anlam çalışması Kâbe'ye yönelik saldırının sonuçsuz kalmasını ve Allah'ın kudretini vurguluyor.", "Fil suresi yalnız bir hayvanı tanıtmaz; Kâbe'ye yönelik saldırının engellenmesi üzerinden Allah'ın kudretini hatırlatır.", "Sureyi olayın bağlamı ve ana mesajıyla birlikte yorumlamak, ayrıntıyı metnin bütününden koparmamak gerekir.", "Kâbe, saldırı ve sonuç ilişkisi, surenin ana mesajının hayvan tanımından daha kapsamlı olduğunu gösterir.", ["Fil suresinin Kâbe'ye yönelik olay ve Allah'ın kudretiyle ilişkisi yoktur.", "Surede geçen tek bir ayrıntı bütün mesajın yerine konabilir.", "Bir surenin anlamını incelerken olay bağlamına bakmak gereksizdir."], "Sure yorumunda sözcükler, olay örgüsü ve ana mesaj birlikte ele alınır; metinde olmayan ayrıntılar kesin tarihsel bilgi gibi eklenmez."),
    ("tr-g06-dkab-note-018", "Bir müze sergisinde hat levhası, ramazan davulu ve ilahi örnekleri dinî motif olarak sunuluyor.", "Açıklamalar bu örneklerin sanat, gelenek ve musiki içinde dinî anlam taşıdığını; her kültür öğesinin dinî olmadığını belirtiyor.", "Dinî motifler kültürde sanat, musiki, edebiyat ve gelenek içinde görülebilir; ancak kültürün bütün öğeleri dinî motif sayılmaz.", "Bir eseri sınıflandırırken biçiminin yanında taşıdığı anlamı, kullanım bağlamını ve güvenilir açıklamasını incelemek gerekir.", "Farklı alanlardaki örnekler dinin kültüre etkisini gösterirken açıklamadaki sınır, her öğenin dinî sayılamayacağını belirtir.", ["Bir toplumda üretilen bütün sanat ve eşyalar zorunlu olarak dinî motiftir.", "Hat, ilahi ve ramazan geleneği kültürde dinin izleriyle ilişkilendirilemez.", "Motifin anlamını belirlerken bağlam ve kullanım amacı önemli değildir."], "Kültür ile din karşılıklı etkileşim gösterebilir; sınıflandırma yüzey görünüşüne değil anlam, bağlam ve tarihsel kullanıma dayanır."),
]


def contextual_case(case: tuple[Any, ...], mode: str, visit: int) -> tuple[Any, ...]:
    values = list(case)
    if visit and mode == "comprehension":
        original_evidence = str(values[2])
        values[1] = f"Bir kavram kartı şu yeni kanıtla sınanıyor: {original_evidence}"
        values[3] = f"{values[5]} Bu çıkarım, karttaki kanıtın desteklediği kavram sınırını korur."
    elif visit and mode == "application":
        original_evidence = str(values[2])
        values[1] = f"{values[1]} İlk uygulamanın ardından şu sonuç kaydediliyor: {original_evidence}"
        values[4] = f"{values[5]} Bu bulguya dayanarak şu karar uygulanmalıdır: {values[4]}"
    elif visit and mode == "analysis":
        original_scenario, original_evidence = str(values[1]), str(values[2])
        values[1] = f"Bir değerlendirme kartında “{values[6][0]}” iddiası yer alıyor."
        values[2] = f"Asıl vaka “{original_scenario}” biçimindedir ve karşılaştırma kaydı şöyledir: {original_evidence}"
        values[5] = f"{values[3]} Bu nedenle karttaki iddia vaka kanıtıyla desteklenmez."
    if visit:
        evidence = str(values[2])
        evidence_tails = (
            f"Bu değerlendirme, vaka kaydındaki “{evidence}” kanıtıyla sınanır.",
            f"Kararın dayanağı olarak “{evidence}” bulgusu açıkça kullanılmalıdır.",
            f"Bu sonuç, “{evidence}” gözleminin açıklayabildiği kapsamla sınırlıdır.",
            f"Öz kontrolde “{evidence}” kaydıyla çelişen genellemeler elenmelidir.",
            f"Son yorum, “{evidence}” bilgisini koruyup metinde olmayan hüküm eklememelidir.",
        )
        tail = evidence_tails[min(visit - 1, len(evidence_tails) - 1)]
        values[7] = f"{values[7]} {tail}"
    return tuple(values)


def main() -> int:
    notes = read_notes_only(DKAB_SOURCE)
    existing = [json.loads(x) for x in OUTPUT.read_text(encoding="utf-8").splitlines() if x.strip()]
    if len(existing) != 300:
        raise RuntimeError("validated first three batches must exist before batch 04")
    labels = json.loads(LABELS_OUTPUT.read_text(encoding="utf-8"))
    visits: dict[tuple[int, str], int] = {}
    rows = []
    for local, (mode, level) in enumerate(zip(MODE_SEQUENCE, LEVEL_SEQUENCE), 1):
        index = (local - 1) % len(CASES)
        key = (index, mode)
        case = contextual_case(CASES[index], mode, visits.get(key, 0))
        visits[key] = visits.get(key, 0) + 1
        rows.append(make_question(
            local, case, mode, level, notes[case[0]], labels,
            "Din Kültürü ve Ahlak Bilgisi", batch_number=4, number_base=300,
        ))
    OUTPUT.write_text("\n".join(json.dumps(row, ensure_ascii=False, separators=(",", ":")) for row in existing + rows) + "\n", encoding="utf-8", newline="\n")
    LABELS_OUTPUT.write_text(json.dumps(labels, ensure_ascii=False, sort_keys=True, indent=2) + "\n", encoding="utf-8", newline="\n")
    print(json.dumps({"batch": 4, "questions": 100, "religion": 100, "total": 400, "labels": len(labels), "sourceQuestionReads": 0}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
