#!/usr/bin/env python3
"""Append 100 Grade 7 Mathematics questions, batch 11, from notes only."""
from __future__ import annotations

from collections import Counter
import json
from pathlib import Path
from typing import Any

from author_grade6_mixed_batch03 import LEVEL_SEQUENCE, make_question, read_notes_only
from author_grade7_dkab_batch01 import LABELS_OUTPUT, OUTPUT


SOURCE = Path("turkiye/7-sinif/matematik/matematik-tum.jsonl")
MODES = ["comprehension"] * 25 + ["application"] * 35 + ["analysis"] * 25 + ["error-analysis"] * 15


# note id, scenario, evidence, concept, application, inference, misconceptions, rationale
CASES = [
    ("tr.g07.matematik.n001", "Bir deniz araştırmasında yüzey 0, yüzeyin 18 metre altı -18 ve 2,5 metre üstü +2,5 ile kodlanıyor.", "Kayıtta -18 bir tam sayı, +2,5 ise 5/2 biçiminde yazılabilen rasyonel sayı olarak gösteriliyor.", "Doğal sayılar sayma ve sıfır bağlamını; tam sayılar yönlü değişimi; rasyonel sayılar iki tam sayının oranını modelleyebilir.", "Her değeri bağlamdaki referans noktasına ve uygun sayı kümesine göre yorumlayıp işaretin yön anlamını korumak gerekir.", "Aynı referansa göre -18'in aşağıyı, +2,5'in yukarıyı göstermesi işaretin büyüklükten ayrı bir yön bilgisi taşıdığını kanıtlar.", ["Negatif işaret sayının büyüklüğünü yok eder.", "Virgüllü yazılan hiçbir sayı rasyonel olamaz.", "Sıfır her bağlamda ne pozitif ne de referans değeri olabilir."], "Sayı kümesi ve işaret, gerçek durumdaki ölçüm türü ile referansa göre birlikte yorumlanır."),
    ("tr.g07.matematik.n002", "Bir sensör 3/8 saatlik süreyi ondalık gösterimle raporlayacaktır.", "Payda 8=2³ olduğundan bölme sonlu biçimde 0,375 değerinde biter.", "Sadeleşmiş kesrin paydasında yalnız 2 ve 5 asal çarpanları varsa ondalık gösterim sonludur; diğer durumlarda devirli olabilir.", "Kesri sadeleştirip paydanın asal çarpanlarını incelemek ve gerekirse payı paydaya bölmek gerekir.", "3/8'in 0,375'te bitmesi paydadaki asal çarpan yapısıyla uyumludur; yalnız rakam sayısına bakmak yeterli değildir.", ["Her kesrin ondalık gösterimi iki basamakta biter.", "Devir çizgisi yalnız ilk rakamın değerini büyütür.", "Ondalık gösterim ile kesir arasında eşitlik kurulamaz."], "Kesir ve ondalık gösterim eşdeğer değeri temsil eder; sonluluk paydanın sadeleşmiş yapısıyla açıklanır."),
    ("tr.g07.matematik.n003", "Soğuk hava deposunda A=-5/6 °C, B=-0,79 °C ve C=-4/5 °C ölçülüyor.", "Ortak ondalık karşılıklar yaklaşık -0,833, -0,79 ve -0,80 olarak hesaplanıyor.", "Rasyonel sayılar ortak kesir, ondalık veya sayı doğrusu temsiline dönüştürülerek karşılaştırılır; negatiflerde sıfıra yakın olan daha büyüktür.", "Değerleri ortak temsile çevirip negatif işaret nedeniyle sıralama yönünü dikkatle belirlemek gerekir.", "-0,79 sıfıra en yakın olduğundan en büyük; yaklaşık -0,833 ise en küçük değerdir.", ["Negatif sayılarda mutlak değeri büyük olan her zaman daha büyüktür.", "Kesir biçimindeki sayı ondalık sayı ile karşılaştırılamaz.", "Paydası büyük olan kesir işaretten bağımsız olarak büyüktür."], "Karşılaştırma eşdeğer temsiller ve sayı doğrusundaki konumla doğrulanır."),
    ("tr.g07.matematik.n004", "Bir su deposunun 5/6'sı doluyken toplam kapasitenin 1/4'ü kadar su kullanılıyor, sonra kapasitenin 1/10'u kadar su ekleniyor.", "Ortak paydada işlem 50/60-15/60+6/60=41/60 biçiminde kaydediliyor.", "Rasyonel sayı probleminde her nicelik aynı bütüne aitse ortak payda ile toplama-çıkarma yapılır ve sonuç bağlamla denetlenir.", "İşlem sırasını olay akışına göre kurup tüm kesirlerin aynı kapasiteyi referans aldığını doğrulamak gerekir.", "Son doluluk 41/60'tır ve 0 ile 1 arasında olması depo bağlamıyla tutarlıdır.", ["Kesirlerde pay ve paydalar doğrudan ayrı ayrı toplanır.", "Kullanılan miktar başlangıca eklenmelidir.", "Sonuç 1'den büyük çıkarsa kapalı depo bağlamında her zaman kabul edilir."], "Model, işlem ve sonuç aralığı birlikte kontrol edildiğinde rasyonel sayı problemi güvenilir biçimde çözülür."),
    ("tr.g07.matematik.n005", "İki okul bahçesinde 12 ve 30 ağaç bulunuyor; fark ve kat ilişkisi ayrı raporlanacak.", "Toplamsal fark 30-12=18, çarpımsal oran 30/12=5/2 olarak hesaplanıyor.", "Toplamsal karşılaştırma farkı, çarpımsal karşılaştırma bir büyüklüğün diğerinin kaç katı olduğunu açıklar.", "Soruda 'kaç fazla' için çıkarma, 'kaç kat' için bölme kullanıp sonuçların birim ve anlamını ayrı yazmak gerekir.", "18 ağaçlık fark ile 5/2 kat oranı aynı verinin farklı ilişkilerini açıklar; birbirinin yerine kullanılamaz.", ["Fark ile oran aynı sayısal ilişkiyi verir.", "Kaç kat sorusu yalnız toplama ile çözülür.", "Oran kurulurken karşılaştırma yönü sonucu değiştirmez."], "Karşılaştırma türü soru dilinden belirlenir ve seçilen işlemle eşleştirilir."),
    ("tr.g07.matematik.n006", "Bir karışımda her 4 ölçü mavi boya için 7 ölçü beyaz boya kullanılıyor.", "8 ölçü mavi için 14, 12 ölçü mavi için 21 ölçü beyaz gerektiği oran eşitliğiyle bulunuyor.", "Doğru orantıda bir nicelik aynı katsayıyla değiştiğinde diğeri de aynı katsayıyla değişir ve oran sabit kalır.", "Önce sabit oranı belirleyip yeni değerin eski değerin kaç katı olduğunu iki niceliğe de uygulamak gerekir.", "4/7=8/14=12/21 eşitliği karışım ilişkisinin doğru orantılı olduğunu destekler.", ["Bir nicelik artarken diğeri aynı miktarda azalırsa doğru orantı oluşur.", "Orantıda yalnız toplamların eşit olması yeterlidir.", "Her iki değere farklı çarpan uygulamak oranı zorunlu korur."], "Orantılılık, tek örneğe değil birden çok eşleşmede sabit kalan çarpımsal ilişkiye dayanır."),
    ("tr.g07.matematik.n007", "Bir yazıcı sabit hızla 3 dakikada 42 sayfa basıyor ve süre-sayfa ilişkisi tabloya aktarılıyor.", "Birim hız 14 sayfa/dakika; 5 dakikada 70, 8 dakikada 112 sayfa değerleri elde ediliyor.", "Doğru orantı tablosunda y/x oranı sabittir ve grafik orijinden geçen bir doğru oluşturur.", "Tablodan birim oranı bulup eksik hücreleri aynı katsayıyla tamamlamak ve grafikte (0,0) koşulunu denetlemek gerekir.", "42/3=70/5=112/8=14 değerleri tablonun tek bir doğru orantı modeline uyduğunu gösterir.", ["Doğru orantı grafiği orijinden geçmek zorunda değildir.", "Tabloda sabit olması gereken büyüklük y-x farkıdır.", "Süre iki katına çıkarken çıktı sabit kalırsa doğru orantı vardır."], "Tablo, grafik ve denklem aynı sabit oranı temsil ettiğinde model tutarlıdır."),
    ("tr.g07.matematik.n008", "Bir kulübün gelir modeli 3(x+4)-2x biçiminde yazılıyor.", "Dağıtma ve benzer terimleri birleştirme ile 3x+12-2x=x+12 elde ediliyor.", "Cebirsel ifadelerde parantez dağıtılır, benzer terimlerin katsayıları işaretleri korunarak birleştirilir.", "Her terimi işaretiyle izleyip dağıtma sonrası benzer olan ve olmayan terimleri ayırmak gerekir.", "x+12 sonucu, x=5 için hem ilk ifadede hem sade biçimde 17 vererek eşdeğerliği doğrular.", ["3(x+4) ifadesi 3x+4 olur.", "x terimi ile sabit 12 doğrudan 13x yapılır.", "-2x teriminin eksi işareti sadeleştirmede yok sayılır."], "Sembolik dönüşüm dağıtma ve benzer terim kurallarıyla yapılır, yerine koyma ile kontrol edilir."),
    ("tr.g07.matematik.n009", "Bir servis ücreti 24 TL sabit ve kişi başı 7 TL'dir; toplam en fazla 80 TL olabilir.", "24+7n≤80 eşitsizliğinden 7n≤56 ve n≤8 bulunuyor.", "Denklem eşitliği, eşitsizlik ise bir sınır veya aralığı modeller; iki tarafa aynı uygun işlem uygulanarak çözüm korunur.", "Bağlamdaki sabit ve değişken maliyeti ayırıp 'en fazla' ifadesini ≤ ile modellemek gerekir.", "n'nin en çok 8 olması hem eşitsizliği sağlar hem 9 kişi için bütçenin aşılmasıyla sınırı doğrular.", ["'En fazla' ifadesi her zaman ≥ ile gösterilir.", "Sabit ücret kişi sayısıyla çarpılmalıdır.", "Eşitsizlik çözümünde sınır değerin bağlamla kontrolü gereksizdir."], "Cebirsel model sözel sınırı doğru sembolle temsil eder ve sonuç gerçek durumla sınanır."),
    ("tr.g07.matematik.n010", "Bir öğrenci 'ardışık iki tam sayının çarpımı her zaman çifttir' iddiasını cebirsel olarak incelemek istiyor.", "Sayılar n ve n+1 yazıldığında ikisinden birinin çift olduğu ve çarpımın 2'nin katı olduğu görülüyor.", "Genel iddia cebirsel temsil ile kanıtlanabilir; yanlış genel iddia tek geçerli karşı örnekle çürütülebilir.", "İddiayı uygun değişkenle genelleyip sayıların tek-çift durumlarını eksiksiz ele almak gerekir.", "Ardışık sayılardan birinin çift olması bütün tam sayılar için çarpımın çiftliğini açıklar.", ["Birkaç örnek görmek bütün tam sayılar için tek başına kanıttır.", "Karşı örnek iddiayı doğrulamak için kullanılır.", "Ardışık iki sayı aynı anda her zaman tektir."], "Kanıt bütün olasılıkları kapsar; örnek ve karşı örneğin mantıksal rolleri ayrılır."),
    ("tr.g07.matematik.n011", "Bir işlem makinesi girdiye önce 4 ekliyor, sonucu 3 ile çarpıyor ve 6 çıkarıyor.", "x girdisi için adımlar x→x+4→3x+12→3x+6 biçiminde izleniyor.", "Algoritma, işlemleri belirli sırayla ve her adımın çıktısını sonraki adımın girdisi yaparak yapılandırır.", "Sözel yönergeleri sıralı adımlara çevirip parantez etkisini korumak ve örnek girdiyle denetlemek gerekir.", "x=2 için hem adımlar hem 3x+6 ifadesi 12 verdiğinden algoritma ile cebirsel model tutarlıdır.", ["İşlem sırası değişse de çıktı her zaman aynı kalır.", "Önce ekleme için parantez kullanmak gereksizdir.", "Bir adımın çıktısı sonraki adımdan bağımsızdır."], "Algoritma ve cebirsel ifade aynı işlem akışını göstermeli, örnekle çapraz doğrulanmalıdır."),
    ("tr.g07.matematik.n012", "K(-4,2) noktasının y eksenine göre yansıması koordinat düzleminde oluşturuluyor.", "Yansıma sonunda x koordinatı 4, y koordinatı 2 oluyor; nokta ve görüntüsü eksene eşit uzaklıkta kalıyor.", "Y eksenine yansımada x işaret değiştirir, y korunur; yansıma ekseni nokta ile görüntüsünün orta dikmesidir.", "Koordinat kuralını uygulayıp özgün nokta ile görüntünün eksene dik ve eşit uzaklıkta olduğunu kontrol etmek gerekir.", "K(-4,2) ile K'(4,2) noktalarının y eksenine üçer değil dörder birim uzaklığı simetriyi doğrular.", ["Y eksenine yansımada iki koordinat da yer değiştirir.", "Yansıma noktanın eksene uzaklığını değiştirir.", "Görüntü ile özgün nokta eksenin aynı tarafında kalmalıdır."], "Koordinat kuralı ve eşit uzaklık geometrik olarak birlikte doğrulanır."),
    ("tr.g07.matematik.n013", "P ve Q noktalarına eşit uzaklıktaki bir sensör yolu ile bir açının kenarlarına eşit uzaklıktaki rota karşılaştırılıyor.", "İlk geometrik yer PQ'nun orta dikmesi, ikinci geometrik yer açının açıortayı olarak belirleniyor.", "Orta dikme iki noktaya; açıortay ise iki doğru veya ışına eşit uzaklık özelliği taşır.", "Eşit uzaklığın noktalara mı yoksa kenarlara mı ait olduğunu belirleyip uygun inşa aracını seçmek gerekir.", "İki eşit uzaklık koşulunun farklı geometrik yerlere götürmesi, inşa adlarının rastgele değiştirilemeyeceğini gösterir.", ["Orta dikme ile açıortay her durumda aynı doğrudur.", "Eşit uzaklık koşulu inşa seçiminde kullanılmaz.", "Açıortay yalnız karşı kenarın orta noktasını bulur."], "İnşa, hedeflenen eşit uzaklık özelliği ve kesişimlerle gerekçelendirilir."),
    ("tr.g07.matematik.n014", "Eş küp yapısında dört taban konumunun yükseklikleri 1, 3, 2 ve 3 olarak kaydediliyor.", "Üst görünüş dört dolu kare, toplam küp sayısı ise 1+3+2+3=9 olarak bulunuyor.", "Üstten görünüş taban konumlarını gösterir; toplam küp sayısı için her konumdaki sütun yüksekliği de gerekir.", "Farklı yön görünümlerini eşleştirip gizli veya üst üste duran küpleri yükseklik kaydıyla tamamlamak gerekir.", "Dört dolu kareye karşılık dokuz küp bulunması, üst görünüş alanı ile hacimsel küp sayısının aynı olmadığını kanıtlar.", ["Üst görünüşteki kare sayısı her zaman toplam küp sayısıdır.", "Yan görünüş sütun yüksekliği hakkında bilgi vermez.", "Görünmeyen küpler yapıda bulunamaz."], "İki boyutlu görünüşler birlikte okunarak üç boyutlu yapı ve küp sayısı çözümlenir."),
    ("tr.g07.matematik.n015", "Bir park planında yarıçapı 4 m olan yarım daire ile tabanları 6 m ve 10 m, yüksekliği 3 m olan yamuk birleştiriliyor.", "π=3 alındığında yarım daire alanı 24 m², yamuk alanı 24 m² ve toplam 48 m² oluyor.", "Bileşik alan, örtüşmeyen temel bölgelerin uygun alan bağıntılarıyla hesaplanıp toplanması veya çıkarılmasıyla bulunur.", "Şekli daire dilimi, yamuk veya eşkenar dörtgen gibi parçalara ayırıp her parçada doğru ölçüyü kullanmak gerekir.", "İki parçanın eşit 24 m² alan vermesi toplamın 48 m² olduğunu, çevre hesabının alan yerine geçemeyeceğini gösterir.", ["Dairenin alanı yalnız çap ile π'nin çarpımıdır.", "Yamuk alanında tabanlar farkı yükseklikle çarpılır.", "Bileşik bölgede alanlar her durumda birbirinden çıkarılır."], "Alan modeli bölge ayrışımı, birim ve bağıntı seçimiyle doğrulanır."),
    ("tr.g07.matematik.n016", "Boyutları 2 cm, 5 cm ve 8 cm olan kapalı bir kutunun karton alanı hesaplanıyor.", "Karşılıklı yüz çiftleri 2·(2·5+2·8+5·8)=132 cm² sonucunu veriyor.", "Dikdörtgenler prizmasının yüzey alanı üç farklı yüz alanının ikişer kez toplamıdır.", "Açınımdaki altı yüzü eş çiftler hâlinde sayıp birimleri santimetrekare olarak yazmak gerekir.", "132 cm² sonucu bütün yüzleri içerir; 80 cm³ hacim sonucu karton alanını temsil etmez.", ["Yüzey alanı üç ayrıtın çarpımıdır.", "Karşılıklı yüzlerden yalnız biri sayılır.", "Alan birimi santimetreküp yazılır."], "Yüz sayısı, alan bağıntısı ve kare birim birlikte korunur."),
    ("tr.g07.matematik.n017", "Bir prizmanın tabanı 4'e 6 birim küplük dikdörtgen ve yüksekliği 5 katmandır.", "Her katmanda 24, beş katmanda 120 birim küp bulunduğu katman modeliyle görülüyor.", "Prizma hacmi, bir katmandaki birim küp sayısı ile katman sayısının çarpımıdır.", "Taban dizilimini sayıp eş katmanlarla çoğaltmak ve boşluk bulunmadığını doğrulamak gerekir.", "24·5=120 hesabı, hacmin yalnız görünen dış küplerden oluşmadığını gösterir.", ["Hacim yalnız üç boyutun toplamıdır.", "Her katmanda küp sayısı rastgele değişir.", "İçte görünmeyen küpler hacme katılmaz."], "Birim küp modeli hacim bağıntısını katman ve çarpma ilişkisiyle açıklar."),
    ("tr.g07.matematik.n018", "Bir saklama kutusunun taban alanı 36 cm², yüksekliği 7 cm olarak ölçülüyor.", "Hacim 36·7=252 cm³; ters kontrolde 252/36=7 cm bulunuyor.", "Dik prizmanın hacmi taban alanı ile yüksekliğin çarpımıdır ve eksik boyut ters işlemle bulunabilir.", "Verilenlerin ayrıt mı taban alanı mı olduğunu ayırıp uygun bağıntıya birimleriyle yerleştirmek gerekir.", "İleri ve ters işlemin aynı yüksekliği vermesi 252 cm³ hacim hesabını doğrular.", ["Taban alanı yeniden kendiyle çarpılmalıdır.", "Hacim için taban alanı ile yükseklik toplanır.", "Hacim ve yükseklik aynı birimle ifade edilir."], "Bağıntı, boyut analizi ve ters işlem birlikte kullanılır."),
    ("tr.g07.matematik.n019", "Bir sıvı kabının hacmi 1,8 dm³ olarak veriliyor ve mililitre cinsine çevriliyor.", "1 dm³=1000 cm³=1000 mL ilişkisiyle sonuç 1800 mL bulunuyor.", "Hacim dönüşümünde uzunluk biriminin dönüşüm katsayısı küp alınır; 1 cm³ ile 1 mL eşdeğerdir.", "Başlangıç ve hedef birimi belirleyip uygun kübik katsayıyı uygulamak gerekir.", "1,8 dm³ ile 1800 mL eşitliği, ondalık basamağın yalnız rastgele kaydırılmadığını gösterir.", ["1 dm³ yalnız 10 cm³'tür.", "Hacim dönüşümünde katsayı her zaman 100'dür.", "Mililitre ile santimetreküp karşılaştırılamaz."], "Birim dönüşümü boyut derecesine ve tanımlı eşdeğerliğe dayanır."),
    ("tr.g07.matematik.n020", "Üstü açık 40×25×30 cm ölçülerindeki bir saksı kutusu için iç hacim ve kaplama alanı ayrı hesaplanıyor.", "Hacim 30000 cm³; kaplama alanı taban ve dört yan yüzün toplamı olarak 4900 cm² bulunuyor.", "Prizma bağlamında kapasite hacimle, kaplama malzemesi ise açık veya kapalı yüzlerin alanıyla modellenir.", "İstenen büyüklüğü ve eksik yüzü belirleyip hacim ile yüzey alanı bağıntılarını karıştırmamak gerekir.", "Farklı birim ve değerler, aynı kutu için kapasite ile malzeme gereksiniminin ayrı nicelikler olduğunu gösterir.", ["Kaplama alanı üç ayrıtın çarpımıyla bulunur.", "Üstü açık kutuda altı yüzün tamamı kaplanır.", "Hacim santimetrekare birimiyle yazılır."], "Gerçek nesnenin açık-kapalı yüzleri, istenen nicelik ve birim birlikte modellenir."),
    ("tr.g07.matematik.n021", "Yarıçapı 9 cm olan yuvarlak bir plakanın alanı π=3 alınarak inceleniyor.", "Alan 3·9²=243 cm²; yarıçap iki katına çıkarılırsa alan dört katına çıkıyor.", "Daire alanı πr² bağıntısıyla bulunur; yarıçaptaki çarpan alanı karesi kadar etkiler.", "Çap verilmişse önce yarıçapa geçmek, kare alma ve alan birimini doğru kullanmak gerekir.", "Yarıçapın iki katında alanın dört kat olması r² bağıntısının sonucudur.", ["Daire alanı 2πr bağıntısıyla bulunur.", "Yarıçap iki katına çıkınca alan yalnız iki katına çıkar.", "Çap ile yarıçap aynı uzunluktur."], "Alan bağıntısı ölçü, kare etkisi ve birimle birlikte değerlendirilir."),
    ("tr.g07.matematik.n022", "Aynı dairede 45° ve 135° merkez açılı iki dilimin alanları karşılaştırılıyor.", "Açı oranı 135/45=3 olduğundan ikinci dilimin alanı birincinin üç katı oluyor.", "Sabit yarıçaplı bir dairede dilim alanı merkez açıyla doğru orantılıdır.", "Merkez açıyı 360°'ye oranlayıp tam daire alanıyla çarpmak veya iki dilimi açı oranıyla karşılaştırmak gerekir.", "135° dilimin üç kat alan vermesi yarıçap sabitken açı-alan doğru orantısını destekler.", ["Dilim alanı merkez açıdan bağımsızdır.", "Açı üç katına çıkınca alan dokuz katına çıkar.", "Dilim alanı yalnız yayın uzunluğuyla toplanır."], "Dilim, tam dairenin merkez açı oranındaki parçasıdır."),
    ("tr.g07.matematik.n023", "Köşegenleri 12 cm ve 7 cm olan eşkenar dörtgen ile tabanları 9 cm ve 15 cm, yüksekliği 4 cm olan yamuk karşılaştırılıyor.", "Eşkenar dörtgen alanı 42 cm², yamuk alanı 48 cm² olarak hesaplanıyor.", "Eşkenar dörtgen alanı köşegenler çarpımının yarısı; yamuk alanı tabanlar toplamının yükseklikle çarpımının yarısıdır.", "Şeklin verilen ölçülerini doğru bağıntıyla eşleştirip alanları aynı kare birimde karşılaştırmak gerekir.", "48-42=6 cm² fark, yamuğun bu ölçülerle daha büyük alana sahip olduğunu gösterir.", ["Eşkenar dörtgende köşegenler yalnız toplanır.", "Yamukta tabanların farkı kullanılır.", "İki alan farklı kare birimlerle doğrudan karşılaştırılır."], "Şekle özgü alan bağıntıları ve ortak birim karşılaştırmayı güvenilir kılar."),
    ("tr.g07.matematik.n024", "Bir üçgende A köşesinden karşı kenarın orta noktasına, B köşesinden karşı kenara dik ve C köşesinden açıyı iki eş parçaya ayıran doğrular çiziliyor.", "Çizgiler sırasıyla kenarortay, yükseklik ve açıortay olarak etiketleniyor.", "Kenarortay orta noktaya, yükseklik dikliğe, açıortay eş açı ölçülerine göre tanımlanır.", "Her yardımcı elemanı hedeflediği nokta veya açı ilişkisiyle denetlemek gerekir.", "Üç çizginin farklı koşullara dayanması, bazı özel üçgenler dışında aynı doğru sayılmamaları gerektiğini gösterir.", ["Karşı kenara ulaşan her doğru yüksekliktir.", "Açıortay karşı kenarı her zaman ortalar.", "Kenarortay karşı kenara her zaman diktir."], "Üçgen yardımcı elemanları görünüşe değil tanımlayıcı geometrik koşula göre sınıflandırılır."),
    ("tr.g07.matematik.n025", "C köşesinden AB kenarına kenarortay inşa etmek için AB'nin orta noktası pergel ve cetvelle aranıyor.", "A ve B merkezli eş yarıçaplı yayların kesişimleri birleştirilerek orta dikme, bunun AB ile kesişimi M bulunuyor.", "Bir kenarın orta dikmesi kenarın orta noktasını verir; köşeyi bu noktayla birleştirmek kenarortayı oluşturur.", "Yay yarıçaplarını eş seçip iki kesişimi kullanmak, sonra C ile M'yi birleştirmek gerekir.", "M'nin A ve B'ye eşit uzaklığı orta nokta koşulunu, CM çizgisi de kenarortay inşasını doğrular.", ["Tek bir rastgele yay orta noktayı kesin belirler.", "Kenarortay için karşı kenara yalnız dik çizmek yeterlidir.", "Yayların yarıçapları farklı seçilmelidir."], "İnşa adımları eş uzaklık ve orta nokta özellikleriyle gerekçelendirilir."),
    ("tr.g07.matematik.n026", "Okulda ulaşım türü ile geliş süresi arasındaki ilişki araştırılacak.", "Her katmandan öğrenci seçilen örneklemde ulaşım türü kategorik, dakika cinsinden süre nicel değişken olarak kaydediliyor.", "İstatistiksel araştırma sorusu, evren, temsil eden örneklem, değişken türü ve uygun gösterimle uyumlu olmalıdır.", "Soruyu ölçülebilir kılıp iki değişkeni aynı bireylerden, tarafsız ve izinli yöntemle toplamak gerekir.", "Katmanlı örneklem ve eşleştirilmiş iki veri, ilişkinin okul geneline yorumlanmasını tek kulüp örnekleminden daha güçlü destekler.", ["Yalnız isim toplamak araştırma sorusunu yanıtlar.", "Kolay ulaşılan tek grup her zaman evreni temsil eder.", "Kategorik ve nicel değişken aynı araştırmada kullanılamaz."], "Araştırma tasarımı soru, veri türü, temsil ve etik toplama ilkelerini birlikte korur."),
    ("tr.g07.matematik.n027", "İki çalışma grubunun ortalaması 68 iken birinin değerleri 64–72, diğerinin 30–96 aralığında dağılıyor.", "Merkezler eşit, ikinci grubun açıklığı ve değişkenliği daha büyük görünüyor.", "İstatistiksel karşılaştırmada yalnız merkez değil yayılım, örneklem ve grafik ölçeği de değerlendirilir.", "İddiayı ortalama, ortanca, açıklık veya dağılım kanıtıyla sınayıp grafiğin eksenlerini kontrol etmek gerekir.", "Eşit ortalama dağılımların aynı olduğunu göstermez; ikinci grubun daha geniş aralığı farklı bir örüntüdür.", ["Ortalamalar eşitse bütün veri değerleri aynıdır.", "Grafik ekseni sonucu hiçbir zaman etkilemez.", "Tek uç değer bütün evren hakkında kesin karar verir."], "Sonuç, kullanılan özet ölçülerinin neyi gösterip neyi göstermediği belirtilerek tartışılır."),
    ("tr.g07.matematik.n028", "Bir etkinliğin zamanında bitme olasılığı 0,72 olarak tahmin ediliyor.", "Geç bitme olayı bunun tümleyeni olduğundan olasılık 1-0,72=0,28 bulunuyor.", "Bir olay ile gerçekleşmeme biçimindeki tümleyeni ayrık olup örnek uzayı kapsar; olasılıkları toplamı 1'dir.", "Olayın tümleyenini açıkça tanımlayıp verilen olasılığı 1'den çıkarmak gerekir.", "0,72+0,28=1 eşitliği iki olayın birlikte bütün olasılık alanını kapsadığını doğrular.", ["Tümleyen olasılık verilen olasılığa her zaman eşittir.", "Tümleyen için olasılıklar toplanıp 1 aşılmalıdır.", "Bir olay ile tümleyeni aynı anda gerçekleşebilir."], "Tümleyen ilişkisi olay tanımı ve toplamın 1 olmasıyla kontrol edilir."),
    ("tr.g07.matematik.n029", "Bir çarkın dört eş bölmesinden üçü sarı, biri mor renktedir.", "Sarı gelme olasılığı 3/4, mor gelme olasılığı 1/4 olarak bölme sayılarından hesaplanıyor.", "Eş büyüklükte bölmelerde olasılık uygun sonuç sayısının tüm sonuç sayısına oranıdır; renkler eş olasılıklı olmak zorunda değildir.", "Bölmelerin fiziksel eşliğini ve her renge ait uygun sonuç sayısını ayrı ayrı saymak gerekir.", "Sarı bölme sayısının üç kat olması sarı olasılığının morun üç katı olduğunu gösterir.", ["Çarkta iki renk varsa olasılıklar mutlaka 1/2'dir.", "Uygun bölme sayısı olasılığı etkilemez.", "Daha az bölmeli renk daha olasıdır."], "Olasılık, etiket sayısına değil eş sonuç uzayındaki uygun sonuç sayısına dayanır."),
    ("tr.g07.matematik.n030", "1'den 12'ye kadar kartlarda A olayı çift, B olayı 3'ün katı gelmesi olarak tanımlanıyor.", "A∩B={6,12} olduğundan olayların ortak sonuçları vardır ve ayrık değildir.", "Ayrık olayların kesişimi boştur; ayrık olmayan olaylar en az bir ortak sonuç içerir.", "Her olayın sonuç kümesini yazıp kesişimi doğrudan kontrol etmek gerekir.", "6 ve 12'nin iki koşulu da sağlaması olayların ayrık olmadığını kanıtlar.", ["İki olayın adları farklıysa her zaman ayrıktır.", "Ayrıklık için birleşimin boş olması gerekir.", "Ortak sonuç sayısı arttıkça olaylar kesin tümleyen olur."], "Ayrıklık kararı olay adından değil sonuç kümelerinin kesişiminden verilir."),
]


def transform(value: Any) -> Any:
    if isinstance(value, str):
        return value.replace("tr-g06-bank-bty-b11", "tr-g07-bank-matematik-b11").replace("tr.g06.bank.bty.b11", "tr.g07.bank.matematik.b11")
    if isinstance(value, list):
        return [transform(child) for child in value]
    if isinstance(value, dict):
        return {key: transform(child) for key, child in value.items()}
    return value


def main() -> int:
    existing = [json.loads(line) for line in OUTPUT.read_text(encoding="utf-8").splitlines() if line.strip()]
    if len(existing) != 1000:
        raise RuntimeError(f"batch 11 expects 1000 records, found {len(existing)}")
    notes = read_notes_only(SOURCE)
    labels = json.loads(LABELS_OUTPUT.read_text(encoding="utf-8"))
    rows = []
    for local, mode in enumerate(MODES, 1):
        case = CASES[(local - 1) % len(CASES)]
        note = notes[case[0]]
        row = make_question(local, case, mode, LEVEL_SEQUENCE[local - 1], note, labels, "Matematik", batch_number=11, number_base=1000)
        row = transform(row)
        row["grade"] = 7
        row["title"] = f"{note['title']} — 11. özgün üretim partisi"
        rows.append(row)
    if Counter(row["correctIndex"] for row in rows) != Counter({0: 25, 1: 25, 2: 25, 3: 25}):
        raise AssertionError("answer balance")
    labels = {transform(key): transform(value) for key, value in labels.items()}
    OUTPUT.write_text("\n".join(json.dumps(row, ensure_ascii=False, separators=(",", ":")) for row in existing + rows) + "\n", encoding="utf-8", newline="\n")
    LABELS_OUTPUT.write_text(json.dumps(labels, ensure_ascii=False, sort_keys=True, indent=2) + "\n", encoding="utf-8", newline="\n")
    print(json.dumps({"grade": 7, "batch": 11, "questions": 100, "mathematics": 100, "total": 1100, "figures": sum(bool(row.get("figure")) for row in rows), "sourceQuestionReads": 0}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
