#!/usr/bin/env python3
"""Append Grade 6 DKAB batch 05 using a second independent case set."""
from __future__ import annotations

import json

from author_grade6_bilisim_batch01 import LABELS_OUTPUT, OUTPUT
from author_grade6_dkab_batch04 import contextual_case
from author_grade6_mixed_batch03 import (
    DKAB_SOURCE, LEVEL_SEQUENCE, MODE_SEQUENCE, make_question, read_notes_only,
)


CASES = [
    ("tr-g06-dkab-note-001", "Bir grup, peygamberlerin insanlardan tamamen farklı varlıklar olduğu için davranışlarıyla örnek olamayacağını söylüyor.", "Ders notu peygamberlerin insanlar arasından seçildiğini, vahyi açıkladığını ve yaşayışlarıyla örnek olduğunu belirtiyor.", "Peygamberler insanlara gönderilen elçilerdir; vahyi bildirmeleri ve örnek yaşamaları mesajın anlaşılmasına yardımcı olur.", "İddiayı düzeltirken peygamberlerin elçilik görevi ile insanlara örnek oluşunu birlikte açıklamak gerekir.", "İnsanlar arasında yaşayıp mesajı uygulamaları, örnekliğin peygamberlik göreviyle ilişkili olduğunu gösterir.", ["Peygamberler insanlarla hiçbir ortak özelliği olmayan varlıklardır ve örnek alınamaz.", "Peygamberlerin görevi vahyi yaşamadan yalnız yazılı metni saklamaktır.", "İlahi mesajın insan hayatında uygulanabilir olması peygamberlerin örnekliğiyle ilişkili değildir."], "Peygamberlerin beşerî yönü ile Allah tarafından elçi seçilmeleri karıştırılmaz; örneklikleri vahyin hayata yansımasını gösterir."),
    ("tr-g06-dkab-note-002", "İki arkadaş anlaşmazlıkta yalnız kendi çıkarını düşünmenin yeterli olduğunu, ortak bir doğru ölçüte gerek bulunmadığını savunuyor.", "Konu anlatımı vahyin insanı adalet, iyilik ve sorumluluğa yönelten rehberliğini örnekliyor.", "Vahyin rehberliği insanın çıkarını tek ölçüt yapması yerine adalet ve sorumluluğu gözetmesine yardım eder.", "Anlaşmazlıkta iki tarafı dinleyip adalet ve kul hakkı ölçütlerini kullanmak uygun yaklaşımdır.", "Ortak ölçütlerin vurgulanması, yalnız güçlü olanın çıkarının doğruyu belirleyemeyeceğini gösterir.", ["Vahiy yalnız güçlü kişinin çıkarını korumayı öğretir.", "Adalet için iki tarafı dinlemek gereksizdir; ilk konuşan her zaman haklıdır.", "Sorumluluk ve kul hakkı günlük anlaşmazlıklara uygulanamaz."], "İlahi rehberlik, iradeli kararın adalet ve sorumlulukla sınanmasına yardımcı olur; kişisel çıkar tek başına ahlaki ölçüt değildir."),
    ("tr-g06-dkab-note-003", "Bir afişte İncil'in Hz. İsa'ya, Kur'an'ın Hz. Muhammed'e verildiği doğru; Tevrat ve Zebur eşleştirmeleri boş bırakılmış.", "Kaynak tabloda Tevrat-Hz. Musa ve Zebur-Hz. Davud eşleştirmeleri bulunuyor.", "Tevrat Hz. Musa'ya, Zebur Hz. Davud'a, İncil Hz. İsa'ya ve Kur'an Hz. Muhammed'e verilmiştir.", "Afişteki boşlukları güvenilir eşleştirme tablosuna göre tamamlamak ve kaynağı belirtmek gerekir.", "İki dolu ve iki kaynaklı eşleştirme birlikte dört ilahi kitap-peygamber bağını tamamlar.", ["Tevrat Hz. İsa'ya, İncil Hz. Musa'ya verilmiştir.", "Zebur Hz. Muhammed'e, Kur'an Hz. Davud'a verilmiştir.", "İlahi kitapların peygamberlerle ilişkisi vahiy kavramından bağımsızdır."], "Kitaplara iman konusu, ilahi mesajların peygamberlere vahiy yoluyla verilmesi ve insanlara rehber olması çerçevesinde anlaşılır."),
    ("tr-g06-dkab-note-004", "Bir öğrenci Felak suresindeki haset edenin şerrinden sığınma ifadesini, kıskandığı kişiye zarar vermeyi haklı gösteren bir söz sanıyor.", "Anlam çalışması kişinin kötülük yapmasını değil, kötülüklerden Allah'a sığınmasını öğretiyor.", "Felak suresi haset kaynaklı kötülükten Allah'a sığınmayı öğretir; başkasına zarar vermeyi onaylamaz.", "Kıskançlık duygusunu zarar verici davranışa dönüştürmemek ve Allah'a sığınarak iyi davranışı seçmek gerekir.", "Sığınma yöneliminin kötülükten korunmaya yönelik olması, zararı haklı çıkaran yorumla çelişir.", ["Felak suresi haset nedeniyle başkasına zarar vermeyi öğütler.", "Surede Allah'a sığınma ve korunma mesajı bulunmaz.", "Kıskançlık duygusu her türlü zararlı davranışı doğru yapar."], "Sure, kötülüğü üretmeyi değil ondan Allah'a sığınmayı öğretir; anlam yorumunda özne ve eylem yönü ters çevrilmez."),
    ("tr-g06-dkab-note-005", "Okul Ramazan panosunda Kur'an'ın bu ayda indirilmeye başlanması hiç anılmıyor ve ay yalnız yiyecek fotoğraflarıyla tanıtılıyor.", "Öğrenciler konu notunda Ramazan'ın Kur'an ayı olarak nitelenmesi ile oruç ve paylaşma bağını buluyor.", "Ramazan'ın özel yönlerinden biri Kur'an'ın bu ayda indirilmeye başlanmasıdır; oruç ve paylaşma da ayın anlam bütünlüğündedir.", "Panoya Kur'an ayı vurgusu, orucun amacı ve dayanışma örneklerini dengeli biçimde eklemek gerekir.", "Not ile pano karşılaştırması, görsel içeriğin Ramazan'ın temel dinî anlamlarını eksik bıraktığını gösterir.", ["Ramazan'ın Kur'an ile hiçbir ilişkisi yoktur.", "Ayın anlamı yalnız iftarda tüketilen yiyeceklerden oluşur.", "Oruç ve paylaşma Ramazan panosunda konu dışı kabul edilmelidir."], "Ramazan anlatımı tek bir kültürel görünüme indirgenmez; Kur'an, ibadet ve dayanışma boyutları kaynakla ilişkilendirilir."),
    ("tr-g06-dkab-note-006", "Bir öğrenci orucun yalnız başkaları görürken anlamlı olduğunu, tek başınayken niyet ve öz denetimin önem taşımadığını söylüyor.", "Ders notu orucun Allah'ın rızası için niyetle tutulduğunu ve kişinin görünmeyen davranışlarında da sorumluluk taşıdığını vurguluyor.", "Oruç gösteriş için değil Allah'ın rızası için niyet ve öz denetimle yerine getirilen bir ibadettir.", "Kişi yalnızken de niyetini ve güzel davranışını korumalı, ibadeti başkalarının beğenisine bağlamamalıdır.", "Görünmeyen davranışların da sorumluluk alanında olması, orucun yalnız toplumsal gösteri olmadığını gösterir.", ["Oruç yalnız başkaları izlerken değer taşıyan bir gösteridir.", "Niyet ve öz denetimin oruçla hiçbir bağlantısı yoktur.", "İbadetin amacı insanların beğenisini kazanmakla sınırlıdır."], "İbadetin niyet boyutu, davranışın dış görünüşü ile içten yönelişini birlikte değerlendirir; gösteriş ibadetin amacı yapılmaz."),
    ("tr-g06-dkab-note-007", "Bir yardım kampanyasında öğrenci yalnız kendi ihtiyaçlarını düşünüyor ve orucun empatiyle ilgisi olmadığını belirtiyor.", "Sınıf çalışmasında açlık deneyiminin ihtiyaç sahiplerini anlamaya ve paylaşma isteğine katkı sağlayabileceği konuşuluyor.", "Oruç empati ve şükür bilincini güçlendirerek kişinin ihtiyaç sahiplerine karşı duyarlılığını artırabilir.", "Kampanyada ihtiyaçları dinlemek ve imkân ölçüsünde adil paylaşım yapmak bu kazanımı davranışa dönüştürür.", "Açlık deneyimi ile paylaşma isteği arasındaki bağ, orucun toplumsal duyarlılık yönünü gösterir.", ["Oruç kişinin yalnız kendi ihtiyacını düşünmesini öğretir.", "Empati başkasının durumunu anlamak değil kendi görüşünü dayatmaktır.", "Şükür ve paylaşma orucun insana kazandırdıkları arasında sayılamaz."], "Orucun kazanımı otomatik bir duygu değildir; deneyimi bilinçli empati, şükür ve sorumlu yardımlaşmaya dönüştürmek gerekir."),
    ("tr-g06-dkab-note-008", "Bir eşleştirme etkinliğinde 'aleyke tevekkeltü' ifadesi şükür, 'alâ rızkıke eftartü' ifadesi Allah'a güven olarak işaretleniyor.", "Ders notu ilk ifadeyi Allah'a güvenme, ikinciyi O'nun verdiği rızıkla orucu açıp şükretme bilinciyle açıklıyor.", "İftar duasında 'aleyke tevekkeltü' Allah'a güvenmeyi, 'alâ rızkıke eftartü' verilen rızıkla iftar edip şükretmeyi anlatır.", "Eşleştirmeleri anlam tablosuna göre düzeltip dua sözlerini taşıdığı bilinçle birlikte öğrenmek gerekir.", "İki anlamın ters işaretlenmesi, etkinlikte tevekkül ile rızık-şükür bağının karıştırıldığını gösterir.", ["'Aleyke tevekkeltü' yalnız yemek çeşidini belirtir.", "'Alâ rızkıke eftartü' rızık ve şükürle hiçbir ilişki taşımaz.", "İftar duasındaki ifadelerin anlamını öğrenmek gereksizdir."], "Dua ezberi sesleri tekrar etmekle sınırlı değildir; ifade-anlam eşleştirmesi niyet, iman, tevekkül ve şükür bütünlüğünü kurar."),
    ("tr-g06-dkab-note-009", "Kasiyer yanlışlıkla fazla para üstü veriyor; öğrenci kimsenin fark etmediğini düşünerek parayı almak istiyor.", "Fiş ile para karşılaştırıldığında fazlalık açıkça görülüyor ve iade edildiğinde hesap düzeliyor.", "Doğru sözlülük ve dürüstlük, kimse görmese de kendine ait olmayan fazlalığı bildirmeyi gerektirir.", "Fazla parayı kasiyere gösterip fişle birlikte doğru tutarı belirlemek gerekir.", "Hesabın iade sonrası düzelmesi, dürüst davranışın hem gerçeği hem başkasının hakkını koruduğunu gösterir.", ["Kimse fark etmezse fazla para kişinin hakkı olur.", "Dürüstlük yalnız yakalanma ihtimali yüksekse gereklidir.", "Fiş ile para arasındaki açık farkı saklamak doğru sözlülüktür."], "Doğruluk dış denetime bağlı değildir; başkasının hakkını ve güveni kişinin kendi seçimiyle korumasını gerektirir."),
    ("tr-g06-dkab-note-010", "Bir arkadaş, başarısız olan öğrencinin üzülmemesi için hatasını hiç konuşmamayı merhamet sayıyor.", "Öğrenci nazik ve somut geri bildirim aldığında hatasını düzeltiyor; aşağılayıcı sözler ise onu dersten uzaklaştırıyor.", "Merhamet gerçeği saklamak değil, kişiyi incitmeden yararına olacak desteği sunmaktır.", "Hatayı saygılı dille, düzeltme yolu göstererek ve öğrencinin onurunu koruyarak açıklamak gerekir.", "Yapıcı geri bildirimin gelişme sağlaması, merhametin sorumlu yardımla birleştiğini gösterir.", ["Merhamet, kişinin yararına olan her gerçeği ondan gizlemektir.", "Hata yapanı küçük düşürmek en etkili yardım biçimidir.", "Bir davranışın merhametli olması için karşıdakine yarar sağlaması gerekmez."], "Merhamet acıma sözüyle sınırlı değildir; insanın gerçek ihtiyacını gözeten, zarar vermeyen ve gelişimini destekleyen davranıştır."),
    ("tr-g06-dkab-note-011", "Bir öğrenci arkadaşının odasına ve kişisel eşyalarına izin almadan girmenin samimiyet göstergesi olduğunu söylüyor.", "Arkadaşı rahatsız olduğunu belirtiyor; izin istendiğinde sınırlar korunarak iletişim sürüyor.", "Adap ve nezaket, yakın ilişkilerde bile izin istemeyi ve kişisel sınırlara saygı göstermeyi gerektirir.", "Odaya veya özel eşyaya yönelmeden önce açık izin istemek ve verilen sınıra uymak gerekir.", "İzin sonrası rahatsızlığın azalması, nezaket ile mahremiyete saygının ilişkisini gösterir.", ["Yakın arkadaşların kişisel sınırı ve izin hakkı yoktur.", "İzin istemek samimiyeti kesinlikle ortadan kaldırır.", "Nezaket yalnız tanımadığımız kişilere karşı uygulanır."], "Adap, ilişkinin yakınlığına göre insan onurunu ve mahremiyeti iptal etmez; saygılı izin güveni güçlendirir."),
    ("tr-g06-dkab-note-012", "Sel felaketinden sonra bir grup yalnız sosyal medyada slogan paylaşmanın vatan sevgisi için yeterli olduğunu düşünüyor.", "Güvenli gönüllülük, resmî yardım çağrılarına uyma ve kamu kaynaklarını koruma çalışmaları gerçek ihtiyaca katkı sağlıyor.", "Vatan sevgisi sözün yanında toplumun ortak iyiliği için güvenli, düzenli ve sorumlu katkıyla gösterilir.", "Yetkili kurumların yönlendirmesine uyarak uygun yardım yapmak ve yanlış bilgi yaymamak gerekir.", "Somut ihtiyacın güvenli yardımla karşılanması, sevginin sorumluluk davranışına dönüşmesi gerektiğini gösterir.", ["Vatan sevgisi yalnız slogan yazmaktır; toplumsal sorumluluk gerektirmez.", "Afette doğrulanmamış bilgiyi hızla yaymak topluma yardım eder.", "Kamu kaynaklarını korumak vatan sevgisiyle ilişkilendirilemez."], "Vatan sevgisi tehlikeli ve gösteriş amaçlı eylem değil, ortak güvenlik ve yararı gözeten bilinçli sorumluluktur."),
    ("tr-g06-dkab-note-013", "Bir anlam kartı Kunut dualarını yalnız maddi başarı isteme metni olarak tanımlıyor.", "Ders notunda Allah'a yönelme, yardım dileme, şükür, O'na kulluk etme ve kötülükten uzak durma mesajları bulunuyor.", "Kunut duaları yalnız maddi istek değil, Allah'a yönelme, yardım dileme ve kulluk bilinci taşıyan dualardır.", "Kartı metindeki çok yönlü mesajlarla düzeltip her anlamı ilgili ifadeyle eşleştirmek gerekir.", "Birden çok manevi mesajın bulunması, duanın tek bir maddi isteğe indirgenemeyeceğini gösterir.", ["Kunut dualarında Allah'a yönelme ve yardım dileme bulunmaz.", "Duaların bütün anlamı yalnız maddi kazanç istemektir.", "Kötülükten uzak durma ve kulluk bilinci dua anlamıyla ilişkisizdir."], "Kunut duaları anlam bütünlüğü içinde yorumlanır; metnin yalnız bir bölümünü seçip diğer temel mesajları silmek doğru değildir."),
    ("tr-g06-dkab-note-014", "Bir öğrenci İslam öncesi Mekke'deki ticaret hayatı ile toplumsal adaletsizlikleri birbirine alternatif iki anlatı sanıyor.", "Kaynak, ticaretin canlı olduğunu ve aynı toplumda putperestlik, kan davaları ile güçsüzlere haksızlık gibi sorunların görülebildiğini anlatıyor.", "Bir toplumda ekonomik canlılık ile ciddi ahlaki ve toplumsal sorunlar aynı dönemde birlikte bulunabilir.", "Dönemi değerlendirirken ekonomik, dinî ve toplumsal özellikleri ayrı kanıtlarla birlikte ele almak gerekir.", "İki farklı özellik için kanıt bulunması, birinin diğerini otomatik olarak yok etmediğini gösterir.", ["Ticaret varsa bir toplumda hiçbir adaletsizlik bulunamaz.", "Toplumsal sorunların bulunması bütün ekonomik faaliyetin durduğu anlamına gelir.", "Tarihsel dönem yalnız tek bir özellikle açıklanmalıdır."], "Tarihsel bağlam çok boyutludur; tek özellik bütün toplumu ve dönemi açıklayan değişmez etiket hâline getirilmez."),
    ("tr-g06-dkab-note-015", "Bir zaman şeridinde Hz. Muhammed'in dedesinin himayesi, annesiyle geçen dönemden önce gösteriliyor.", "Ders notu çocukluk dönemlerini annesi, sonra dedesi ve ardından amcasının himayesi biçiminde sıralıyor.", "Hz. Muhammed'in çocukluk dönemleri annesi, dedesi ve amcasının himayesi sırasıyla ele alınmalıdır.", "Zaman şeridini kaynakta verilen ardışıklığa göre yeniden düzenlemek gerekir.", "Kaynak sırası ile şeridin çelişmesi, dedenin himayesinin yanlış konuma yerleştirildiğini gösterir.", ["Dedesiyle geçen dönem annesiyle geçen dönemden önce gelir.", "Çocukluk olaylarının sırası kaynakla karşılaştırılamaz.", "Amcasının himayesi çocukluk anlatısında hiç yer almaz."], "Siyer kronolojisi olay ve kişiler arasındaki sırayı korur; kaynakta bulunmayan tarih veya nedenler eklenmez."),
    ("tr-g06-dkab-note-016", "Bir tüccar Hz. Muhammed'in peygamberlikten önce 'el-Emin' olarak anılmasının yalnız servetiyle ilgili olduğunu ileri sürüyor.", "Ders anlatımı bu nitelemeyi dürüstlük, sözünde durma ve güvenilir davranışlarla ilişkilendiriyor.", "El-Emin nitelemesi Hz. Muhammed'in peygamberlikten önceki güvenilir ve dürüst kişiliğiyle ilişkilidir.", "Nitelemenin anlamını servet varsayımıyla değil, kaynakta verilen ahlaki davranış örnekleriyle açıklamak gerekir.", "Dürüstlük ve güvenilirlik örnekleri, nitelemenin mal varlığına indirgenemeyeceğini gösterir.", ["El-Emin nitelemesi yalnız çok mal sahibi olmak demektir.", "Dürüstlük ve sözünde durmanın güvenilirlikle ilişkisi yoktur.", "Hz. Muhammed'in peygamberlik öncesi ahlakı hakkında hiçbir bilgi aktarılamaz."], "Tarihsel niteleme, kaynağın bağladığı ahlaki özelliklerle açıklanır; kanıtsız ekonomik veya siyasi anlam yüklenmez."),
    ("tr-g06-dkab-note-017", "Bir görsel kronoloji Fil Vakası'nı Hz. Muhammed'in doğum çevresindeki tarihsel bağlamdan kopuk, çok sonraki bir olay gibi gösteriyor.", "Ders notu Fil Vakası'nı onun doğduğu yıl çevresindeki önemli olay olarak ele alıyor ve Fil suresinin mesajıyla ilişkilendiriyor.", "Fil Vakası, Hz. Muhammed'in doğduğu dönem çevresinde anılan ve Fil suresinde mesajı verilen olaydır.", "Kronolojiyi ders kaynağındaki dönem ilişkisine göre düzeltip sure mesajını olaydan koparmamak gerekir.", "Kaynakta doğum dönemiyle kurulan bağ, olayın çok sonraya yerleştirilmesiyle çelişir.", ["Fil Vakası Hz. Muhammed'in hayatından yüzyıllar sonra gerçekleşmiştir.", "Fil suresinin anlattığı olay ile Kâbe'nin korunması arasında ilişki yoktur.", "Tarihsel bağlam ile sure anlamı birlikte incelenemez."], "Olayın yaklaşık tarihsel konumu ve surenin ana mesajı kaynak sınırında ilişkilendirilir; ayrıntılı tarih uydurulmaz."),
    ("tr-g06-dkab-note-018", "Bir öğrenci mimarideki her geometrik desenin tek başına dinî motif olduğunu söylüyor.", "Müze açıklaması desenin bulunduğu yapı, kitabe, kullanım amacı ve tarihsel bağlam birlikte incelenmeden kesin sınıflandırma yapılamayacağını belirtiyor.", "Bir görsel öğenin dinî motif sayılması için yalnız biçimine değil, anlamına, kullanım yerine ve kültürel bağlamına bakılmalıdır.", "Deseni yapı, kitabe ve kullanım amacıyla birlikte inceleyip sınıflandırmayı kanıta dayandırmak gerekir.", "Ek bağlam gereksinimi, yüzeydeki geometrik biçimin tek başına kesin dinî anlam taşımadığını gösterir.", ["Her geometrik şekil bulunduğu yerden bağımsız olarak kesin dinî motiftir.", "Bir motifin kullanım yeri ve tarihsel açıklaması anlamını etkilemez.", "Dinî motifler mimari, edebiyat veya musikide hiçbir zaman görülmez."], "Kültürel motif yorumu biçim benzerliğine indirgenmez; anlam, işlev ve tarihsel kullanım birlikte doğrulanır."),
]


def main() -> int:
    notes = read_notes_only(DKAB_SOURCE)
    existing = [json.loads(x) for x in OUTPUT.read_text(encoding="utf-8").splitlines() if x.strip()]
    if len(existing) != 400:
        raise RuntimeError("validated first four batches must exist before batch 05")
    labels = json.loads(LABELS_OUTPUT.read_text(encoding="utf-8"))
    visits: dict[tuple[int, str], int] = {}
    rows = []
    for local, (mode, level) in enumerate(zip(MODE_SEQUENCE, LEVEL_SEQUENCE), 1):
        index = (local - 1) % len(CASES)
        key = (index, mode)
        case = contextual_case(CASES[index], mode, visits.get(key, 0))
        visits[key] = visits.get(key, 0) + 1
        rows.append(make_question(
            local, case, mode, level, notes[case[0]], labels,
            "Din Kültürü ve Ahlak Bilgisi", batch_number=5, number_base=400,
        ))
    OUTPUT.write_text("\n".join(json.dumps(row, ensure_ascii=False, separators=(",", ":")) for row in existing + rows) + "\n", encoding="utf-8", newline="\n")
    LABELS_OUTPUT.write_text(json.dumps(labels, ensure_ascii=False, sort_keys=True, indent=2) + "\n", encoding="utf-8", newline="\n")
    print(json.dumps({"batch": 5, "questions": 100, "religion": 100, "total": 500, "labels": len(labels), "sourceQuestionReads": 0}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
