"""Localized building blocks for AliKa's creative charades prompts."""
from __future__ import annotations


LANGUAGES = ("tr", "en", "de", "es", "fr", "pt", "ru", "ja", "ko")

# The first 20 are universal roles. The final five are culture-local prompts.
SUBJECTS = {
    "tr": ["kedi", "köpek", "tavşan", "penguen", "fil", "maymun", "aslan", "ayı",
           "kurbağa", "kanguru", "aşçı", "astronot", "itfaiyeci", "sihirbaz", "robot",
           "korsan", "dedektif", "süper kahraman", "kaşif", "bilim insanı",
           "Nasreddin Hoca", "meddah", "yağlı güreşçi", "simitçi", "halk oyunu dansçısı"],
    "en": ["cat", "dog", "rabbit", "penguin", "elephant", "monkey", "lion", "bear",
           "frog", "kangaroo", "chef", "astronaut", "firefighter", "magician", "robot",
           "pirate", "detective", "superhero", "explorer", "scientist",
           "tea-time host", "cricket player", "double-decker driver", "cowboy", "jazz musician"],
    "de": ["Katze", "Hund", "Kaninchen", "Pinguin", "Elefant", "Affe", "Löwe", "Bär",
           "Frosch", "Känguru", "Koch", "Astronaut", "Feuerwehrmann", "Zauberer", "Roboter",
           "Pirat", "Detektiv", "Superheld", "Entdecker", "Wissenschaftler",
           "Brezelbäcker", "Alphornspieler", "Fußballtorwart", "Märchenerzähler", "Kuckucksuhrmacher"],
    "es": ["gato", "perro", "conejo", "pingüino", "elefante", "mono", "león", "oso",
           "rana", "canguro", "chef", "astronauta", "bombero", "mago", "robot", "pirata",
           "detective", "superhéroe", "explorador", "científico", "bailaor de flamenco",
           "mariachi", "gaucho", "vendedor de churros", "luchador enmascarado"],
    "fr": ["chat", "chien", "lapin", "manchot", "éléphant", "singe", "lion", "ours",
           "grenouille", "kangourou", "chef cuisinier", "astronaute", "pompier", "magicien",
           "robot", "pirate", "détective", "super-héros", "explorateur", "scientifique",
           "mime parisien", "crêpier", "joueur de pétanque", "styliste", "accordéoniste"],
    "pt": ["gato", "cachorro", "coelho", "pinguim", "elefante", "macaco", "leão", "urso",
           "sapo", "canguru", "chef", "astronauta", "bombeiro", "mágico", "robô", "pirata",
           "detetive", "super-herói", "explorador", "cientista", "sambista", "capoeirista",
           "cantor de fado", "jogador de futebol", "baterista de carnaval"],
    "ru": ["кот", "собака", "кролик", "пингвин", "слон", "обезьяна", "лев", "медведь",
           "лягушка", "кенгуру", "повар", "космонавт", "пожарный", "фокусник", "робот",
           "пират", "детектив", "супергерой", "путешественник", "учёный", "балалаечник",
           "мастер матрёшек", "фигурист", "артист цирка", "шахматист"],
    "ja": ["猫", "犬", "ウサギ", "ペンギン", "ゾウ", "サル", "ライオン", "クマ", "カエル",
           "カンガルー", "料理人", "宇宙飛行士", "消防士", "魔法使い", "ロボット", "海賊",
           "探偵", "スーパーヒーロー", "探検家", "科学者", "侍", "忍者", "すし職人", "力士", "和太鼓奏者"],
    "ko": ["고양이", "강아지", "토끼", "펭귄", "코끼리", "원숭이", "사자", "곰", "개구리",
           "캥거루", "요리사", "우주비행사", "소방관", "마술사", "로봇", "해적", "탐정",
           "슈퍼히어로", "탐험가", "과학자", "태권도 선수", "한복 무용가", "케이팝 댄서",
           "김치 장인", "전통 궁수"],
}

ACTIONS = {
    "young": {
        "tr": ["kocaman esneyerek uyanmak", "parmak ucunda yürümek", "dev bir sandviç yemek",
               "ekşi limonata içmek", "ip atlamak", "yerinde dans etmek", "kayıp oyuncağı aramak", "aniden uyuyakalmak"],
        "en": ["wake up with a huge yawn", "walk on tiptoe", "eat a giant sandwich", "drink sour lemonade",
               "jump rope", "dance in place", "search for a lost toy", "fall asleep suddenly"],
        "de": ["mit einem riesigen Gähnen aufwachen", "auf Zehenspitzen gehen", "ein riesiges Sandwich essen",
               "saure Limonade trinken", "Seil springen", "auf der Stelle tanzen", "ein verlorenes Spielzeug suchen", "plötzlich einschlafen"],
        "es": ["despertarse con un gran bostezo", "caminar de puntillas", "comer un sándwich gigante",
               "beber limonada agria", "saltar a la cuerda", "bailar sin moverse del sitio", "buscar un juguete perdido", "quedarse dormido de repente"],
        "fr": ["se réveiller avec un énorme bâillement", "marcher sur la pointe des pieds", "manger un sandwich géant",
               "boire une limonade très acide", "sauter à la corde", "danser sur place", "chercher un jouet perdu", "s'endormir soudainement"],
        "pt": ["acordar com um bocejo enorme", "andar na ponta dos pés", "comer um sanduíche gigante",
               "beber limonada azeda", "pular corda", "dançar no mesmo lugar", "procurar um brinquedo perdido", "adormecer de repente"],
        "ru": ["проснуться с огромным зевком", "идти на цыпочках", "есть гигантский бутерброд",
               "пить кислый лимонад", "прыгать через скакалку", "танцевать на месте", "искать потерянную игрушку", "внезапно уснуть"],
        "ja": ["大あくびをして目を覚ます", "つま先で歩く", "巨大なサンドイッチを食べる", "酸っぱいレモネードを飲む",
               "縄跳びをする", "その場で踊る", "なくしたおもちゃを探す", "急に眠ってしまう"],
        "ko": ["크게 하품하며 일어나기", "발끝으로 걷기", "거대한 샌드위치 먹기", "신 레모네이드 마시기",
               "줄넘기하기", "제자리에서 춤추기", "잃어버린 장난감 찾기", "갑자기 잠들기"],
    },
    "mid": {
        "tr": ["sıkışmış kavanozu açmak", "kaygan zeminden geçmek", "görünmez yağmurdan kaçmak", "çok ağır bir kutu taşımak",
               "komik bir özçekim yapmak", "hayali bisiklete binmek", "vızıldayan sineği kovalamak", "ip üzerinde dengede durmak"],
        "en": ["open a stuck jar", "cross a slippery floor", "escape invisible rain", "carry a very heavy box",
               "take a funny selfie", "ride an imaginary bicycle", "chase a buzzing fly", "balance on a rope"],
        "de": ["ein festsitzendes Glas öffnen", "einen rutschigen Boden überqueren", "unsichtbarem Regen entkommen", "eine sehr schwere Kiste tragen",
               "ein lustiges Selfie machen", "auf einem unsichtbaren Fahrrad fahren", "eine summende Fliege jagen", "auf einem Seil balancieren"],
        "es": ["abrir un frasco atascado", "cruzar un suelo resbaladizo", "escapar de una lluvia invisible", "cargar una caja muy pesada",
               "hacerse un selfi divertido", "montar en una bicicleta imaginaria", "perseguir una mosca zumbona", "mantener el equilibrio sobre una cuerda"],
        "fr": ["ouvrir un bocal coincé", "traverser un sol glissant", "échapper à une pluie invisible", "porter une boîte très lourde",
               "prendre un selfie amusant", "rouler sur un vélo imaginaire", "chasser une mouche qui bourdonne", "tenir en équilibre sur une corde"],
        "pt": ["abrir um pote emperrado", "atravessar um chão escorregadio", "fugir de uma chuva invisível", "carregar uma caixa muito pesada",
               "tirar uma selfie engraçada", "andar numa bicicleta imaginária", "perseguir uma mosca zumbindo", "equilibrar-se numa corda"],
        "ru": ["открывать застрявшую банку", "переходить скользкий пол", "убегать от невидимого дождя", "нести очень тяжёлую коробку",
               "делать смешное селфи", "ехать на воображаемом велосипеде", "гоняться за жужжащей мухой", "балансировать на канате"],
        "ja": ["固い瓶のふたを開ける", "滑りやすい床を渡る", "見えない雨から逃げる", "とても重い箱を運ぶ",
               "面白い自撮りをする", "見えない自転車に乗る", "飛び回るハエを追う", "ロープの上でバランスを取る"],
        "ko": ["꽉 닫힌 병뚜껑 열기", "미끄러운 바닥 건너기", "보이지 않는 비 피하기", "아주 무거운 상자 나르기",
               "재미있는 셀카 찍기", "상상 속 자전거 타기", "윙윙대는 파리 쫓기", "줄 위에서 균형 잡기"],
    },
    "teen": {
        "tr": ["telefonun şarjının bittiğini fark etmek", "ağır çekime yakalanmak", "hayali gitarla konser vermek", "hareketli spot ışığından saklanmak",
               "sessiz bir tartışmayı kazanmak", "Ay'da yürümek", "imkânsız bulmacayı çözmek", "son saniye golünü kutlamak"],
        "en": ["realize the phone battery is dead", "get caught in slow motion", "give an invisible-guitar concert", "hide from a moving spotlight",
               "win a silent argument", "walk on the Moon", "solve an impossible puzzle", "celebrate a last-second goal"],
        "de": ["merken, dass der Handyakku leer ist", "in Zeitlupe geraten", "ein Konzert mit unsichtbarer Gitarre geben", "sich vor einem wandernden Scheinwerfer verstecken",
               "einen stummen Streit gewinnen", "auf dem Mond gehen", "ein unmögliches Rätsel lösen", "ein Tor in letzter Sekunde feiern"],
        "es": ["descubrir que el móvil no tiene batería", "quedar atrapado en cámara lenta", "dar un concierto con una guitarra invisible", "esconderse de un foco móvil",
               "ganar una discusión silenciosa", "caminar por la Luna", "resolver un rompecabezas imposible", "celebrar un gol en el último segundo"],
        "fr": ["découvrir que le téléphone n'a plus de batterie", "se retrouver au ralenti", "donner un concert avec une guitare invisible", "se cacher d'un projecteur mobile",
               "gagner une dispute silencieuse", "marcher sur la Lune", "résoudre une énigme impossible", "fêter un but à la dernière seconde"],
        "pt": ["perceber que a bateria do celular acabou", "ficar preso em câmera lenta", "dar um show com guitarra invisível", "esconder-se de um holofote em movimento",
               "vencer uma discussão silenciosa", "caminhar na Lua", "resolver um quebra-cabeça impossível", "comemorar um gol no último segundo"],
        "ru": ["понять, что телефон разрядился", "попасть в замедленное движение", "дать концерт с невидимой гитарой", "прятаться от движущегося прожектора",
               "выиграть немой спор", "ходить по Луне", "решать невозможную головоломку", "праздновать гол на последней секунде"],
        "ja": ["スマホの充電切れに気づく", "スローモーションになる", "見えないギターでコンサートをする", "動くスポットライトから隠れる",
               "無言の議論に勝つ", "月面を歩く", "不可能なパズルを解く", "終了直前のゴールを祝う"],
        "ko": ["휴대전화 배터리가 꺼진 걸 깨닫기", "슬로 모션에 갇히기", "보이지 않는 기타로 공연하기", "움직이는 조명 피하기",
               "말없이 논쟁에서 이기기", "달 위를 걷기", "불가능한 퍼즐 풀기", "마지막 순간의 골 축하하기"],
    },
    "senior": {
        "tr": ["yanlış odaya girip normal davranmak", "notları kaybolmuş bir konuşma yapmak", "yırtık haritayla yol bulmak", "zamana karşı yemek pişirmek",
               "dramatik bir film sahnesi oynamak", "karmaşık bir dans öğretmek", "kalabalık pazarda pazarlık yapmak", "orkestra yönetmek"],
        "en": ["enter the wrong room and act normal", "give a speech with missing notes", "navigate with a torn map", "cook against the clock",
               "perform a dramatic movie scene", "teach a complicated dance", "bargain in a busy market", "conduct an orchestra"],
        "de": ["den falschen Raum betreten und normal tun", "eine Rede mit fehlenden Notizen halten", "mit einer zerrissenen Karte navigieren", "gegen die Uhr kochen",
               "eine dramatische Filmszene spielen", "einen komplizierten Tanz beibringen", "auf einem vollen Markt handeln", "ein Orchester dirigieren"],
        "es": ["entrar en la sala equivocada y actuar con normalidad", "dar un discurso sin algunas notas", "orientarse con un mapa roto", "cocinar contrarreloj",
               "interpretar una escena dramática de cine", "enseñar un baile complicado", "regatear en un mercado concurrido", "dirigir una orquesta"],
        "fr": ["entrer dans la mauvaise pièce et faire comme si de rien n'était", "prononcer un discours avec des notes manquantes", "s'orienter avec une carte déchirée", "cuisiner contre la montre",
               "jouer une scène de film dramatique", "enseigner une danse compliquée", "marchander dans un marché bondé", "diriger un orchestre"],
        "pt": ["entrar na sala errada e agir normalmente", "fazer um discurso sem algumas anotações", "orientar-se com um mapa rasgado", "cozinhar contra o relógio",
               "representar uma cena dramática de cinema", "ensinar uma dança complicada", "pechinchar num mercado movimentado", "reger uma orquestra"],
        "ru": ["войти не в ту комнату и вести себя как обычно", "произнести речь без части записей", "искать путь по порванной карте", "готовить наперегонки со временем",
               "сыграть драматическую сцену из фильма", "обучать сложному танцу", "торговаться на шумном рынке", "дирижировать оркестром"],
        "ja": ["間違った部屋に入り平静を装う", "メモの一部をなくしてスピーチする", "破れた地図で道を探す", "時間に追われて料理する",
               "映画の劇的な場面を演じる", "複雑なダンスを教える", "混雑した市場で値段交渉する", "オーケストラを指揮する"],
        "ko": ["엉뚱한 방에 들어가 태연한 척하기", "메모 일부 없이 연설하기", "찢어진 지도로 길 찾기", "시간 안에 요리하기",
               "극적인 영화 장면 연기하기", "복잡한 춤 가르치기", "붐비는 시장에서 흥정하기", "오케스트라 지휘하기"],
    },
}

CATEGORY = {
    "tr": ("Hareket", "Kültür"), "en": ("Action", "Culture"),
    "de": ("Aktion", "Kultur"), "es": ("Acción", "Cultura"),
    "fr": ("Action", "Culture"), "pt": ("Ação", "Cultura"),
    "ru": ("Действие", "Культура"), "ja": ("アクション", "文化"),
    "ko": ("동작", "문화"),
}
