"""Localized products and market themes for AliKa Colorful Market."""
from __future__ import annotations


CATALOGS = {
    "tr": [("elma", "food"), ("simit", "food"), ("yoğurt", "food"), ("mercimek", "food"),
           ("defter", "school"), ("boya kalemi", "school"), ("matara", "daily"),
           ("sabun", "daily"), ("fidan", "nature"), ("bez çanta", "nature"),
           ("top", "play"), ("yapboz", "play")],
    "en": [("apple", "food"), ("bread", "food"), ("oats", "food"), ("yogurt", "food"),
           ("notebook", "school"), ("colored pencils", "school"), ("water bottle", "daily"),
           ("soap", "daily"), ("seedling", "nature"), ("reusable bag", "nature"),
           ("ball", "play"), ("puzzle", "play")],
    "de": [("Apfel", "food"), ("Brot", "food"), ("Haferflocken", "food"), ("Joghurt", "food"),
           ("Heft", "school"), ("Buntstifte", "school"), ("Trinkflasche", "daily"),
           ("Seife", "daily"), ("Setzling", "nature"), ("Stoffbeutel", "nature"),
           ("Ball", "play"), ("Puzzle", "play")],
    "es": [("manzana", "food"), ("pan", "food"), ("avena", "food"), ("yogur", "food"),
           ("cuaderno", "school"), ("lápices de colores", "school"), ("botella", "daily"),
           ("jabón", "daily"), ("plantón", "nature"), ("bolsa reutilizable", "nature"),
           ("pelota", "play"), ("rompecabezas", "play")],
    "fr": [("pomme", "food"), ("pain", "food"), ("avoine", "food"), ("yaourt", "food"),
           ("cahier", "school"), ("crayons de couleur", "school"), ("gourde", "daily"),
           ("savon", "daily"), ("jeune plante", "nature"), ("sac réutilisable", "nature"),
           ("ballon", "play"), ("puzzle", "play")],
    "pt": [("maçã", "food"), ("pão", "food"), ("aveia", "food"), ("iogurte", "food"),
           ("caderno", "school"), ("lápis de cor", "school"), ("garrafa", "daily"),
           ("sabonete", "daily"), ("muda", "nature"), ("sacola reutilizável", "nature"),
           ("bola", "play"), ("quebra-cabeça", "play")],
    "ru": [("яблоко", "food"), ("хлеб", "food"), ("овсянка", "food"), ("йогурт", "food"),
           ("тетрадь", "school"), ("цветные карандаши", "school"), ("бутылка", "daily"),
           ("мыло", "daily"), ("саженец", "nature"), ("многоразовая сумка", "nature"),
           ("мяч", "play"), ("головоломка", "play")],
    "ja": [("りんご", "food"), ("パン", "food"), ("おにぎり", "food"), ("ヨーグルト", "food"),
           ("ノート", "school"), ("色えんぴつ", "school"), ("水筒", "daily"),
           ("せっけん", "daily"), ("苗木", "nature"), ("風呂敷バッグ", "nature"),
           ("ボール", "play"), ("パズル", "play")],
    "ko": [("사과", "food"), ("빵", "food"), ("쌀", "food"), ("요구르트", "food"),
           ("공책", "school"), ("색연필", "school"), ("물병", "daily"),
           ("비누", "daily"), ("묘목", "nature"), ("재사용 가방", "nature"),
           ("공", "play"), ("퍼즐", "play")],
}

MARKETS = {
    "tr": ["İstanbul mahalle pazarı", "Ege üretici pazarı", "Anadolu dayanışma dükkânı",
           "Karadeniz sahil pazarı", "Kapadokya festival çarşısı"],
    "en": ["neighborhood market", "coastal farmers market", "community shop",
           "highland market hall", "festival bazaar"],
    "de": ["Wochenmarkt", "Küstenmarkt", "Dorfladen", "Alpenmarkthalle", "Festmarkt"],
    "es": ["mercado del barrio", "mercado costero", "tienda comunitaria",
           "mercado andino", "feria de colores"],
    "fr": ["marché du quartier", "marché côtier", "épicerie solidaire",
           "halle alpine", "marché de fête"],
    "pt": ["mercado do bairro", "mercado costeiro", "loja comunitária",
           "mercado serrano", "feira colorida"],
    "ru": ["районный рынок", "прибрежный рынок", "общественная лавка",
           "северная ярмарка", "праздничный базар"],
    "ja": ["商店街の市場", "港の朝市", "みんなの売店", "山の市場", "お祭り広場"],
    "ko": ["동네 시장", "바닷가 장터", "마을 가게", "산골 시장", "축제 장터"],
}
