# -*- coding: utf-8 -*-
"""Faz 7a: Turkce karakter restorasyonu.
ASCII transliterasyonu dogru Turkce karakterlere donusturur.
Sozluk tabanli + kural tabanli yaklasim.
"""
import io, json, os, sys, re
sys.stdout.reconfigure(encoding='utf-8')

ROOT = r'turkiye\5-sinif\turkce'

# Kapsamli Turkce sozluk: ASCII -> Dogru Turkce
# En sik kullanilan egitim sozcukleri
SOZLUK = {
    # Temel sozcukler
    'buyuk': 'büyük', 'kucuk': 'küçük', 'ozel': 'özel', 'genel': 'genel',
    'turkce': 'türkçe', 'turk': 'türk', 'turkiye': 'türkiye',
    'ogrenci': 'öğrenci', 'ogretmen': 'öğretmen', 'okul': 'okul',
    'egitim': 'eğitim', 'ogretim': 'öğretim', 'ogrenme': 'öğrenme',
    'bilgi': 'bilgi', 'bilim': 'bilim', 'bilimsel': 'bilimsel',
    'dil': 'dil', 'dilbilgisi': 'dilbilgisi',
    'cumle': 'cümle', 'cumleler': 'cümleler', 'cumlenin': 'cümlenin',
    'cumleye': 'cümleye', 'cumlede': 'cümlede', 'cumlesi': 'cümlesi',
    'cumlesinde': 'cümlesinde', 'cumlesine': 'cümlesine',
    'sozcuk': 'sözcük', 'sozcukler': 'sözcükler', 'sozcugun': 'sözcüğün',
    'sozcuklerin': 'sözcüklerin', 'sozcugu': 'sözcüğü',
    'kelime': 'kelime', 'kelimeler': 'kelimeler',
    'harf': 'harf', 'harfler': 'harfler', 'harfle': 'harfle',
    'ses': 'ses', 'sesli': 'sesli', 'sessiz': 'sessiz',
    'yazim': 'yazım', 'yazimi': 'yazımı', 'yazimda': 'yazımda',
    'noktalama': 'noktalama', 'nokta': 'nokta', 'noktasi': 'noktası',
    'virgul': 'virgül', 'unlem': 'ünlem', 'soru': 'soru',
    'iki': 'iki', 'nokta': 'nokta', 'kesme': 'kesme', 'tirnak': 'tırnak',
    'isareti': 'işareti', 'isaret': 'işaret', 'isaretleri': 'işaretleri',
    'noktalama': 'noktalama',
    'anlam': 'anlam', 'anlami': 'anlamı', 'anlamina': 'anlamına',
    'anlamli': 'anlamlı', 'anlamsiz': 'anlamsız',
    'metin': 'metin', 'metni': 'metni', 'metinde': 'metinde',
    'metnin': 'metnin', 'metinler': 'metinler',
    'paragraf': 'paragraf', 'paragrafi': 'paragrafı',
    'konu': 'konu', 'konuyu': 'konuyu', 'konuda': 'konuda',
    'tema': 'tema', 'temalari': 'temaları',
    'tur': 'tür', 'turu': 'türü', 'turleri': 'türleri',
    'cesit': 'çeşit', 'cesitli': 'çeşitli',
    'gorev': 'görev', 'gorevi': 'görevi', 'gorevleri': 'görevleri',
    'kural': 'kural', 'kurallari': 'kuralları', 'kurallarina': 'kurallarına',
    'kurali': 'kuralı', 'kurallarinin': 'kurallarının',
    'ornek': 'örnek', 'ornegin': 'örneğin', 'ornekleri': 'örnekleri',
    'ornekler': 'örnekler', 'ornekte': 'örnekte',
    'ozellik': 'özellik', 'ozellikleri': 'özellikleri',
    'ozelligi': 'özelliği', 'ozelliklerini': 'özelliklerini',
    'aciklama': 'açıklama', 'aciklamasi': 'açıklaması',
    'aciklamak': 'açıklamak', 'aciklar': 'açıklar',
    'belirtmek': 'belirtmek', 'belirten': 'belirten',
    'gosteren': 'gösteren', 'gosterir': 'gösterir', 'gostermek': 'göstermek',
    'gosterir': 'gösterir', 'gostergesi': 'göstergesi',
    'kullanilan': 'kullanılan', 'kullanilir': 'kullanılır',
    'kullanilma': 'kullanılma', 'kullanimi': 'kullanımı',
    'kullanildigi': 'kullanıldığı', 'kullanilan': 'kullanılan',
    'bulunan': 'bulunan', 'bulunur': 'bulunur', 'bulunan': 'bulunan',
    'olusturan': 'oluşturan', 'olusturur': 'oluşturur',
    'olusturan': 'oluşturan', 'olusur': 'oluşur',
    'yapilan': 'yapılan', 'yapilir': 'yapılır', 'yapmak': 'yapmak',
    'yazilan': 'yazılan', 'yazilir': 'yazılır', 'yazmak': 'yazmak',
    'yazimi': 'yazımı', 'yazilis': 'yazılış',
    'dogru': 'doğru', 'dogru': 'doğru', 'dogrudur': 'doğrudur',
    'dogru': 'doğru', 'dogruluk': 'doğruluk',
    'yanlis': 'yanlış', 'yanlistir': 'yanlıştır',
    'hata': 'hata', 'hatali': 'hatalı', 'hatasi': 'hatası',
    'dikkat': 'dikkat', 'dikkatli': 'dikkatli',
    'onemli': 'önemli', 'onemi': 'önemi', 'onem': 'önem',
    'gereken': 'gereken', 'gerekir': 'gerekir', 'gerekli': 'gerekli',
    'gerektigi': 'gerektiği', 'gerektirir': 'gerektirir',
    'edilen': 'edilen', 'edilir': 'edilir', 'etmek': 'etmek',
    'eden': 'eden', 'eder': 'eder',
    'olan': 'olan', 'olur': 'olur', 'olmak': 'olmak',
    'olarak': 'olarak', 'oldugu': 'olduğu', 'oldugunu': 'olduğunu',
    'oldugu': 'olduğu', 'olmadigi': 'olmadığı',
    'icin': 'için', 'icinde': 'içinde', 'iceren': 'içeren',
    'icerir': 'içerir', 'icerisinde': 'içerisinde',
    'uzere': 'üzere', 'uzerinde': 'üzerinde', 'uzerine': 'üzerine',
    'uzerinden': 'üzerinden',
    'sonra': 'sonra', 'sonraki': 'sonraki', 'sonunda': 'sonunda',
    'once': 'önce', 'onceki': 'önceki', 'oncelikle': 'öncelikle',
    'ilk': 'ilk', 'son': 'son', 'ara': 'ara',
    'basinda': 'başında', 'sonunda': 'sonunda', 'ortasinda': 'ortasında',
    'baslar': 'başlar', 'baslayan': 'başlayan', 'baslangic': 'başlangıç',
    'biten': 'biten', 'biter': 'biter', 'bitis': 'bitiş',
    'ayni': 'aynı', 'ayri': 'ayrı', 'ayrica': 'ayrıca',
    'baska': 'başka', 'baskasi': 'başkası',
    'her': 'her', 'hic': 'hiç', 'hicbir': 'hiçbir',
    'bir': 'bir', 'birbirine': 'birbirine', 'birbirinden': 'birbirinden',
    'cok': 'çok', 'cokluk': 'çokluk', 'cogul': 'çoğul',
    'az': 'az', 'daha': 'daha', 'en': 'en',
    'tum': 'tüm', 'butun': 'bütün', 'hepsi': 'hepsi',
    'kisim': 'kısım', 'bolum': 'bölüm', 'bolumu': 'bölümü',
    'bolumleri': 'bölümleri', 'bolumleri': 'bölümleri',
    'yapi': 'yapı', 'yapisi': 'yapısı', 'yapilar': 'yapılar',
    'yapisal': 'yapısal',
    'biyim': 'biyim', 'deyim': 'deyim', 'deyimler': 'deyimler',
    'atasozu': 'atasözü', 'atasozleri': 'atasözleri',
    'soz': 'söz', 'sozu': 'sözü', 'sozleri': 'sözleri',
    'sozcuk': 'sözcük', 'sozcukleri': 'sözcükleri',
    'sanat': 'sanat', 'sanatlari': 'sanatları', 'sanatsal': 'sanatsal',
    'edebi': 'edebi', 'edebiyat': 'edebiyat', 'edebiyati': 'edebiyatı',
    'yazar': 'yazar', 'yazari': 'yazarı', 'sair': 'şair',
    'siir': 'şiir', 'siiri': 'şiiri', 'siirde': 'şiirde',
    'hikaye': 'hikaye', 'hikayesi': 'hikayesi', 'masal': 'masal',
    'roman': 'roman', 'makale': 'makale', 'deneme': 'deneme',
    'haber': 'haber', 'haberi': 'haberi',
    'gezi': 'gezi', 'yazisi': 'yazısı',
    'betimleme': 'betimleme', 'betimleyici': 'betimleyici',
    'oykuleyici': 'öyküleyici', 'bilgilendirici': 'bilgilendirici',
    'tartismaci': 'tartışmacı', 'aciklayici': 'açıklayıcı',
    'anlatim': 'anlatım', 'anlatimi': 'anlatımı',
    'anlatici': 'anlatıcı', 'anlatan': 'anlatan',
    'kisiler': 'kişiler', 'kisi': 'kişi', 'kahraman': 'kahraman',
    'olay': 'olay', 'olayi': 'olayı', 'olaylar': 'olaylar',
    'yer': 'yer', 'zaman': 'zaman', 'mekan': 'mekan',
    'duygu': 'duygu', 'dusunce': 'düşünce', 'dusuncelerini': 'düşüncelerini',
    'dusuncesi': 'düşüncesi', 'dusunmek': 'düşünmek',
    'dusun': 'düşün', 'dusunduren': 'düşündüren',
    'hayal': 'hayal', 'gercek': 'gerçek', 'gercekci': 'gerçekçi',
    'gercegi': 'gerçeği', 'gercekte': 'gerçekte',
    'dogal': 'doğal', 'doga': 'doğa',
    'toplum': 'toplum', 'toplumsal': 'toplumsal',
    'kulturel': 'kültürel', 'kultur': 'kültür', 'kulturu': 'kültürü',
    'gelenek': 'gelenek', 'gorenek': 'görenek',
    'milli': 'milli', 'ulusal': 'ulusal',
    'dil': 'dil', 'dili': 'dili', 'dilin': 'dilin',
    'ifade': 'ifade', 'ifadeler': 'ifadeler', 'ifadesi': 'ifadesi',
    'anlatir': 'anlatır', 'anlatmak': 'anlatmak',
    'belirtir': 'belirtir', 'belirtilen': 'belirtilen',
    'verir': 'verir', 'verilen': 'verilen', 'vermek': 'vermek',
    'alir': 'alır', 'alinarak': 'alınarak', 'alinir': 'alınır',
    'gelir': 'gelir', 'gelen': 'gelen', 'gelmek': 'gelmek',
    'olur': 'olur', 'olan': 'olan', 'olmak': 'olmak',
    'der': 'der', 'dedi': 'dedi', 'demek': 'demek',
    'gibi': 'gibi', 'gore': 'göre', 'gorev': 'görev',
    'karsi': 'karşı', 'karsin': 'karşın', 'karsilik': 'karşılık',
    'ilgili': 'ilgili', 'iliski': 'ilişki', 'iliskisi': 'ilişkisi',
    'bagli': 'bağlı', 'baglam': 'bağlam', 'baglanti': 'bağlantı',
    'iliskin': 'ilişkin', 'iliskili': 'ilişkili',
    'neden': 'neden', 'nedeni': 'nedeni', 'nedeniyle': 'nedeniyle',
    'sonuc': 'sonuç', 'sonucu': 'sonucu', 'sonuclari': 'sonuçları',
    'sebep': 'sebep', 'sebebi': 'sebebi',
    'ama': 'ama', 'ancak': 'ancak', 'fakat': 'fakat',
    'cunku': 'çünkü', 'bu': 'bu', 'su': 'şu',
    'o': 'o', 'bu': 'bu', 'bunlar': 'bunlar',
    'hangisi': 'hangisi', 'hangi': 'hangi', 'nasil': 'nasıl',
    'neden': 'neden', 'nicin': 'niçin', 'kim': 'kim',
    'ne': 'ne', 'nerede': 'nerede', 'ne': 'ne',
    'var': 'var', 'yok': 'yok', 'var': 'var',
    'degil': 'değil', 'degildir': 'değildir', 'degildir': 'değildir',
    'midir': 'midir', 'mudur': 'mudur',
    've': 've', 'ile': 'ile', 'veya': 'veya', 'ya': 'ya',
    'da': 'da', 'de': 'de', 'ki': 'ki',
    'bir': 'bir', 'bir': 'bir',
    'secenegi': 'seçeneği', 'secenek': 'seçenek', 'secenekleri': 'seçenekleri',
    'secenegin': 'seçeneğin', 'secenekte': 'seçenekte',
    'sik': 'şık', 'sikki': 'şıkkı', 'siklar': 'şıklar',
    'cevap': 'cevap', 'cevabi': 'cevabı', 'cevabi': 'cevabı',
    'yanit': 'yanıt', 'yaniti': 'yanıtı',
    'dogru': 'doğru', 'yanlis': 'yanlış',
    'ipucu': 'ipucu', 'ipuclari': 'ipuçları',
    'dusun': 'düşün', 'dusunun': 'düşünün',
    'hatirla': 'hatırla', 'hatirlayin': 'hatırlayın',
    'incele': 'incele', 'inceleyin': 'inceleyin',
    'belirle': 'belirle', 'belirleyin': 'belirleyin',
    'bul': 'bul', 'bulun': 'bulun', 'bulma': 'bulma',
    'sec': 'seç', 'secin': 'seçin', 'secme': 'seçme',
    'eslestir': 'eşleştir', 'eslestirme': 'eşleştirme',
    'karsilastir': 'karşılaştır', 'karsilastirma': 'karşılaştırma',
    'sinifla': 'sınıfla', 'siniflandirma': 'sınıflandırma',
    'ozetle': 'özetle', 'ozet': 'özet', 'ozeti': 'özeti',
    'kisaca': 'kısaca', 'kisa': 'kısa', 'uzun': 'uzun',
    'genis': 'geniş', 'dar': 'dar', 'derin': 'derin',
    'yuksek': 'yüksek', 'alçak': 'alçak',
    'hizli': 'hızlı', 'yavas': 'yavaş',
    'kolay': 'kolay', 'zor': 'zor', 'guc': 'güç',
    'iyi': 'iyi', 'kotu': 'kötü', 'guzel': 'güzel',
    'cirkin': 'çirkin', 'temiz': 'temiz', 'kirli': 'kirli',
    'yeni': 'yeni', 'eski': 'eski', 'genç': 'genç',
    'sicak': 'sıcak', 'soguk': 'soğuk', 'ilik': 'ılık',
    'agir': 'ağır', 'hafif': 'hafif',
    'sert': 'sert', 'yumusak': 'yumuşak',
    'kalin': 'kalın', 'ince': 'ince',
    'genis': 'geniş', 'dar': 'dar',
    'uzak': 'uzak', 'yakin': 'yakın',
    'acik': 'açık', 'kapali': 'kapalı',
    'bos': 'boş', 'dolu': 'dolu',
    'kuru': 'kuru', 'islak': 'ıslak',
    'aydinlik': 'aydınlık', 'karanlik': 'karanlık',
    'sessiz': 'sessiz', 'gurultulu': 'gürültülü',
    'guclu': 'güçlü', 'zayif': 'zayıf',
    'zengin': 'zengin', 'fakir': 'fakir',
    'mutlu': 'mutlu', 'uzgun': 'üzgün', 'kizgin': 'kızgın',
    'korku': 'korku', 'sevinc': 'sevinç', 'sasirma': 'şaşırma',
    'ofke': 'öfke', 'nefret': 'nefret', 'sevgi': 'sevgi',
    'saygi': 'saygı', 'sevgi': 'sevgi', 'dostluk': 'dostluk',
    'arkadas': 'arkadaş', 'arkadaslik': 'arkadaşlık',
    'aile': 'aile', 'anne': 'anne', 'baba': 'baba',
    'kardes': 'kardeş', 'abi': 'abi', 'abla': 'abla',
    'cocuk': 'çocuk', 'cocuklar': 'çocuklar', 'cocugun': 'çocuğun',
    'genclik': 'gençlik', 'gencleri': 'gençleri',
    'insan': 'insan', 'insanlar': 'insanlar', 'insanlarin': 'insanların',
    'toplum': 'toplum', 'toplumun': 'toplumun',
    'devlet': 'devlet', 'devletin': 'devletin',
    'ulke': 'ülke', 'ulkenin': 'ülkenin', 'ulkeler': 'ülkeler',
    'sehir': 'şehir', 'sehri': 'şehri', 'kasaba': 'kasaba',
    'koy': 'köy', 'mahalle': 'mahalle',
    'ev': 'ev', 'evi': 'evi', 'evde': 'evde',
    'oda': 'oda', 'odasi': 'odası', 'mutfak': 'mutfak',
    'bahce': 'bahçe', 'bahcesi': 'bahçesi',
    'yol': 'yol', 'yolu': 'yolu', 'yolda': 'yolda',
    'araba': 'araba', 'otobus': 'otobüs', 'tren': 'tren',
    'deniz': 'deniz', 'dag': 'dağ', 'orman': 'orman',
    'nehir': 'nehir', 'gol': 'göl', 'ova': 'ova',
    'gunes': 'güneş', 'ay': 'ay', 'yildiz': 'yıldız',
    'gokyuzu': 'gökyüzü', 'bulut': 'bulut', 'yagmur': 'yağmur',
    'kar': 'kar', 'ruzgar': 'rüzgar', 'firtina': 'fırtına',
    'hava': 'hava', 'havasi': 'havası', 'havada': 'havada',
    'su': 'su', 'suyu': 'suyu', 'suda': 'suda',
    'ates': 'ateş', 'atesi': 'ateşi',
    'toprak': 'toprak', 'topragi': 'toprağı',
    'tas': 'taş', 'kaya': 'kaya', 'kum': 'kum',
    'bitki': 'bitki', 'bitkiler': 'bitkiler', 'cicek': 'çiçek',
    'agac': 'ağaç', 'agaclari': 'ağaçları', 'yaprak': 'yaprak',
    'hayvan': 'hayvan', 'hayvanlar': 'hayvanlar', 'kus': 'kuş',
    'balik': 'balık', 'kedi': 'kedi', 'kopek': 'köpek',
    'at': 'at', 'inek': 'inek', 'koyun': 'koyun',
    'tavuk': 'tavuk', 'horoz': 'horoz',
    'yiyecek': 'yiyecek', 'icecek': 'içecek', 'yemek': 'yemek',
    'ekmek': 'ekmek', 'sut': 'süt', 'su': 'su',
    'meyve': 'meyve', 'sebze': 'sebze', 'elma': 'elma',
    'armut': 'armut', 'uzum': 'üzüm', 'kiraz': 'kiraz',
    'portakal': 'portakal', 'limon': 'limon', 'muz': 'muz',
    'domates': 'domates', 'salatalik': 'salatalık', 'biber': 'biber',
    'sogan': 'soğan', 'sarımsak': 'sarımsak',
    'gun': 'gün', 'gunu': 'günü', 'gunde': 'günde',
    'hafta': 'hafta', 'ay': 'ay', 'yil': 'yıl',
    'mevsim': 'mevsim', 'mevsimler': 'mevsimler',
    'ilkbahar': 'ilkbahar', 'yaz': 'yaz', 'sonbahar': 'sonbahar', 'kis': 'kış',
    'sabah': 'sabah', 'ogle': 'öğle', 'aksam': 'akşam', 'gece': 'gece',
    'bugun': 'bugün', 'dun': 'dün', 'yarin': 'yarın',
    'simdi': 'şimdi', 'hemen': 'hemen', 'sonra': 'sonra',
    'once': 'önce', 'gecmis': 'geçmiş', 'gelecek': 'gelecek',
    'zaman': 'zaman', 'zamani': 'zamanı', 'zamanda': 'zamanda',
    'saat': 'saat', 'dakika': 'dakika', 'saniye': 'saniye',
    'sayi': 'sayı', 'sayisi': 'sayısı', 'sayilar': 'sayılar',
    'sayisal': 'sayısal', 'sayisal': 'sayısal',
    'islem': 'işlem', 'islemi': 'işlemi', 'islemler': 'işlemler',
    'toplama': 'toplama', 'cikarma': 'çıkarma', 'carpma': 'çarpma',
    'bolme': 'bölme', 'bolu': 'bölü',
    'esit': 'eşit', 'esittir': 'eşittir', 'esitlik': 'eşitlik',
    'fazla': 'fazla', 'eksik': 'eksik', 'artik': 'artık',
    'yuzde': 'yüzde', 'oran': 'oran', 'orani': 'oranı',
    'olcu': 'ölçü', 'olcusu': 'ölçüsü', 'olcmek': 'ölçmek',
    'uzunluk': 'uzunluk', 'genislik': 'genişlik', 'yukseklik': 'yükseklik',
    'agirlik': 'ağırlık', 'hacim': 'hacim', 'alan': 'alan',
    'cevre': 'çevre', 'cevresi': 'çevresi', 'cevresinde': 'çevresinde',
    'sekil': 'şekil', 'sekli': 'şekli', 'sekilde': 'şekilde',
    'daire': 'daire', 'kare': 'kare', 'ucgen': 'üçgen',
    'dikdortgen': 'dikdörtgen', 'cember': 'çember',
    'kose': 'köşe', 'kosesi': 'köşesi', 'kenar': 'kenar',
    'acisi': 'açısı', 'aci': 'açı', 'dik': 'dik',
    'cizgi': 'çizgi', 'cizgisi': 'çizgisi', 'nokta': 'nokta',
    'dogru': 'doğru', 'egri': 'eğri', 'duz': 'düz',
    'yatay': 'yatay', 'dikey': 'dikey', 'paralel': 'paralel',
    'simetri': 'simetri', 'simetrik': 'simetrik',
    'yansima': 'yansıma', 'donme': 'dönme', 'oteleme': 'öteleme',
    'veri': 'veri', 'verileri': 'verileri', 'veriler': 'veriler',
    'grafik': 'grafik', 'grafiği': 'grafiği', 'tablo': 'tablo',
    'istatistik': 'istatistik', 'olasilik': 'olasılık',
    'kesir': 'kesir', 'kesirler': 'kesirler', 'kesri': 'kesri',
    'pay': 'pay', 'payda': 'payda', 'paydasi': 'paydası',
    'bilesik': 'bileşik', 'basit': 'basit', 'tam': 'tam',
    'ondalik': 'ondalık', 'yuzde': 'yüzde',
    'oran': 'oran', 'oranti': 'orantı',
    'denklem': 'denklem', 'esitsizlik': 'eşitsizlik',
    'degisken': 'değişken', 'bilinmeyen': 'bilinmeyen',
    'cozum': 'çözüm', 'cozumu': 'çözümü', 'cozmek': 'çözmek',
    'sonuc': 'sonuç', 'sonucu': 'sonucu',
    'adim': 'adım', 'adimi': 'adımı', 'adimlari': 'adımları',
    'yontem': 'yöntem', 'yontemi': 'yöntemi',
    'strateji': 'strateji', 'stratejileri': 'stratejileri',
    'problem': 'problem', 'problemi': 'problemi',
    'soru': 'soru', 'soruyu': 'soruyu', 'soruda': 'soruda',
    'sorunun': 'sorunun', 'sorular': 'sorular',
    'cevap': 'cevap', 'cevabi': 'cevabı', 'cevaplari': 'cevapları',
    'secenek': 'seçenek', 'secenekleri': 'seçenekleri',
    'sik': 'şık', 'sikki': 'şıkkı',
    'test': 'test', 'sinav': 'sınav', 'sinavi': 'sınavı',
    'not': 'not', 'notu': 'notu', 'notlari': 'notları',
    'ders': 'ders', 'dersi': 'dersi', 'derste': 'derste',
    'konu': 'konu', 'konuyu': 'konuyu', 'konuda': 'konuda',
    'unit': 'ünite', 'unite': 'ünite', 'unitesi': 'ünitesi',
    'bolum': 'bölüm', 'bolumu': 'bölümü',
    'bolumleri': 'bölümleri',
    'konu': 'konu', 'konular': 'konular',
    'kazanim': 'kazanım', 'kazanımları': 'kazanımları',
    'hedef': 'hedef', 'hedefi': 'hedefi',
    'amac': 'amaç', 'amaci': 'amacı', 'amaclari': 'amaçları',
    'yontem': 'yöntem', 'yontemi': 'yöntemi',
    'teknik': 'teknik', 'teknigi': 'tekniği',
    'beceri': 'beceri', 'becerileri': 'becerileri',
    'yetkinlik': 'yetkinlik', 'yeterlilik': 'yeterlilik',
    'düzey': 'düzey', 'duzey': 'düzey', 'duzeyi': 'düzeyi',
    'seviye': 'seviye', 'seviyesi': 'seviyesi',
    'kolay': 'kolay', 'orta': 'orta', 'zor': 'zor',
    'temel': 'temel', 'ileri': 'ileri', 'giris': 'giriş',
    'gelisme': 'gelisme', 'gelisme': 'gelişme',
    'sonuc': 'sonuç', 'degerlendirme': 'değerlendirme',
    'olcme': 'ölçme', 'olcmek': 'ölçmek',
    'analiz': 'analiz', 'sentez': 'sentez',
    'uygulama': 'uygulama', 'anlama': 'anlama',
    'bilgi': 'bilgi', 'kavrama': 'kavrama',
    'kavram': 'kavram', 'kavrami': 'kavramı',
    'kavramlar': 'kavramlar', 'kavramlari': 'kavramları',
    'tanim': 'tanım', 'tanimi': 'tanımı', 'tanimlamak': 'tanımlamak',
    'aciklama': 'açıklama', 'aciklamasi': 'açıklaması',
    'yorum': 'yorum', 'yorumu': 'yorumu', 'yorumlama': 'yorumlama',
    'cikarim': 'çıkarım', 'cikarim': 'çıkarım',
    'genelleme': 'genelleme', 'genellemek': 'genellemek',
    'ozelleme': 'özelleme', 'ozel': 'özel',
    'siniflama': 'sınıflama', 'siniflandirma': 'sınıflandırma',
    'karsilastirma': 'karşılaştırma', 'karsilastir': 'karşılaştır',
    'iliski': 'ilişki', 'iliskisi': 'ilişkisi',
    'neden': 'neden', 'sonuc': 'sonuç',
    'sebep': 'sebep', 'etki': 'etki', 'etkisi': 'etkisi',
    'degisim': 'değişim', 'degisiklik': 'değişiklik',
    'surec': 'süreç', 'sureci': 'süreci',
    'asama': 'aşama', 'asamalari': 'aşamaları',
    'adim': 'adım', 'adimlari': 'adımları',
    'sira': 'sıra', 'sirasi': 'sırası', 'siralama': 'sıralama',
    'duzen': 'düzen', 'duzeni': 'düzeni', 'duzenli': 'düzenli',
    'sistem': 'sistem', 'sistemi': 'sistemi',
    'yapi': 'yapı', 'yapisi': 'yapısı',
    'bolum': 'bölüm', 'parca': 'parça', 'parcasi': 'parçası',
    'butun': 'bütün', 'butunu': 'bütünü',
    'kisim': 'kısım', 'kismi': 'kısmı',
    'oge': 'öğe', 'ogeleri': 'ögeleri', 'oge': 'öğe',
    'unsur': 'unsur', 'unsurlari': 'unsurları',
    'fark': 'fark', 'farki': 'farkı', 'farkli': 'farklı',
    'benzer': 'benzer', 'benzerlik': 'benzerlik',
    'ortak': 'ortak', 'ortak': 'ortak',
    'zıt': 'zıt', 'zit': 'zıt', 'karsit': 'karşıt',
    'olumlu': 'olumlu', 'olumsuz': 'olumsuz',
    'pozitif': 'pozitif', 'negatif': 'negatif',
    'dogru': 'doğru', 'yanlis': 'yanlış',
    'gecerli': 'geçerli', 'gecersiz': 'geçersiz',
    'uygun': 'uygun', 'uygun': 'uygun',
    'gerekli': 'gerekli', 'gereksiz': 'gereksiz',
    'zorunlu': 'zorunlu', 'secmeli': 'seçmeli',
    'serbest': 'serbest', 'sinirli': 'sınırlı',
    'sinirsiz': 'sınırsız', 'belirli': 'belirli',
    'belirsiz': 'belirsiz', 'kesin': 'kesin',
    'supheli': 'şüpheli', 'guvenli': 'güvenli',
    'tehlikeli': 'tehlikeli', 'zararli': 'zararlı',
    'faydali': 'faydalı', 'yararli': 'yararlı',
    'etkili': 'etkili', 'etkisiz': 'etkisiz',
    'verimli': 'verimli', 'verimsiz': 'verimsiz',
    'basarili': 'başarılı', 'basarisiz': 'başarısız',
    'basari': 'başarı', 'basarisi': 'başarısı',
    'calisma': 'çalışma', 'calismasi': 'çalışması',
    'calismak': 'çalışmak', 'calisir': 'çalışır',
    'uretim': 'üretim', 'uretimi': 'üretimi',
    'tuketim': 'tüketim', 'tuketimi': 'tüketimi',
    'dagitim': 'dağıtım', 'dagitimi': 'dağıtımı',
    'ekonomi': 'ekonomi', 'ekonomik': 'ekonomik',
    'ticaret': 'ticaret', 'ticari': 'ticari',
    'para': 'para', 'parasi': 'parası',
    'fiyat': 'fiyat', 'fiyati': 'fiyatı',
    'mal': 'mal', 'hizmet': 'hizmet',
    'is': 'iş', 'isi': 'işi', 'iste': 'işte',
    'meslek': 'meslek', 'meslegi': 'mesleği',
    'calisan': 'çalışan', 'isci': 'işçi', 'memur': 'memur',
    'yonetici': 'yönetici', 'mudur': 'müdür',
    'baskan': 'başkan', 'baskani': 'başkanı',
    'uye': 'üye', 'uyesi': 'üyesi', 'uyelik': 'üyelik',
    'grup': 'grup', 'grubu': 'grubu',
    'takim': 'takım', 'takimi': 'takımı',
    'ekip': 'ekip', 'ekibi': 'ekibi',
    'toplanti': 'toplantı', 'toplantisi': 'toplantısı',
    'karar': 'karar', 'karari': 'kararı',
    'oy': 'oy', 'oyu': 'oyu', 'oylama': 'oylama',
    'secim': 'seçim', 'secimi': 'seçimi',
    'hukuk': 'hukuk', 'hukuki': 'hukuki',
    'yasa': 'yasa', 'yasasi': 'yasası',
    'kanun': 'kanun', 'kanunu': 'kanunu',
    'anayasa': 'anayasa', 'anayasasi': 'anayasası',
    'hak': 'hak', 'hakki': 'hakkı', 'haklari': 'hakları',
    'ozgurluk': 'özgürlük', 'ozgurlugu': 'özgürlüğü',
    'esitlik': 'eşitlik', 'esit': 'eşit',
    'adalet': 'adalet', 'adil': 'adil',
    'demokrasi': 'demokrasi', 'demokratik': 'demokratik',
    'cumhuriyet': 'cumhuriyet', 'cumhuriyeti': 'cumhuriyeti',
    'meclis': 'meclis', 'meclisi': 'meclisi',
    'bakan': 'bakan', 'bakanlik': 'bakanlık',
    'vali': 'vali', 'valilik': 'valilik',
    'belediye': 'belediye', 'belediyesi': 'belediyesi',
    'muhtar': 'muhtar', 'muhtarlik': 'muhtarlık',
    'polis': 'polis', 'jandarma': 'jandarma',
    'asker': 'asker', 'ordu': 'ordu',
    'guvenlik': 'güvenlik', 'guvenligi': 'güvenliği',
    'saglik': 'sağlık', 'sagligi': 'sağlığı',
    'hastane': 'hastane', 'doktor': 'doktor',
    'ilac': 'ilaç', 'tedavi': 'tedavi',
    'hastalik': 'hastalık', 'hastaligi': 'hastalığı',
    'temizlik': 'temizlik', 'temiz': 'temiz',
    'cevre': 'çevre', 'cevresi': 'çevresi',
    'doga': 'doğa', 'dogasi': 'doğası',
    'hayvan': 'hayvan', 'bitki': 'bitki',
    'ekosistem': 'ekosistem', 'yasam': 'yaşam',
    'yasami': 'yaşamı', 'yasam': 'yaşam',
    'enerji': 'enerji', 'enerjisi': 'enerjisi',
    'elektrik': 'elektrik', 'elektrigi': 'elektriği',
    'isik': 'ışık', 'isigi': 'ışığı',
    'ses': 'ses', 'sesi': 'sesi',
    'kuvvet': 'kuvvet', 'kuvveti': 'kuvveti',
    'hareket': 'hareket', 'hareketi': 'hareketi',
    'hiz': 'hız', 'hizi': 'hızı',
    'yogunluk': 'yoğunluk', 'yogunlugu': 'yoğunluğu',
    'sicaklik': 'sıcaklık', 'sicakligi': 'sıcaklığı',
    'basinc': 'basınç', 'basinci': 'basıncı',
    'madde': 'madde', 'maddesi': 'maddesi',
    'maddenin': 'maddenin', 'maddeler': 'maddeler',
    'hal': 'hal', 'hali': 'hali', 'halleri': 'halleri',
    'kati': 'katı', 'sivi': 'sıvı', 'gaz': 'gaz',
    'erime': 'erime', 'donma': 'donma',
    'buharlasma': 'buharlaşma', 'yogusma': 'yoğuşma',
    'cozunme': 'çözünme', 'cozelti': 'çözelti',
    'karisim': 'karışım', 'karisimi': 'karışımı',
    'bilesik': 'bileşik', 'bilesigi': 'bileşiği',
    'element': 'element', 'atom': 'atom',
    'molekul': 'molekül', 'molekulu': 'molekülü',
    'hucre': 'hücre', 'hucreyi': 'hücreyi',
    'doku': 'doku', 'organ': 'organ',
    'sistem': 'sistem', 'sistemi': 'sistemi',
    'canli': 'canlı', 'canlilar': 'canlılar',
    'canlilari': 'canlıları', 'canlilarin': 'canlıların',
    'yasam': 'yaşam', 'yasami': 'yaşamı',
    'olaganustu': 'olağanüstü', 'olagan': 'olağan',
    'evrensel': 'evrensel', 'yerel': 'yerel',
    'uluslararasi': 'uluslararası', 'ulusal': 'ulusal',
    'kuresel': 'küresel', 'bolgesel': 'bölgesel',
    'bolge': 'bölge', 'bolgesi': 'bölgesi',
    'bolgeleri': 'bölgeleri', 'bolgelerin': 'bölgelerin',
    'iklim': 'iklim', 'iklimi': 'iklimi',
    'bitki': 'bitki', 'ortusu': 'örtüsü',
    'nufus': 'nüfus', 'nufusu': 'nüfusu',
    'yerlesme': 'yerleşme', 'yerlesim': 'yerleşim',
    'goc': 'göç', 'gocu': 'göçü',
    'ulasim': 'ulaşım', 'ulasimi': 'ulaşımı',
    'iletisim': 'iletişim', 'iletisimi': 'iletişimi',
    'teknoloji': 'teknoloji', 'teknolojisi': 'teknolojisi',
    'bilim': 'bilim', 'bilimi': 'bilimi',
    'arastirma': 'araştırma', 'arastirmasi': 'araştırması',
    'gelisme': 'gelişme', 'gelismesi': 'gelişmesi',
    'bulus': 'buluş', 'bulusu': 'buluşu',
    'kesif': 'keşif', 'kesfi': 'keşfi',
    'icat': 'icat', 'icadi': 'icadı',
    'muhendis': 'mühendis', 'muhendislik': 'mühendislik',
    'tasarim': 'tasarım', 'tasarimi': 'tasarımı',
    'proje': 'proje', 'projeyi': 'projeyi',
    'deney': 'deney', 'deneyi': 'deneyi',
    'gozlem': 'gözlem', 'gozlemi': 'gözlemi',
    'olcum': 'ölçüm', 'olcumu': 'ölçümü',
    'veri': 'veri', 'verileri': 'verileri',
    'sonuc': 'sonuç', 'sonuclari': 'sonuçları',
    'hipotez': 'hipotez', 'teori': 'teori',
    'yasa': 'yasa', 'ilke': 'ilke',
    'prensip': 'prensip', 'kural': 'kural',
}

def restore_turkish(text):
    """Metindeki ASCII Turkce sozcukleri dogru karakterlere donusturur."""
    if not text:
        return text
    
    # Sozcuk bazli degistirme (buyuk-kucuk harf duyarliligi ile)
    def replace_word(match):
        word = match.group(0)
        lower = word.lower()
        if lower in SOZLUK:
            replacement = SOZLUK[lower]
            # Buyuk harf koruma
            if word[0].isupper():
                replacement = replacement[0].upper() + replacement[1:]
            if word.isupper():
                replacement = replacement.upper()
            return replacement
        return word
    
    # Sozcuk sinirlarini koruyarak degistir
    result = re.sub(r'[a-zA-Z\u00c0-\u024f]+', replace_word, text)
    return result

def process_file(fpath):
    lines = [l for l in io.open(fpath, encoding='utf-8').read().split('\n') if l.strip()]
    out = []
    changes = 0
    
    for line in lines:
        obj = json.loads(line)
        original = json.dumps(obj, ensure_ascii=False)
        
        # Tum metin alanlarini isle
        for field in ('question', 'explanation', 'title', 'body', 'topic'):
            if field in obj and isinstance(obj[field], str):
                obj[field] = restore_turkish(obj[field])
        
        for field in ('choices', 'hints', 'distractorWhy'):
            if field in obj and isinstance(obj[field], list):
                obj[field] = [restore_turkish(x) if isinstance(x, str) else x for x in obj[field]]
        
        new = json.dumps(obj, ensure_ascii=False)
        if new != original:
            changes += 1
        out.append(obj)
    
    with io.open(fpath, 'w', encoding='utf-8') as f:
        for obj in out:
            f.write(json.dumps(obj, ensure_ascii=False) + '\n')
    
    return changes

# Ana calisma
files = []
for dirpath, _, filenames in os.walk(ROOT):
    for fn in sorted(filenames):
        if fn.endswith('.jsonl'):
            files.append(os.path.join(dirpath, fn))

print(f"Islenecek Turkce dosyasi: {len(files)}")
total_changes = 0
for fpath in files:
    n = process_file(fpath)
    total_changes += n
    print(f"  {os.path.basename(fpath)}: {n} satir degisti")

print(f"\nToplam: {total_changes} satir degisti")

# Dogrulama: Turkce karakter orani
tr_pat = re.compile(r'[\u011f\u0130\u0131\u015f\u00e7\u00f6\u00fc\u011e\u015e\u00c7\u00d6\u00dc]')
for fpath in files:
    lines = [l for l in io.open(fpath, encoding='utf-8').read().split('\n') if l.strip()]
    q_total = 0; q_tr = 0
    for l in lines:
        o = json.loads(l)
        if o.get('type') == 'question':
            q_total += 1
            txt = o.get('question','') + ' '.join(o.get('choices',[])) + o.get('explanation','')
            if tr_pat.search(txt):
                q_tr += 1
    print(f"  {os.path.basename(fpath)}: {q_tr}/{q_total} soru Turkce karakterli")
