# -*- coding: utf-8 -*-
"""A3 parti 8 — MAT.5.1.4 ve MAT.5.6.2 ailelerinin yeniden üretimi.

Kural 39'un en büyük tek ihlali bu iki ailedeydi: 'karşılaştırılamaz' ile
'Karşılaştırılamaz' toplam 10 kez çeldirici olarak geçip hiçbirinde doğru
olmuyordu. Ayrıca ikisi de kapalı havuzdu — 5.1.4'te ['büyüktür','eşittir',
'karşılaştırılamaz','küçüktür'] kümesi 5 kez, 5-6-2'de ['A torbası',
'B torbası','Karşılaştırılamaz','İki torbada eşit'] kümesi 5 kez birebir
tekrarlanıyordu.

Sebep yine beş kalıbın beşer kez tekrarı. Yeni sürümlerde her iki ailede de
notun anlattığı bütün alt konular kapsandı ve "karşılaştırılamaz" seçeneği
yalnız gerçekten karşılaştırma yapılamayan durumlarda — ve orada doğru cevap
olarak — kullanıldı.

choices + correct + distractorWhy + hints + explanation tek birimde üretildi
(AUTHORING_RULES.md §1 atomiklik ilkesi).
"""

KAYNAK = "https://tymm.meb.gov.tr/upload/program/2024programmat5678Onayli.pdf"


def S(level, question, choices, correct, why, exp, dr, hints):
    return dict(level=level, question=question, choices=choices, correct=correct,
                distractorWhy=why, explanation=exp, difficultyReason=dr, hints=hints)


# ---------------------------------------------------------------------------
# MAT.5.1.4 — kesirleri karşılaştırma
# ---------------------------------------------------------------------------

N1 = "tr.g05.mat.5.1.4.note.01"   # paydaları veya payları eşit kesirler
N2 = "tr.g05.mat.5.1.4.note.02"   # farklı pay ve paydalı kesirler
N3 = "tr.g05.mat.5.1.4.note.03"   # gösterimler arası karşılaştırma

A14 = [
    (N1, S(1, "Eş büyüklükteki dört parkurun sırasıyla 2/9, 5/9, 7/9 ve 4/9'luk kısımları tamamlanmıştır. En çok tamamlanan parkur hangisidir?",
           ["2/9", "5/9", "7/9", "4/9"], 2,
           ["Payı en küçük olan kesirdir; en az tamamlanan parkuru gösterir.",
            "Payı 5'tir; 7 payından küçük olduğu için daha az tamamlanmıştır.",
            "doğru",
            "Payı 4'tür; listedeki en büyük pay bu değildir."],
           "Paydalar eşit olduğunda bütünler aynı sayıda eş parçaya ayrılmıştır, yani parçalar aynı "
           "büyüktedir. Bu durumda payı büyük olan kesir büyüktür; 7/9 en büyüğüdür.",
           "1 adım; ön bilgi: paydaları eşit kesirlerde payın belirleyici olması; çeldiriciler yakın (aynı paydalı kesirler); beceri: karşılaştırma",
           ["Kesirlerin paydalarına bak; eşit mi?",
            "Paydalar eşitse parçaların büyüklüğü hakkında ne söylenir?",
            "Alınan parça sayısını hangi sayı gösterir?",
            "Payları büyükten küçüğe sırala.",
            "Tam çözüm: paydalar eşit olduğundan payı en büyük olan kesir en büyüktür; 7/9 seçilir."])),
    (N1, S(2, "Eş büyüklükteki dört pizzadan sırasıyla 2/3, 2/5, 2/7 ve 2/9'luk parçalar ayrılmıştır. En büyük parça hangisidir?",
           ["2/9", "2/7", "2/5", "2/3"], 3,
           ["Paydası en büyük olduğu için parçaları en küçüktür.",
            "Paydası 7'dir; 3 paydasından büyük olduğu için parçaları daha küçüktür.",
            "Paydası 5'tir; listedeki en küçük payda bu değildir.",
            "doğru"],
           "Paylar eşit olduğunda alınan parça sayısı aynıdır. Bütün daha az parçaya ayrılmışsa her "
           "parça daha büyük olur; bu yüzden paydası en küçük olan 2/3 en büyüktür.",
           "2 adım; ön bilgi: payları eşit kesirlerde paydanın ters yönde etkisi; çeldiriciler yakın (payda büyüdükçe kesir küçülür); beceri: karşılaştırma",
           ["Kesirlerin paylarına bak; eşit mi?",
            "Paylar eşitse alınan parça sayısı için ne söylenir?",
            "Bütün daha çok parçaya ayrılırsa her parça büyür mü küçülür mü?",
            "Paydaları küçükten büyüğe sırala.",
            "Tam çözüm: paylar eşit olduğundan paydası en küçük olan kesir en büyüktür; 2/3 seçilir."])),
    (N1, S(3, "Paydaları eşit iki kesirden hangisi daha büyüktür?",
           ["Payı büyük olan", "Paydası büyük olan", "Payı küçük olan", "İkisi her zaman eşittir"], 0,
           ["doğru",
            "Paydalar zaten eşittir; aralarında büyüklük farkı yoktur.",
            "Parçalar aynı büyüklükte olduğuna göre daha az parça alan kesir daha küçüktür.",
            "Paylar farklıysa kesirler eşit olmaz."],
           "Paydaları eşit kesirlerde bütünler aynı sayıda eş parçaya ayrılmıştır; her parça aynı "
           "büyüklüktedir. Daha çok parça alan, yani payı büyük olan kesir daha büyüktür.",
           "1 adım; ön bilgi: paydaları eşit kesirlerin karşılaştırma kuralı; çeldiriciler yakın (pay ile paydanın rolünü değiştirme); beceri: kural bilgisi",
           ["Payda eşitken bütünlerin kaç parçaya ayrıldığını düşün.",
            "Parçaların büyüklüğü birbirine eşit mi?",
            "Alınan parça sayısını hangi sayı gösterir?",
            "Daha çok parça almak miktarı artırır mı azaltır mı?",
            "Tam çözüm: parçalar eşit büyüklükte olduğundan payı büyük olan kesir daha büyüktür."])),
    (N1, S(3, "Payları eşit iki kesirden hangisi daha büyüktür?",
           ["Paydası büyük olan", "Paydası küçük olan", "Payı büyük olan", "Karşılaştırma yapılamaz"], 1,
           ["Payda büyüdükçe bütün daha çok parçaya bölünür ve her parça küçülür.",
            "doğru",
            "Paylar zaten eşittir; aralarında büyüklük farkı yoktur.",
            "Payları eşit kesirler paydalarına bakılarak karşılaştırılabilir."],
           "Paylar eşitken alınan parça sayısı aynıdır. Bütün daha az sayıda parçaya ayrılmışsa her "
           "parça daha büyük olur; bu yüzden paydası küçük olan kesir daha büyüktür.",
           "2 adım; ön bilgi: payları eşit kesirlerde paydanın ters etkisi; çeldiriciler yakın (paydayı doğru orantılı sanma); beceri: kural bilgisi",
           ["Pay eşitken kaç parça alındığını düşün.",
            "Payda büyüdükçe her bir parçaya ne olur?",
            "Küçük paydalı bir bütünde parçalar büyük mü küçük mü?",
            "Aynı sayıda büyük parça mı daha çok eder, aynı sayıda küçük parça mı?",
            "Tam çözüm: paylar eşit olduğundan paydası küçük olan kesir daha büyüktür."])),
    (N1, S(4, "Bir öğrenci “1/2, 1/3'ten büyüktür” demiştir. Bu karşılaştırmanın geçerli olması için hangi koşul gerekir?",
           ["Kesirlerin paydaları eşit olmalıdır",
            "İki kesrin ait olduğu bütünler aynı büyüklükte olmalıdır",
            "Kesirler ondalık gösterime çevrilmelidir",
            "Payların ikisi de 1 olmalıdır"], 1,
           ["Paydaların eşit olması gerekmez; farklı paydalı kesirler de karşılaştırılabilir.",
            "doğru",
            "Ondalığa çevirmek bir kolaylıktır; karşılaştırmanın geçerlilik koşulu değildir.",
            "Payların 1 olması özel bir durumdur; genel koşul bu değildir."],
           "Kesirler karşılaştırılırken bütünlerin aynı büyüklükte olduğu kabul edilir. Farklı "
           "büyüklükteki iki pastanın 1/2'si ile 1/3'ü doğrudan karşılaştırılamaz.",
           "3 adım; ön bilgi: karşılaştırmanın ortak bütün varsayımına dayanması; çeldiriciler yakın (teknik koşulları temel koşul sanma); beceri: kavram bilgisi",
           ["Kesrin neyin parçasını gösterdiğini düşün.",
            "İki farklı büyüklükte pasta hayal et.",
            "Küçük pastanın yarısı büyük pastanın üçte birinden büyük olabilir mi?",
            "Karşılaştırmanın anlamlı olması için neyin aynı olması gerektiğine karar ver.",
            "Tam çözüm: karşılaştırma ancak bütünler aynı büyüklükteyse anlamlıdır."])),
    (N1, S(2, "5/8 ile 3/8 kesirleri arasına hangi işaret konmalıdır?",
           ["<", ">", "=", "Karşılaştırılamaz"], 1,
           ["Bu işaret solun sağdan küçük olduğunu söyler; oysa 5 payı 3 payından büyüktür.",
            "doğru",
            "Paylar farklı olduğu için kesirler eşit olamaz.",
            "Paydalar eşit olduğundan karşılaştırma doğrudan yapılabilir."],
           "Paydalar eşittir; parçalar aynı büyüklüktedir. 5 parça 3 parçadan çoktur, bu yüzden "
           "5/8 > 3/8 yazılır.",
           "1 adım; ön bilgi: paydaları eşit kesirlerde payın karşılaştırılması; çeldiriciler yakın (işaret yönü); beceri: karşılaştırma",
           ["İki kesrin paydalarına bak.",
            "Paydalar eşitse hangi sayıya bakılacağını belirle.",
            "Payları karşılaştır.",
            "İşaretin açık ağzının büyük sayıya baktığını hatırla.",
            "Tam çözüm: paydalar eşit, 5 > 3 olduğundan 5/8 > 3/8 yazılır."])),
    (N1, S(3, "3/7, 5/7, 1/7 ve 6/7 kesirleri küçükten büyüğe nasıl sıralanır?",
           ["1/7, 3/7, 5/7, 6/7", "6/7, 5/7, 3/7, 1/7", "1/7, 6/7, 3/7, 5/7", "3/7, 1/7, 5/7, 6/7"], 0,
           ["doğru",
            "Büyükten küçüğe sıralanmış; soru küçükten büyüğe istiyor.",
            "6/7 ile 3/7'nin yeri değişmiş; 6 payı 3'ten büyüktür.",
            "3/7 ile 1/7'nin yeri değişmiş; 1 payı 3'ten küçüktür."],
           "Paydalar eşit olduğundan yalnız paylar sıralanır: 1 < 3 < 5 < 6. Buna göre sıralama "
           "1/7, 3/7, 5/7, 6/7 olur.",
           "2 adım; ön bilgi: paydaları eşit kesirlerin sıralanması; çeldiriciler yakın (yön hatası ve tek yer değiştirme); beceri: sıralama",
           ["Sıralamanın hangi yönde istendiğini işaretle.",
            "Paydaların eşit olduğunu doğrula.",
            "Yalnız payları alıp sırala.",
            "Payların yanına paydayı geri yaz.",
            "Tam çözüm: 1 < 3 < 5 < 6 sıralaması 1/7, 3/7, 5/7, 6/7 dizilişini verir."])),
    (N1, S(4, "4/5, 4/9, 4/6 ve 4/11 kesirlerinden en küçüğü hangisidir?",
           ["4/5", "4/6", "4/9", "4/11"], 3,
           ["Paydası en küçük olduğu için bu kesir listenin en büyüğüdür.",
            "Paydası 6'dır; 11 paydasından küçük olduğu için bu kesir daha büyüktür.",
            "Paydası 9'dur; listedeki en büyük payda bu değildir.",
            "doğru"],
           "Paylar eşittir. Payda büyüdükçe bütün daha çok parçaya ayrılır ve her parça küçülür; "
           "bu yüzden paydası en büyük olan 4/11 en küçüktür.",
           "3 adım; ön bilgi: payları eşit kesirlerde paydanın ters etkisi; çeldiriciler yakın (payda büyüklüğünü doğru orantılı sanma); beceri: karşılaştırma",
           ["Payların eşit olduğunu doğrula.",
            "Paydaların ne anlattığını hatırla.",
            "Payda büyüdükçe parçaların büyüklüğüne ne olduğunu söyle.",
            "En büyük paydayı bul.",
            "Tam çözüm: paylar eşit olduğundan paydası en büyük olan 4/11 en küçüktür."])),
    (N1, S(5, "Bir öğrenci “5/6 kesri 5/8 kesrinden küçüktür, çünkü 6 sayısı 8'den küçüktür” demiştir. Öğrencinin hatası nedir?",
           ["Payları karşılaştırmalıydı; paydalar karşılaştırmada kullanılmaz",
            "Paydası küçük olan kesrin parçaları daha büyüktür; bu yüzden 5/6 daha büyüktür",
            "İki kesir eşittir; karşılaştırma yapılamaz",
            "Kesirleri ondalığa çevirmeden hiçbir karşılaştırma yapılamaz"], 1,
           ["Paylar zaten eşittir; bu soruda belirleyici olan paydadır.",
            "doğru",
            "Paydalar farklı olduğu için kesirler eşit değildir.",
            "Ondalığa çevirmek bir yoldur ama tek yol değildir; paylar eşitken payda doğrudan karar verdirir."],
           "Paylar eşit olduğunda payda küçüldükçe her parça büyür. 6 parçaya bölünmüş bütünün "
           "parçaları 8 parçaya bölünmüşünkinden büyüktür; bu yüzden 5/6 > 5/8'dir.",
           "4 adım; ön bilgi: paydanın kesir büyüklüğüne ters etkisi; çeldiriciler yakın (paydayı doğru orantılı okuma); beceri: hata teşhisi",
           ["İki kesrin paylarını karşılaştır.",
            "Paylar eşitse belirleyici olanın hangi sayı olduğunu söyle.",
            "Payda küçüldükçe parçaların büyüklüğüne ne olduğunu düşün.",
            "Öğrencinin kurduğu ilişkinin yönünü kontrol et.",
            "Tam çözüm: paylar eşittir ve payda küçüldükçe parçalar büyür; bu yüzden 5/6 > 5/8'dir."])),

    (N2, S(3, "2/3 ile 3/5 kesirleri karşılaştırıldığında hangi ifade doğrudur?",
           ["2/3 = 3/5", "2/3 > 3/5", "2/3 < 3/5", "2/3 ile 3/5 karşılaştırılamaz"], 1,
           ["Kesirler denk değildir; 10/15 ile 9/15 farklı değerlerdir.",
            "doğru",
            "Bu ifade solun küçük olduğunu söyler; oysa 10/15 > 9/15'tir.",
            "Paydalar eşitlenerek karşılaştırma yapılabilir."],
           "Paydalar 15'te eşitlenir: 2/3 = 10/15 ve 3/5 = 9/15. Paydalar eşit olunca paylar "
           "karşılaştırılır: 10 > 9 olduğundan 2/3 > 3/5'tir.",
           "3 adım; ön bilgi: farklı paydalı kesirlerin ortak paydada eşitlenmesi; çeldiriciler yakın (işaret yönü); beceri: karşılaştırma; hesaplama",
           ["İki paydanın ortak katını bul.",
            "Her kesri bu paydaya genişlet.",
            "Yeni payları karşılaştır.",
            "İşaretin yönünü paylara göre belirle.",
            "Tam çözüm: 2/3 = 10/15, 3/5 = 9/15 olur; 10 > 9 olduğundan 2/3 > 3/5'tir."])),
    (N2, S(3, "4/9, 5/12, 7/15 ve 9/20 kesirlerinden hangisi 1/2'ye en yakındır?",
           ["4/9", "5/12", "7/15", "9/20"], 2,
           ["1/2'den 1/18 kadar küçüktür; daha yakın bir kesir vardır.",
            "1/2'den 1/12 kadar küçüktür; listenin en uzak kesridir.",
            "doğru",
            "1/2'den 1/20 kadar küçüktür; 7/15 daha yakındır."],
           "Her kesir yarımla karşılaştırılır: 4/9 için yarım 4,5/9; 5/12 için 6/12; 7/15 için 7,5/15; "
           "9/20 için 10/20'dir. Uzaklıklar sırasıyla 1/18, 1/12, 1/30 ve 1/20'dir; en küçüğü "
           "1/30 olduğundan 7/15 yarıma en yakın kesirdir.",
           "5 adım; ön bilgi: referans kesir (1/2) ile uzaklık karşılaştırması; çeldiriciler çok yakın (hepsi yarımın biraz altında); beceri: karşılaştırma; akıl yürütme",
           ["Her kesirde paydanın yarısını hesapla.",
            "Payı bu yarım değerle karşılaştır.",
            "Aradaki farkı kesir olarak yaz.",
            "Bulduğun uzaklıkları birbiriyle karşılaştır.",
            "Tam çözüm: uzaklıklar 1/18, 1/12, 1/30 ve 1/20'dir; en küçük uzaklık 7/15'e aittir."])),
    (N2, S(2, "Aşağıdaki kesirlerden hangisi 1/2'den büyüktür?",
           ["3/8", "4/9", "5/11", "7/12"], 3,
           ["Paydanın yarısı 4'tür; pay 3 olduğundan kesir yarımdan küçüktür.",
            "Paydanın yarısı 4,5'tir; pay 4 olduğundan kesir yarımdan küçüktür.",
            "Paydanın yarısı 5,5'tir; pay 5 olduğundan kesir yarımdan küçüktür.",
            "doğru"],
           "Bir kesir, payı paydanın yarısından büyükse yarımdan büyüktür. 7/12'de paydanın yarısı "
           "6'dır ve pay 7 > 6 olduğundan bu kesir 1/2'den büyüktür.",
           "3 adım; ön bilgi: yarım ölçütünün pay-payda karşılaştırmasıyla uygulanması; çeldiriciler yakın (hepsi yarıma yakın); beceri: karşılaştırma",
           ["Bir kesrin yarımdan büyük olması için ne gerektiğini düşün.",
            "Her seçenekte paydanın yarısını hesapla.",
            "Payı bu değerle karşılaştır.",
            "Payı büyük olan tek seçeneği ara.",
            "Tam çözüm: 7/12'de paydanın yarısı 6, pay 7'dir; yalnız bu kesir yarımdan büyüktür."])),
    (N2, S(4, "5/8 ile 7/12 kesirlerini karşılaştırmak için paydalar hangi sayıda eşitlenmelidir?",
           ["20", "24", "96", "12"], 1,
           ["20 sayısı 8'e tam bölünmez; ortak payda olamaz.",
            "doğru",
            "96 sayısı ortak kat olsa da en küçük ortak kat değildir; işlemi gereksiz büyütür.",
            "12 sayısı 8'e tam bölünmez; ortak payda olamaz."],
           "Ortak payda, iki paydanın ortak katı olmalıdır. 8 ve 12'nin en küçük ortak katı 24'tür: "
           "5/8 = 15/24 ve 7/12 = 14/24 olur.",
           "3 adım; ön bilgi: en küçük ortak kat ile payda eşitleme; çeldiriciler yakın (ortak olmayan ya da gereksiz büyük kat); beceri: hesaplama",
           ["İki paydayı yan yana yaz.",
            "Her birinin katlarını sırayla listele.",
            "İki listede de görünen en küçük sayıyı bul.",
            "Bu sayının iki paydaya da tam bölünüp bölünmediğini doğrula.",
            "Tam çözüm: 8 ve 12'nin en küçük ortak katı 24'tür; kesirler 15/24 ve 14/24 olur."])),
    (N2, S(4, "3/4, 2/3, 5/6 ve 7/12 kesirleri küçükten büyüğe nasıl sıralanır?",
           ["7/12, 2/3, 3/4, 5/6", "2/3, 7/12, 3/4, 5/6", "5/6, 3/4, 2/3, 7/12", "7/12, 3/4, 2/3, 5/6"], 0,
           ["doğru",
            "2/3 ile 7/12'nin yeri değişmiş; 8/12 > 7/12'dir.",
            "Büyükten küçüğe sıralanmış; soru küçükten büyüğe istiyor.",
            "3/4 ile 2/3'ün yeri değişmiş; 9/12 > 8/12'dir."],
           "Paydalar 12'de eşitlenir: 3/4 = 9/12, 2/3 = 8/12, 5/6 = 10/12, 7/12 = 7/12. "
           "Paylar sıralanınca 7 < 8 < 9 < 10 çıkar; sıralama 7/12, 2/3, 3/4, 5/6 olur.",
           "5 adım; ön bilgi: dört kesrin ortak paydada sıralanması; çeldiriciler çok yakın (tek yer değiştirme); beceri: sıralama; hesaplama",
           ["Dört paydanın ortak katını bul.",
            "Her kesri bu paydaya genişlet.",
            "Yeni payları küçükten büyüğe sırala.",
            "Her payın yanına asıl kesri geri yaz.",
            "Tam çözüm: 12'de eşitlenince paylar 7, 8, 9 ve 10 olur; sıralama 7/12, 2/3, 3/4, 5/6'dır."])),
    (N2, S(2, "Aşağıdaki kesirlerden hangisi 1'den büyüktür?",
           ["9/10", "11/12", "13/13", "15/14"], 3,
           ["Payı paydasından küçüktür; bu kesir 1'den küçüktür.",
            "Payı paydasından küçüktür; bu kesir 1'den küçüktür.",
            "Payı paydasına eşittir; bu kesir tam olarak 1'e eşittir.",
            "doğru"],
           "Bir kesir, payı paydasından büyükse 1'den büyüktür. 15/14 kesrinde 15 > 14 olduğundan "
           "bu kesir birden büyüktür.",
           "2 adım; ön bilgi: pay-payda karşılaştırmasıyla 1'e göre konum; çeldiriciler yakın (biri tam olarak 1); beceri: karşılaştırma",
           ["Bir kesrin 1'e eşit olması için ne gerektiğini hatırla.",
            "Her seçenekte payı ve paydayı karşılaştır.",
            "Payı paydasından küçük olanları ele.",
            "Payı paydasına eşit olan seçeneğin 1'den büyük sayılıp sayılmayacağına karar ver.",
            "Tam çözüm: 15 > 14 olduğundan yalnız 15/14 kesri 1'den büyüktür."])),
    (N2, S(5, "1/3 ile 1/2 arasında bulunan bir kesir aşağıdakilerden hangisidir?",
           ["1/4", "2/5", "3/5", "1/6"], 1,
           ["1/4 kesri 1/3'ten küçüktür; aralığın dışındadır.",
            "doğru",
            "3/5 kesri 1/2'den büyüktür; aralığın dışındadır.",
            "1/6 kesri 1/3'ten de küçüktür; aralığın dışındadır."],
           "Paydalar 30'da eşitlenir: 1/3 = 10/30, 1/2 = 15/30, 2/5 = 12/30. 10 < 12 < 15 olduğundan "
           "2/5 kesri aralıktadır.",
           "5 adım; ön bilgi: iki kesir arasındaki aralığa yerleştirme; çeldiriciler yakın (aralığın iki yanında); beceri: karşılaştırma; hesaplama",
           ["Aralığın uçlarını belirleyen iki kesri yaz.",
            "Bütün kesirleri ortak bir paydaya çevir.",
            "Uç değerlerin paylarını bul.",
            "Seçeneklerin paylarını bu iki değerin arasında ara.",
            "Tam çözüm: 30 paydasında uçlar 10 ve 15'tir; 2/5 = 12/30 olduğundan aralıktadır."])),
    (N2, S(3, "7/10 ile 5/8 kesirlerinden hangisi daha büyüktür?",
           ["7/10", "5/8", "İkisi eşittir", "Paydası büyük olduğu için 5/8"], 0,
           ["doğru",
            "5/8 = 25/40'tır; 7/10'un karşılığı olan 28/40'tan küçüktür.",
            "Kesirler denk değildir; 28/40 ile 25/40 farklı değerlerdir.",
            "Payda büyüklüğü tek başına kesri büyütmez; paylar farklı olduğu için ortak paydaya geçilmelidir."],
           "Paydalar 40'ta eşitlenir: 7/10 = 28/40 ve 5/8 = 25/40. 28 > 25 olduğundan 7/10 > 5/8'dir.",
           "3 adım; ön bilgi: ortak paydada karşılaştırma; çeldiriciler yakın (işaret yönü); beceri: karşılaştırma; hesaplama",
           ["İki paydanın ortak katını bul.",
            "Kesirleri bu paydaya genişlet.",
            "Yeni payları karşılaştır.",
            "İşaretin açık ağzını büyük değere çevir.",
            "Tam çözüm: 7/10 = 28/40 ve 5/8 = 25/40'tır; 28 > 25 olduğundan 7/10 > 5/8 yazılır."])),
    (N2, S(4, "8/9, 11/12, 13/15 ve 17/18 kesirlerinden hangisi 1'e en yakındır?",
           ["8/9", "11/12", "13/15", "17/18"], 3,
           ["1'e uzaklığı 1/9'dur; daha yakın bir kesir vardır.",
            "1'e uzaklığı 1/12'dir; 17/18 daha yakındır.",
            "1'e uzaklığı 2/15'tir; listenin en uzak kesridir.",
            "doğru"],
           "Bir kesrin 1'e uzaklığı, payda ile pay arasındaki farkın payda üzerine yazılmasıyla "
           "bulunur: 1/9, 1/12, 2/15 ve 1/18. En küçük uzaklık 1/18 olduğundan 17/18 en yakındır.",
           "4 adım; ön bilgi: 1'e uzaklığın kesir olarak yazılması; çeldiriciler çok yakın (hepsi 1'in biraz altında); beceri: karşılaştırma",
           ["Bir kesrin 1'e ne kadar uzak olduğunu nasıl bulacağını düşün.",
            "Her kesirde paydadan payı çıkar.",
            "Çıkan farkı aynı paydanın üzerine yaz.",
            "Elde ettiğin uzaklık kesirlerini karşılaştır.",
            "Tam çözüm: uzaklıklar 1/9, 1/12, 2/15 ve 1/18'dir; en küçüğü 1/18 olduğundan 17/18 en yakındır."])),

    (N3, S(3, "Bir ankette dört seçeneğin tercih oranları 0,45; 1/2; %55 ve 6/10 olarak verilmiştir. En çok tercih edilen seçeneğin oranı hangisidir?",
           ["0,45", "1/2", "%55", "6/10"], 3,
           ["Ondalık karşılığı 0,45'tir; listenin en küçüğüdür.",
            "Ondalık karşılığı 0,50'dir; daha büyük oranlar vardır.",
            "Ondalık karşılığı 0,55'tir; 6/10 bundan büyüktür.",
            "doğru"],
           "Karşılaştırma için hepsi ondalığa çevrilir: 0,45; 0,50; 0,55 ve 6/10 = 0,60. "
           "En büyük değer 0,60 olduğundan 6/10 en çok tercih edilendir.",
           "4 adım; ön bilgi: farklı gösterimlerin ortak biçime çevrilerek karşılaştırılması; çeldiriciler çok yakın (dördü de 0,45-0,60 aralığında); beceri: gösterim dönüştürme; karşılaştırma",
           ["Dört değerin farklı gösterimlerde yazıldığını fark et.",
            "Hepsini aynı gösterime çevirmeye karar ver.",
            "Kesirleri ve yüzdeyi ondalığa çevir.",
            "Dört ondalık sayıyı karşılaştır.",
            "Tam çözüm: 0,45; 0,50; 0,55 ve 0,60 elde edilir; en büyüğü 6/10'a aittir."])),
    (N3, S(2, "%25 ile 1/4 miktarları için ne söylenebilir?",
           ["%25 daha büyüktür", "1/4 daha büyüktür", "İkisi eşittir", "%25 kesre çevrilemez"], 2,
           ["Gösterim biçimi miktarı büyütmez; iki değer aynıdır.",
            "1/4 kesri 25/100'e denktir; iki değer aynıdır.",
            "doğru",
            "Her yüzde gösterimi paydası 100 olan bir kesre çevrilebilir; %25 = 25/100'dür."],
           "1/4 kesri pay ve payda 25 ile genişletilerek 25/100 hâline gelir; bu da %25 demektir. "
           "İki gösterim aynı miktarı anlatır.",
           "2 adım; ön bilgi: yüzde ile kesrin denkliği; çeldiriciler yakın (gösterime göre büyüklük varsayma); beceri: gösterim dönüştürme",
           ["Yüzde gösteriminin paydasının kaç olduğunu hatırla.",
            "Kesrin paydasını bu sayıya çevirmeyi dene.",
            "Payı da aynı çarpanla genişlet.",
            "İki değeri karşılaştır.",
            "Tam çözüm: 1/4 = 25/100 = %25'tir; iki gösterim aynı miktarı anlatır."])),
    (N3, S(4, "0,8 ile 3/4 miktarlarından hangisi büyüktür?",
           ["3/4", "0,8", "İkisi eşittir", "Payı büyük olduğu için 3/4"], 1,
           ["3/4 = 0,75'tir ve 0,8'den küçüktür.",
            "doğru",
            "0,75 ile 0,80 farklı değerlerdir.",
            "Bir kesrin payı ile bir ondalık sayı doğrudan karşılaştırılamaz; ikisi aynı gösterime çevrilmelidir."],
           "3/4 kesri 75/100 = 0,75'tir. 0,80 > 0,75 olduğundan 0,8 daha büyüktür.",
           "3 adım; ön bilgi: kesri ondalığa çevirerek karşılaştırma; çeldiriciler yakın (iki değer birbirine yakın); beceri: gösterim dönüştürme; karşılaştırma",
           ["İki miktarın gösterimlerinin farklı olduğunu fark et.",
            "Kesri ondalığa çevir.",
            "İki ondalık sayıyı basamak basamak karşılaştır.",
            "Onda birler basamağına özellikle bak.",
            "Tam çözüm: 3/4 = 0,75'tir; 0,8 > 0,75 olduğundan 0,8 daha büyüktür."])),
    (N3, S(5, "3/5; %55 ve 0,58 miktarları küçükten büyüğe nasıl sıralanır?",
           ["%55 < 0,58 < 3/5", "3/5 < %55 < 0,58", "0,58 < %55 < 3/5", "%55 < 3/5 < 0,58"], 0,
           ["doğru",
            "3/5 = 0,60 olduğundan listenin en büyüğüdür; başa yazılamaz.",
            "0,58 değeri %55'ten büyüktür; sıralamanın başına yazılamaz.",
            "3/5 = 0,60 ve 0,58 değerlerinin sırası ters yazılmış."],
           "Hepsi ondalığa çevrilir: 3/5 = 0,60; %55 = 0,55; 0,58. Sıralama 0,55 < 0,58 < 0,60, "
           "yani %55 < 0,58 < 3/5 olur.",
           "5 adım; ön bilgi: üç farklı gösterimin ortak biçimde sıralanması; çeldiriciler çok yakın (0,55-0,60 aralığı); beceri: sıralama; gösterim dönüştürme",
           ["Üç miktarın gösterimlerini işaretle.",
            "Hepsini ondalığa çevir.",
            "Üç ondalık sayıyı küçükten büyüğe diz.",
            "Her sayının yanına asıl gösterimini geri yaz.",
            "Tam çözüm: 0,55; 0,58 ve 0,60 elde edilir; sıralama %55 < 0,58 < 3/5'tir."])),
    (N3, S(3, "Farklı gösterimlerdeki miktarları karşılaştırmanın en güvenilir yolu nedir?",
           ["En büyük sayıyı taşıyan gösterimi seçmek",
            "Hepsini ortak bir gösterime çevirip karşılaştırmak",
            "Yüzde gösterimlerini her zaman büyük saymak",
            "Paydası büyük olan kesri büyük saymak"], 1,
           ["Gösterimlerdeki sayılar farklı bütünlere göre yazılmıştır; doğrudan karşılaştırılamaz.",
            "doğru",
            "Yüzde yalnız bir yazım biçimidir; miktarın büyüklüğünü belirlemez.",
            "Payda büyüklüğü tek başına kesrin büyüklüğünü belirlemez.",],
           "Kesir, ondalık ve yüzde aynı miktarın farklı gösterimleridir. Güvenilir karşılaştırma "
           "için hepsi ortak bir gösterime, çoğunlukla ondalığa çevrilir.",
           "2 adım; ön bilgi: karşılaştırmanın ortak gösterim gerektirmesi; çeldiriciler yakın (biçime bakarak karar verme); beceri: yöntem seçme",
           ["Farklı gösterimlerdeki sayıların doğrudan karşılaştırılıp karşılaştırılamayacağını düşün.",
            "0,4 ile 1/4 örneğini dene: hangisi büyük?",
            "Aynı biçime çevirdiğinde karşılaştırmanın kolaylaşıp kolaylaşmadığına bak.",
            "Bir gösterim biçiminin diğerinden büyük sayılmasının anlamlı olup olmadığını sorgula.",
            "Tam çözüm: en güvenilir yol hepsini ortak bir gösterime çevirip öyle karşılaştırmaktır."])),
    (N3, S(4, "Bir öğrenci “%30, 3/10'dan büyüktür” demiştir. Bu iddia için ne söylenebilir?",
           ["Doğrudur; yüzde gösterimi daha büyüktür",
            "Yanlıştır; iki miktar birbirine eşittir",
            "Doğrudur; 30 sayısı 3'ten büyüktür",
            "Karşılaştırılamaz; biri yüzde, diğeri kesirdir"], 1,
           ["Gösterim biçimi miktarı büyütmez; iki değer aynıdır.",
            "doğru",
            "Payları doğrudan karşılaştırmak yanıltıcıdır; paydalar farklıdır.",
            "İki gösterim ortak biçime çevrilerek karşılaştırılabilir."],
           "3/10 kesri pay ve payda 10 ile genişletilerek 30/100 hâline gelir; bu da %30 demektir. "
           "İki miktar eşittir.",
           "3 adım; ön bilgi: gösterim değişiminin miktarı korumasi; çeldiriciler yakın (rakam büyüklüğüne bakma); beceri: hata teşhisi",
           ["İki miktarı ortak gösterime çevirmeyi dene.",
            "Kesrin paydasını 100 yapacak çarpanı bul.",
            "Payı da aynı çarpanla genişlet.",
            "Elde ettiğin değeri verilen yüzdeyle karşılaştır.",
            "Tam çözüm: 3/10 = 30/100 = %30'dur; iki miktar eşittir."])),
    (N3, S(5, "Bir öğretmen “A grubunun 1/2'si, B grubunun 3/4'ünden fazladır” demiştir. Bu iddia hakkında ne söylenebilir?",
           ["Doğrudur; 1/2 her zaman 3/4'ten büyüktür",
            "Yanlıştır; 1/2 her zaman 3/4'ten küçüktür",
            "Grupların büyüklükleri verilmediği için karşılaştırılamaz",
            "Doğrudur; paydası küçük olan kesir her zaman büyüktür"], 2,
           ["Aynı bütün üzerinde 1/2 < 3/4'tür; ayrıca bütünler farklıysa kesirler doğrudan karşılaştırılamaz.",
            "Aynı bütün üzerinde bu doğrudur ama burada bütünler farklı gruplardır; kesin bir yargı verilemez.",
            "doğru",
            "Paydası küçük olan kesrin büyük olması yalnız paylar eşitken geçerlidir; burada paylar farklıdır."],
           "Kesirler ancak aynı büyüklükteki bütünler üzerinde karşılaştırılabilir. A ve B gruplarının "
           "kişi sayıları verilmediği için 40 kişilik A grubunun yarısı (20 kişi), 20 kişilik B "
           "grubunun 3/4'ünden (15 kişi) fazla olabilir; grup büyüklükleri bilinmeden karar verilemez.",
           "5 adım; ön bilgi: farklı bütünler üzerindeki kesirlerin karşılaştırılamaması; çeldiriciler çok yakın (aynı bütün varsayarak karar verme); beceri: akıl yürütme",
           ["İki kesrin hangi bütünlere ait olduğunu belirle.",
            "Bu bütünlerin aynı büyüklükte olup olmadığına bak.",
            "A grubu 40, B grubu 20 kişi olsaydı ne çıkacağını hesapla.",
            "Grup büyüklükleri bilinmeden kesin bir yargı verilip verilemeyeceğine karar ver.",
            "Tam çözüm: kesirler ancak aynı bütünler üzerinde karşılaştırılır; grup büyüklükleri verilmediği için bu iddia hakkında karar verilemez."])),
]

# ---------------------------------------------------------------------------
# MAT.5.6.2 — olayların olasılıklarını karşılaştırma
# ---------------------------------------------------------------------------

N6 = "tr.g05.mat.5.6.note.01"

A62 = [
    S(1, "A torbasında 10 topun 5'i, B torbasında 10 topun 4'ü yıldızlıdır. Yıldızlı top çekme olasılığı hangi torbada daha yüksektir?",
      ["A torbası", "B torbası", "İki torbada eşit", "Torbaların rengine bağlıdır"], 0,
      ["doğru",
       "B torbasında yıldızlı oranı 4/10'dur; A torbasındaki 5/10'dan küçüktür.",
       "Yıldızlı sayıları farklı olduğu için oranlar da farklıdır: 5/10 ile 4/10.",
       "Torbaların rengi deneyin sonuçlarını etkilemez; olasılık yıldızlı top oranına bağlıdır."],
      "İki torbada da 10 top vardır. Olasılıklar 5/10 ve 4/10'dur; 5/10 > 4/10 olduğundan A "
      "torbasında yıldızlı top çekme olasılığı daha yüksektir.",
      "1 adım; ön bilgi: eşit toplamda istenen sonuç sayısının karşılaştırılması; çeldiriciler yakın (deneyle ilgisiz özellik); beceri: olasılık karşılaştırma",
      ["Her torbadaki toplam top sayısını yaz.",
       "Her torbadaki yıldızlı top sayısını yaz.",
       "Toplamların eşit olup olmadığını kontrol et.",
       "Toplamlar eşitse hangi sayının belirleyici olduğuna karar ver.",
       "Tam çözüm: olasılıklar 5/10 ve 4/10'dur; A torbasındaki olasılık daha yüksektir."]),
    S(3, "A torbasında 20 topun 6'sı, B torbasında 10 topun 4'ü yıldızlıdır. Yıldızlı top çekme olasılığı hangi torbada daha yüksektir?",
      ["A torbası", "İki torbada eşit", "B torbası", "Toplam top sayısı fazla olan torbada"], 2,
      ["A torbasındaki oran 6/20 = 3/10'dur; B'deki 4/10'dan küçüktür.",
       "Oranlar 3/10 ve 4/10'dur; birbirine eşit değildir.",
       "doğru",
       "Toplam top sayısı tek başına olasılığı belirlemez; belirleyici olan yıldızlıların orandır."],
      "Toplamlar farklı olduğu için ham sayılar karşılaştırılamaz. Oranlar hesaplanır: "
      "6/20 = 3/10 ve 4/10. 4/10 > 3/10 olduğundan B torbasındaki olasılık daha yüksektir.",
      "4 adım; ön bilgi: farklı toplamlarda oran üzerinden karşılaştırma; çeldiriciler yakın (ham sayıyı ya da toplamı belirleyici sanma); beceri: olasılık karşılaştırma",
      ["Her torbadaki toplam ve yıldızlı sayılarını yaz.",
       "Toplamların eşit olup olmadığına bak.",
       "Toplamlar farklıysa her torba için bir oran kur.",
       "Oranları ortak paydada karşılaştır.",
       "Tam çözüm: oranlar 6/20 = 3/10 ve 4/10'dur; B torbasındaki olasılık daha yüksektir."]),
    S(2, "Eş 8 bölmeli iki çarktan birincisinde 7, ikincisinde 5 bölüm yıldızlıdır. Yıldız gelme olasılığı hangi çarkta daha yüksektir?",
      ["İki çarkta eşit", "İkinci çark", "Birinci çark", "Çarkların rengine bağlıdır"], 2,
      ["Yıldızlı bölüm sayıları farklıdır; olasılıklar 7/8 ile 5/8'dir ve eşit değildir.",
       "İkinci çarkta olasılık 5/8'dir; birinci çarktaki 7/8'den küçüktür.",
       "doğru",
       "Renk deneyin sonuçlarını etkilemez; belirleyici olan yıldızlı bölüm sayısıdır."],
      "İki çarkta da 8 eş bölme vardır, yani her bölmenin şansı eşittir. Olasılıklar 7/8 ve 5/8'dir; "
      "7/8 > 5/8 olduğundan birinci çarkta yıldız gelme olasılığı daha yüksektir.",
      "2 adım; ön bilgi: eş bölmeli çarkta olasılığın bölme sayısına oranla bulunması; çeldiriciler yakın (deneyle ilgisiz özellik); beceri: olasılık karşılaştırma",
      ["Çarklardaki toplam bölme sayısını yaz.",
       "Bölmelerin eş olup olmadığını kontrol et.",
       "Her çarktaki yıldızlı bölüm sayısını yaz.",
       "İki oranı karşılaştır.",
       "Tam çözüm: olasılıklar 7/8 ve 5/8'dir; birinci çarktaki olasılık daha yüksektir."]),
    S(3, "Adil bir zar atıldığında çift sayı gelmesi ile 6 gelmesi olayları karşılaştırıldığında ne söylenebilir?",
      ["6 gelmesi daha olasıdır", "İkisi eşit olasılıklıdır",
       "Çift sayı gelmesi daha olasıdır", "Karşılaştırma yapılamaz"], 2,
      ["6 gelmesi olayı tek bir sonucu kapsar: olasılığı 1/6'dır.",
       "Bir olay üç sonucu, diğeri tek sonucu kapsadığı için olasılıkları eşit olamaz.",
       "doğru",
       "Olası sonuçlar belirli olduğu için iki olay karşılaştırılabilir."],
      "Zarda olası sonuçlar 1, 2, 3, 4, 5 ve 6'dır. Çift sayı olayı 2, 4 ve 6 sonuçlarını kapsar: "
      "olasılığı 3/6. “6 gelmesi” olayı yalnız bir sonucu kapsar: olasılığı 1/6. "
      "3/6 > 1/6 olduğundan çift sayı gelmesi daha olasıdır.",
      "3 adım; ön bilgi: olayın kapsadığı sonuç sayısının olasılığı belirlemesi; çeldiriciler yakın (tek sonuçlu olayı eşit sanma); beceri: olasılık karşılaştırma",
      ["Zarın bütün olası sonuçlarını listele.",
       "Birinci olayın hangi sonuçları kapsadığını işaretle.",
       "İkinci olay için aynısını yap.",
       "İki olayın kapsadığı sonuç sayılarını karşılaştır.",
       "Tam çözüm: çift sayı olayı üç sonucu (3/6), 6 gelmesi tek sonucu (1/6) kapsar; çift sayı gelmesi daha olasıdır."]),
    S(4, "Adil bir para iki kez atılıyor. “En az bir kez yazı gelmesi” ile “iki kez tura gelmesi” olayları karşılaştırıldığında ne söylenebilir?",
      ["İki kez tura gelmesi daha olasıdır", "İkisi eşit olasılıklıdır",
       "En az bir kez yazı gelmesi daha olasıdır", "Olası sonuçlar belirlenemez"], 2,
      ["İki kez tura yalnız bir sonuçtur: TT. Olasılığı 1/4'tür.",
       "Bir olay üç sonucu, diğeri tek sonucu kapsadığından olasılıkları eşit olamaz.",
       "doğru",
       "İki atışın olası sonuçları YY, YT, TY ve TT olarak listelenebilir."],
      "İki atışın olası sonuçları YY, YT, TY ve TT'dir. “En az bir kez yazı” olayı YY, YT ve TY "
      "sonuçlarını kapsar: 3/4. “İki kez tura” yalnız TT'yi kapsar: 1/4. "
      "3/4 > 1/4 olduğundan en az bir kez yazı gelmesi daha olasıdır.",
      "4 adım; ön bilgi: iki aşamalı deneyde olası sonuçların listelenmesi; çeldiriciler yakın ('en az bir' ifadesini tek sonuç sanma); beceri: olasılık karşılaştırma",
      ["İki atışın bütün olası sonuçlarını yaz.",
       "Kaç farklı sonuç olduğunu say.",
       "“En az bir kez yazı” ifadesinin hangi sonuçları kapsadığını işaretle.",
       "İkinci olayın kaç sonucu kapsadığını bul.",
       "Tam çözüm: olası sonuçlar YY, YT, TY, TT'dir; olasılıklar 3/4 ve 1/4'tür ve ilki daha büyüktür."]),
    S(1, "Bir olayın olasılığı en fazla kaç olabilir?",
      ["0", "1/2", "1", "Sınırsızdır"], 2,
      ["Sıfır, gerçekleşmesi mümkün olmayan olayın olasılığıdır.",
       "Yarım, eşit olasılığı gösteren ara değerdir; en büyük değer değildir.",
       "doğru",
       "Olasılık 0 ile 1 arasında yer alır; sınırsız büyüyemez."],
      "Olasılık 0 ile 1 arasında yer alır. Mutlaka gerçekleşecek bir olayın olasılığı 1'dir; "
      "bundan büyük bir değer alamaz.",
      "1 adım; ön bilgi: olasılık ölçeğinin sınırları; çeldiriciler yakın (ölçeğin diğer noktaları); beceri: kavram bilgisi",
      ["Olasılığın hangi iki sayı arasında yer aldığını hatırla.",
       "Kesin gerçekleşen bir olay düşün.",
       "Bu olayın olasılığının ölçeğin neresinde olduğunu söyle.",
       "Ölçeğin dışına çıkılıp çıkılamayacağını sorgula.",
       "Tam çözüm: olasılık 0 ile 1 arasındadır; en büyük değer 1'dir."]),
    S(2, "Bir torbada yalnız kırmızı toplar vardır. Torbadan mavi top çekme olayı için ne söylenir?",
      ["Kesin olaydır; olasılığı 1'dir", "İmkânsız olaydır; olasılığı 0'dır",
       "Eşit olasılıklı olaydır", "Olasılığı 1/2'dir"], 1,
      ["Kesin olay mutlaka gerçekleşen olaydır; torbada mavi top yoktur.",
       "doğru",
       "Eşit olasılık iki sonucun aynı şansa sahip olmasıdır; burada mavi sonucu hiç yoktur.",
       "Yarım değeri eşit olasılığı gösterir; gerçekleşemeyen bir olay için kullanılmaz."],
      "Torbada mavi top bulunmadığından bu olay gerçekleşemez. Gerçekleşmesi mümkün olmayan "
      "olayın olasılığı 0'dır.",
      "1 adım; ön bilgi: imkânsız olayın olasılığı; çeldiriciler yakın (ölçeğin diğer noktaları); beceri: kavram uygulama",
      ["Torbada hangi renklerin bulunduğunu yaz.",
       "İstenen sonucun torbada olup olmadığını kontrol et.",
       "Gerçekleşemeyen bir olayın olasılığının kaç olduğunu hatırla.",
       "Bu değeri ölçek üzerinde yerleştir.",
       "Tam çözüm: torbada mavi top olmadığından olay imkânsızdır ve olasılığı 0'dır."]),
    S(2, "Adil bir para atıldığında yazı gelmesi olayı için ne söylenir?",
      ["Kesin olaydır", "İmkânsız olaydır",
       "Gerçekleşmesi ve gerçekleşmemesi eşit olasılıklıdır", "Olasılığı 1/4'tür"], 2,
      ["Kesin olay mutlaka gerçekleşir; para tura da gelebilir.",
       "İmkânsız olay hiç gerçekleşmez; yazı gelmesi mümkündür.",
       "doğru",
       "Paranın iki olası sonucu vardır; olasılık 1/2'dir."],
      "Adil bir paranın iki olası sonucu vardır ve ikisi eşit şansa sahiptir. Yazı gelme olasılığı "
      "1/2'dir; bu değer eşit olasılığı gösterir.",
      "1 adım; ön bilgi: eşit olasılıklı olay ve 1/2 değeri; çeldiriciler yakın (ölçeğin uçları); beceri: kavram uygulama",
      ["Paranın kaç olası sonucu olduğunu say.",
       "Sonuçların eşit şansa sahip olup olmadığını düşün.",
       "İstenen sonucun kaç tanesini kapsadığını belirle.",
       "Oranı yazıp ölçek üzerinde yerleştir.",
       "Tam çözüm: iki eşit şanslı sonuçtan biri istendiğinden olasılık 1/2'dir; olay eşit olasılıklıdır."]),
    S(4, "Bir torbada 2 kırmızı ve 7 başka renk top vardır. Torbaya 1 kırmızı top eklenirse kırmızı top çekme olasılığı nasıl değişir?",
      ["Değişmez", "Azalır", "Artar", "Sıfır olur"], 2,
      ["Hem kırmızı sayısı hem toplam değiştiği için oran aynı kalmaz.",
       "Kırmızı sayısı arttığı için oran küçülemez: 2/9 iken 3/10 olur.",
       "doğru",
       "Torbada kırmızı top bulunduğu sürece olasılık sıfır olamaz."],
      "Başlangıçta olasılık 2/9'dur. Bir kırmızı eklenince 3/10 olur. Ortak paydada 20/90 ile "
      "27/90 karşılaştırılır; 27/90 > 20/90 olduğundan olasılık artar.",
      "4 adım; ön bilgi: hem istenen sonucun hem toplamın değiştiği durumda oranın karşılaştırılması; çeldiriciler yakın (oranı sabit ya da azalan sanma); beceri: akıl yürütme",
      ["Başlangıçtaki toplam ve kırmızı sayısını yaz.",
       "Ekleme sonrası yeni sayıları yaz.",
       "İki durum için ayrı ayrı oran kur.",
       "İki oranı ortak paydada karşılaştır.",
       "Tam çözüm: oran 2/9 iken 3/10 olur; ortak paydada 20/90 < 27/90 olduğundan olasılık artar."]),
    S(4, "Bir torbada 3 mavi ve 9 başka renk top vardır. Torbadan 3 tane mavi olmayan top çıkarılırsa mavi top çekme olasılığı kaç olur?",
      ["1/3", "1/4", "1/2", "3/4"], 0,
      ["doğru",
       "Bu değer toplar çıkarılmadan önceki olasılıktır: 3/12.",
       "Mavi sayısı diğerlerine eşit olmadığı için olasılık yarım olamaz.",
       "Bu değer mavi olmayanların oranına yakındır; soru mavi çekme olasılığını istiyor."],
      "Başlangıçta olasılık 3/12 = 1/4'tür. Üç mavi olmayan top çıkarılınca toplam 9'a düşer ve "
      "olasılık 3/9 = 1/3 olur. 1/3 > 1/4 olduğundan olasılık artar.",
      "4 adım; ön bilgi: istenen sonuç sabitken toplamın azalmasının oranı büyütmesi; çeldiriciler yakın (yönü ters okuma); beceri: akıl yürütme",
      ["Başlangıçtaki toplam ve mavi sayısını yaz.",
       "Çıkarılan topların hangi renkte olduğuna dikkat et.",
       "Yeni toplam ve yeni mavi sayısını yaz.",
       "İki oranı sadeleştirip karşılaştır.",
       "Tam çözüm: oran 3/12 = 1/4 iken 3/9 = 1/3 olur; 1/3 > 1/4 olduğundan olasılık artar."]),
    S(3, "Bir deneyde ortaya çıkabilecek bütün durumların listesine ne ad verilir?",
      ["Olay", "Olası sonuçlar", "Olasılık", "Deney"], 1,
      ["Olay, olası sonuçlar içinden ilgilendiğimiz sonuçlar grubudur.",
       "doğru",
       "Olasılık bir olayın gerçekleşme ihtimalini gösteren sayıdır.",
       "Deney, sonucu önceden kesin bilinmeyen işlemin kendisidir."],
      "Bir deneyde ortaya çıkabilecek her duruma sonuç, bunların tamamının listesine olası "
      "sonuçlar denir. Olay ise bu liste içinden ilgilendiğimiz sonuçların oluşturduğu gruptur.",
      "2 adım; ön bilgi: deney, sonuç, olası sonuçlar ve olay kavramlarının ayrımı; çeldiriciler yakın (dördü de aynı konunun terimleri); beceri: kavram bilgisi",
      ["Zar atma örneğini düşün: bütün gelebilecek sayıları yaz.",
       "Bu listenin adını hatırlamaya çalış.",
       "“Çift sayı gelmesi” ifadesinin bu listenin neresine karşılık geldiğini düşün.",
       "Liste ile listenin bir parçasını birbirinden ayır.",
       "Tam çözüm: bütün durumların listesine olası sonuçlar denir; bunların bir alt grubu olaydır."]),
    S(3, "Adil bir zar atıldığında 3'ten büyük sayı gelmesi ile tek sayı gelmesi olayları karşılaştırıldığında ne söylenebilir?",
      ["3'ten büyük sayı gelmesi daha olasıdır", "Tek sayı gelmesi daha olasıdır",
       "İkisi eşit olasılıklıdır", "Zarın kaç kez atıldığı bilinmeden karar verilemez"], 2,
      ["3'ten büyük sayılar 4, 5 ve 6'dır: üç sonuç, yani 3/6.",
       "Tek sayılar 1, 3 ve 5'tir: üç sonuç, yani 3/6.",
       "doğru",
       "Olasılık tek bir atış için tanımlıdır; atış sayısı bilinmeden de karşılaştırma yapılabilir."],
      "3'ten büyük sayılar 4, 5 ve 6; tek sayılar 1, 3 ve 5'tir. İki olay da üçer sonucu kapsar, "
      "yani ikisinin de olasılığı 3/6'dır; olaylar eşit olasılıklıdır.",
      "3 adım; ön bilgi: farklı tanımlı iki olayın aynı sayıda sonucu kapsayabilmesi; çeldiriciler yakın (birini büyük sanma); beceri: olasılık karşılaştırma",
      ["Zarın olası sonuçlarını listele.",
       "Birinci olayın kapsadığı sonuçları işaretle.",
       "İkinci olayın kapsadığı sonuçları işaretle.",
       "Kapsanan sonuç sayılarını karşılaştır.",
       "Tam çözüm: iki olay da üçer sonucu kapsar; olasılıkları 3/6 ile eşittir."]),
    S(5, "Adil bir zar atıldığında asal sayı gelmesi ile 3'ten küçük sayı gelmesi olayları karşılaştırıldığında ne söylenebilir?",
      ["3'ten küçük sayı gelmesi daha olasıdır", "İkisi eşit olasılıklıdır",
       "Asal sayı gelmesi daha olasıdır", "1 sayısı asal olduğu için ikisi eşittir"], 2,
      ["3'ten küçük sayılar 1 ve 2'dir: iki sonuç, yani 2/6.",
       "Bir olay üç, diğeri iki sonucu kapsadığından olasılıkları eşit değildir.",
       "doğru",
       "1 sayısı asal değildir; asal sayılar 2, 3 ve 5 olduğundan olaylar eşit olasılıklı olmaz."],
      "Zardaki asal sayılar 2, 3 ve 5'tir: üç sonuç, olasılık 3/6. 3'ten küçük sayılar 1 ve 2'dir: "
      "iki sonuç, olasılık 2/6. 3/6 > 2/6 olduğundan asal sayı gelmesi daha olasıdır.",
      "4 adım; ön bilgi: asal sayı tanımının olası sonuçlara uygulanması; çeldiriciler yakın (1'i asal sayma eğilimi); beceri: olasılık karşılaştırma",
      ["Zarın olası sonuçlarını yaz.",
       "Bunlardan hangilerinin asal olduğunu belirle; 1 sayısının asal olmadığını hatırla.",
       "3'ten küçük sayıları işaretle.",
       "İki olayın kapsadığı sonuç sayılarını karşılaştır.",
       "Tam çözüm: asal sayılar 2, 3, 5 (3/6); 3'ten küçükler 1, 2'dir (2/6). Asal sayı gelmesi daha olasıdır."]),
    S(4, "Adil bir para iki kez atılıyor. “Tam bir kez yazı gelmesi” olayının olasılığı kaçtır?",
      ["1/4", "1/2", "3/4", "1"], 1,
      ["Tam bir kez yazı olayı iki sonucu kapsar; 1/4 tek sonuçlu bir olaya aittir.",
       "doğru",
       "3/4 değeri “en az bir kez yazı” olayına aittir; o olay üç sonucu kapsar.",
       "Olasılığın 1 olması olayın mutlaka gerçekleşmesi demektir; TT sonucunda yazı gelmez."],
      "Olası sonuçlar YY, YT, TY ve TT'dir. Tam bir kez yazı gelmesi YT ve TY sonuçlarını kapsar: "
      "olasılık 2/4 = 1/2'dir.",
      "4 adım; ön bilgi: 'tam bir kez' ile 'en az bir kez' ifadelerinin farklı olayları tanımlaması; çeldiriciler çok yakın (komşu olayların olasılıkları); beceri: olay belirleme",
      ["İki atışın olası sonuçlarını listele.",
       "“Tam bir kez” ifadesinin ne anlama geldiğini söyle.",
       "Bu koşulu sağlayan sonuçları işaretle.",
       "İşaretlediğin sonuç sayısını toplam sonuç sayısına oranla.",
       "Tam çözüm: YT ve TY sonuçları koşulu sağlar; olasılık 2/4 = 1/2'dir."]),
    S(2, "Bir çarkın bölmeleri eş büyüklükte değilse olasılık nasıl hesaplanır?",
      ["Bölme sayısına bakılarak hesaplanır",
       "Bölmelerin kapladığı alanlara bakılarak hesaplanır",
       "Her bölme eşit sayılarak hesaplanır",
       "Hesaplanamaz; olasılık yalnız eş bölmeli çarklarda tanımlıdır"], 1,
      ["Bölme sayısına bakmak, bölmelerin eş olduğu varsayımına dayanır; burada bu varsayım geçerli değildir.",
       "doğru",
       "Bölmeler eş değilse eşit saymak yanlış sonuç verir; büyük bölmenin şansı daha yüksektir.",
       "Olasılık eş olmayan bölmelerde de tanımlıdır; ölçüt alan olur."],
      "Olası sonuçların eşit şansa sahip olması, çarkta bölmelerin eş büyüklükte olmasına bağlıdır. "
      "Bölmeler eş değilse her bölmenin şansı kapladığı alanla orantılıdır.",
      "3 adım; ön bilgi: eşit şans koşulunun eş bölmeye bağlı olması; çeldiriciler yakın (sayma kuralını koşulsuz uygulama); beceri: kavram bilgisi",
      ["Eş bölmeli bir çarkta her bölmenin şansının neden eşit olduğunu düşün.",
       "Bölmelerden biri diğerlerinin iki katı olsaydı ne değişirdi?",
       "Şansın neyle orantılı hâle geldiğini belirle.",
       "Bölme sayısını saymanın hâlâ geçerli olup olmadığına karar ver.",
       "Tam çözüm: bölmeler eş değilse şans kaplanan alanla orantılıdır; sayma kuralı uygulanamaz."]),
    S(5, "Bir torbada 4 yeşil ve 8 başka renk top vardır. Yeşil top çekme olasılığını 1/2 yapmak için torbaya en az kaç yeşil top eklenmelidir?",
      ["2", "4", "6", "8"], 1,
      ["İki yeşil eklenince oran 6/14 = 3/7 olur; bu değer 1/2'den küçüktür.",
       "doğru",
       "Altı yeşil eklenince oran 10/18 = 5/9 olur; bu değer 1/2'yi aşar.",
       "Sekiz yeşil eklenince oran 12/20 = 3/5 olur; 1/2'nin üzerine çıkar."],
      "Başlangıçta 4 yeşil ve toplam 12 top vardır. n yeşil eklenirse oran (4 + n)/(12 + n) olur. "
      "Bu oranın 1/2 olması için yeşil sayısının diğerlerine eşitlenmesi gerekir; diğerleri 8 "
      "olduğuna göre yeşil de 8 olmalıdır, yani 4 top eklenir.",
      "5 adım; ön bilgi: 1/2 olasılığın istenen ve istenmeyen sonuç sayılarının eşitliği anlamına gelmesi; çeldiriciler yakın (deneme değerleri); beceri: model kurma; akıl yürütme",
      ["Başlangıçtaki yeşil ve yeşil olmayan sayılarını ayrı ayrı yaz.",
       "Olasılığın 1/2 olması iki grup için ne anlama gelir, düşün.",
       "Yeşil olmayanların sayısının değişip değişmediğine bak.",
       "Yeşilleri bu sayıya eşitlemek için kaç top gerektiğini hesapla.",
       "Tam çözüm: yeşil olmayanlar 8'dir; olasılığın 1/2 olması için yeşiller de 8 olmalıdır, yani 4 top eklenir."]),
    S(3, "Adil bir zar atıldığında 7 gelmesi olayı ile 1'den büyük sayı gelmesi olayı karşılaştırıldığında ne söylenebilir?",
      ["7 gelmesi daha olasıdır", "İkisi eşit olasılıklıdır",
       "1'den büyük sayı gelmesi daha olasıdır", "İkisi de imkânsızdır"], 2,
      ["Zarda 7 yüzü bulunmadığından bu olay gerçekleşemez; olasılığı 0'dır.",
       "Biri imkânsız, diğeri yüksek olasılıklı olduğundan eşit olamazlar.",
       "doğru",
       "1'den büyük sayı gelmesi mümkündür; 2, 3, 4, 5 ve 6 sonuçları bu olayı sağlar."],
      "Zarda 7 yüzü olmadığından “7 gelmesi” imkânsız olaydır ve olasılığı 0'dır. "
      "“1'den büyük sayı gelmesi” olayı 2, 3, 4, 5 ve 6 sonuçlarını kapsar: olasılığı 5/6'dır. "
      "5/6 > 0 olduğundan ikinci olay daha olasıdır.",
      "3 adım; ön bilgi: imkânsız olayın ölçeğin en altında yer alması; çeldiriciler yakın (imkânsızı olası sanma); beceri: olasılık karşılaştırma",
      ["Zarın yüzlerinde hangi sayıların bulunduğunu yaz.",
       "Birinci olayın gerçekleşip gerçekleşemeyeceğine karar ver.",
       "İkinci olayın kaç sonucu kapsadığını say.",
       "İki olasılığı ölçek üzerinde karşılaştır.",
       "Tam çözüm: 7 gelmesi imkânsızdır (0); 1'den büyük sayı gelmesi 5/6'dır ve daha olasıdır."]),
    S(4, "Bir torbadan top çekme deneyinde kırmızı çekme olasılığı 3/10'dur. Kırmızı olmayan bir top çekme olasılığı kaçtır?",
      ["3/10", "7/10", "1/10", "10/3"], 1,
      ["Bu değer kırmızı çekme olasılığıdır; soru bunun dışındakini istiyor.",
       "doğru",
       "Bu değer tek bir topun olasılığına karşılık gelir; kırmızı olmayanlar birden çoktur.",
       "Olasılık 1'den büyük olamaz; bu değer ölçeğin dışındadır."],
      "Bütün olasılıkların toplamı 1'dir. Kırmızı çekme olasılığı 3/10 olduğuna göre kırmızı "
      "olmayan çekme olasılığı 1 − 3/10 = 7/10'dur.",
      "3 adım; ön bilgi: tümleyen olayın olasılığının 1'den çıkarılarak bulunması; çeldiriciler yakın (verilen değeri yineleme, ölçek dışına çıkma); beceri: hesaplama",
      ["Bir deneydeki bütün olasılıkların toplamının kaç olduğunu hatırla.",
       "Verilen olasılığı yaz.",
       "Geriye kalan payın ne kadar olduğunu düşün.",
       "1 sayısını aynı paydada yazıp çıkarmayı dene.",
       "Tam çözüm: 1 = 10/10'dur; 10/10 − 3/10 = 7/10 bulunur."]),
    S(2, "Adil bir zar atma deneyinde “5 gelmesi” ifadesi neyi belirtir?",
      ["Deneyi", "Olası sonuçların tamamını", "Bir olayı", "Olasılığı"], 2,
      ["Deney, zarın atılması işleminin kendisidir.",
       "Olası sonuçların tamamı 1, 2, 3, 4, 5 ve 6'dır.",
       "doğru",
       "Olasılık bu olayın gerçekleşme ihtimalini gösteren sayıdır: 1/6."],
      "Deney zarın atılmasıdır; olası sonuçlar 1'den 6'ya kadar olan sayılardır. “5 gelmesi” ise "
      "bu sonuçlar içinden ilgilendiğimiz grubu, yani bir olayı belirtir.",
      "2 adım; ön bilgi: deney, olası sonuçlar, olay ve olasılık terimlerinin ayrımı; çeldiriciler yakın (aynı konunun terimleri); beceri: kavram bilgisi",
      ["Zar atma işleminin kendisine ne dendiğini söyle.",
       "Gelebilecek bütün sayıların listesini yaz.",
       "“5 gelmesi” ifadesinin bu listenin tamamı mı bir parçası mı olduğunu belirle.",
       "Bir sayı mı yoksa bir durum mu tanımlandığına karar ver.",
       "Tam çözüm: “5 gelmesi” olası sonuçların bir alt grubudur, yani bir olaydır."]),
    S(5, "Bir öğrenci “bir torbada kırmızı top sayısı fazlaysa kırmızı çekme olasılığı da her zaman daha yüksektir” demiştir. Bu iddia için ne söylenebilir?",
      ["Doğrudur; kırmızı sayısı olasılığı tek başına belirler",
       "Yanlıştır; toplam top sayısı da hesaba katılmalıdır",
       "Yanlıştır; olasılık yalnız toplam top sayısına bağlıdır",
       "Doğrudur ama yalnız zar deneylerinde geçerlidir"], 1,
      ["Kırmızı sayısı tek başına yetmez; aynı kırmızı sayısı farklı toplamlarda farklı oran verir.",
       "doğru",
       "Toplam tek başına da yetmez; olasılık istenen sonuç sayısının toplama oranıdır.",
       "İddia zar deneylerinde de geçerli değildir; her deneyde oran belirleyicidir."],
      "Olasılık, istenen sonuç sayısının olası sonuç sayısına oranıdır. 6 kırmızısı olan 20 toplu "
      "bir torbada oran 6/20 = 3/10 iken 4 kırmızısı olan 10 toplu torbada 4/10'dur; kırmızı "
      "sayısı fazla olan torbada olasılık daha düşüktür.",
      "5 adım; ön bilgi: olasılığın ham sayıya değil orana bağlı olması; çeldiriciler yakın (tek bir sayıyı belirleyici sanma); beceri: akıl yürütme; hata teşhisi",
      ["Olasılığın hangi iki sayıdan hesaplandığını yaz.",
       "İki torba örneği kurup birinde kırmızıyı fazla, toplamı da çok yap.",
       "İki torba için oranları hesapla.",
       "Kırmızı sayısı fazla olan torbanın oranının her zaman büyük çıkıp çıkmadığına bak.",
       "Tam çözüm: 6/20 = 3/10 ile 4/10 karşılaştırıldığında kırmızısı fazla olan torbanın oranı daha küçüktür; toplam da hesaba katılmalıdır."]),
    S(1, "Yarın güneşin doğması olayı için ne söylenir?",
      ["İmkânsız olaydır", "Kesin olaydır", "Eşit olasılıklı olaydır", "Olasılığı 1/2'dir"], 1,
      ["İmkânsız olay hiç gerçekleşmeyen olaydır; güneşin doğması beklenen bir durumdur.",
       "doğru",
       "Eşit olasılık iki sonucun aynı şansa sahip olması demektir; burada böyle bir durum yoktur.",
       "Yarım değeri eşit olasılığı gösterir; mutlaka gerçekleşen olay için kullanılmaz."],
      "Mutlaka gerçekleşeceği bilinen olaylara kesin olay denir ve olasılıkları 1'dir.",
      "1 adım; ön bilgi: kesin olay ve olasılığının 1 olması; çeldiriciler yakın (ölçeğin diğer noktaları); beceri: kavram uygulama",
      ["Olayın gerçekleşmeme ihtimalinin olup olmadığını düşün.",
       "Mutlaka gerçekleşen olaylara ne dendiğini hatırla.",
       "Bu olayların olasılığının kaç olduğunu söyle.",
       "Değeri ölçek üzerinde yerleştir.",
       "Tam çözüm: olay mutlaka gerçekleşeceği için kesin olaydır ve olasılığı 1'dir."]),
]


def _dondur(secenekler, gerekceler, kaynak, hedef):
    """choices ve distractorWhy'a AYNI anda uygulanan döngüsel kaydırma."""
    kaydir = (kaynak - hedef) % len(secenekler)
    yeni_s = secenekler[kaydir:] + secenekler[:kaydir]
    yeni_g = gerekceler[kaydir:] + gerekceler[:kaydir]
    assert yeni_s[hedef] == secenekler[kaynak]
    assert yeni_g[hedef] == gerekceler[kaynak] == "doğru"
    return yeni_s, yeni_g


def _kayit(qid, kazanim, note_id, topic, s, hedef):
    secenekler, gerekceler = _dondur(list(s["choices"]), list(s["distractorWhy"]),
                                     int(s["correct"]), hedef)
    return {
        "type": "question", "id": qid, "subject": "Matematik", "topic": topic,
        "noteId": note_id, "objective": kazanim, "objectiveSource": KAYNAK,
        "level": s["level"], "question": s["question"], "choices": secenekler,
        "correct": hedef, "distractorWhy": gerekceler,
        "explanation": s["explanation"], "difficultyReason": s["difficultyReason"],
        "figure": None, "hints": s["hints"],
        "provenance": "machine-generated:claude-opus-5:2026-08:a3-celdirici-yeniden-uretim:human-pending",
        "reviewStatus": "pending", "correctIndex": hedef,
    }


def uret():
    kayitlar = []
    for i, (note_id, s) in enumerate(A14, start=1):
        kayitlar.append(_kayit(f"tr.g05.mat.5.1.4.q{i:03d}", "MAT.5.1.4", note_id,
                               "Kesirleri karşılaştırma", s, (i - 1) % 4))
    for i, s in enumerate(A62, start=1):
        kayitlar.append(_kayit(f"tr.g05.mat.5-6-2.q{i:03d}", "MAT.5.6.2", N6,
                               "Olayların olasılıklarını karşılaştırma", s, (i - 1) % 4))
    return kayitlar
